- docs/examples/ModalStatic.js
- src/Modal.jsx
- test/ModalSpec.jsx
Standard bootstrap modals add `modal-open` css class to document.body when they are opened to ensure proper overflow/scrolling of large modals.  This PR adds `modal-open` to the container of the react-bootstrap modal (which defaults to document.body unless otherwise specified).  This works as expected both for global modals and contained modals:
http://screencast.com/t/Uqhp66HD9Nlp
@pcardune @kellyrmilligan @mwaylonis @cmwelsh - You have all commented on or submitted possible solutions to this modal issue.  Can you verify that this PR satisfies your needs?
> add modal-open class to modal container when open

- src/OverlayMixin.js
- test/OverlayMixinSpec.jsx
Use case:
Large table in which there is an item using OverlayMixin on every row.
If a `<span />` is returned by renderOverlay(), using React Dev Tools can be frustrating as the tree is littered with `<span />`s
> Update OverlayMixin to allow for a null overlay

- docs/examples/DropdownButtonNoCaret.js
- docs/src/ComponentsPage.js
- src/DropdownButton.jsx
- test/DropdownButtonSpec.jsx
Fixes react-bootstrap/react-bootstrap#341
Add a `noCaret` prop to DropdownButton that will prevent a caret from being rendered next to the button's title.
@trentgrover-wf
> Add noCaret prop to DropdownButton

- docs/examples/PanelListGroupFill.js
- docs/src/ComponentsPage.js
- src/Panel.jsx
- test/PanelSpec.jsx
For react-bootstrap/react-bootstrap#228
Having multiple body elements in the panel is going to unavoidably screw up the collapse behavior, unfortunately, but it works otherwise.
> Support panel-filling tables and list groups

- Gruntfile.js
- package.json
Use grunt-karma to run the "npm run" karma tasks instead of shell
commands, for windows users.
> Use grunt-karma for npm run test

- src/Input.jsx
- test/InputSpec.jsx
This allows for specifying a size, such as input-group-sm and input-group-lg, as in:
<Input
type="text"
placeholder="Search"
inputGroupClassName="input-group-sm"
buttonAfter={<Button><Glyphicon glyph="search" /></Button>}
/>
Before:
After:
> [added] inputGroupClassName prop to Input

- src/Col.jsx
- test/ColSpec.jsx
According to the Bootstrap documentation (and my own experience), column offsets must be reset to zero for other sizes if not used.
"In addition to column clearing at responsive breakpoints, you may need to reset offsets, pushes, or pulls. See this in action in the grid example."
For example `<Col xsOffset={2} xs={8} sm={4} md={4} lg={4}>...</Col>` when viewed in 'sm/md/lg' does not produce the expected result of having a column width of '4'. It looks only correct when viewed in 'xs'.
The example would have to be rewritten as `<Col xs={8} xsOffset={2} sm={4} smOffset={0} md={4} mdOffset={0} lg={4} lgOffset={0}>...</Col>` to render correctly in all views.
However, Offset/Push/Pull property values were ran through a "truthy" check in Col.jsx. So when the property value was `0` the column …
> Col Push/Pull/Offset value zero support

- docs/examples/CollapsableParagraph.js
- docs/src/ComponentsPage.js
- docs/src/ReactPlayground.js
- src/BootstrapMixin.js
- src/CollapsableMixin.js
- src/Panel.jsx
- src/PanelGroup.jsx
- test/BootstrapMixinSpec.jsx
- test/CollapsableMixinSpec.jsx
- test/PanelSpec.jsx
* Added internal 'is expanded' tracking (see comments in mixin)
* Added basic `CollapsablePanel` example
* Added aria-expanded attributes to Panel
* Fixes expand/collapse animation for stand-alone panel
* Fixes #399, where the panel would stay a fixed size
Fixes #399
> [changed] CollapsableMixin state tracking

- docs/examples/CollapsableNav.js
- docs/src/ComponentsPage.js
- docs/src/ReactPlayground.js
- src/CollapsableNav.jsx
- test/CollapsableNavSpec.jsx
- tools/amd/index.js
- tools/cjs/main.js
These proposed changes will allow for a cleaner implementation of the bootstrap collapse component. Most of the functionality was moved up from the Nav element. This handles the correct sizing and doesn't offset the navbar elements where there are multiple `<Nav>` elements as was the original issue that led me down this path.
```html
<Navbar toggleNavKey={1}>
<Collapsable eventKey={1}>
<Nav navbar={true}>
<NavItem>Item 1</NavItem>
<NavItem>Item 2</NavItem>
</Nav>
<Nav right={true} navbar={true}>
<NavItem>Right Item 1</NavItem>
<NavItem>Right Item 2</NavItem>
</Nav>
</Collapsable>
</Navbar>
```
> Results:
```html
<nav role="navigation" class="navbar navbar-default">
<div class="container">
<div class="navbar-header">
<button class="navbar-toggle" type="button">
<span class="sr-only">Toggle …
```
> Add Collapsable class that can handle multiple Nav objects

- src/OverlayTrigger.jsx
I created this pull request because I was seeing a significant amount of layout thrashing when I had several hundred tooltips being rendered at once. It seems the layout was invalidated by the overlay position calculation fired within `componentDidMount`. By checking `this.props.defaultOverlayShown`, we can avoid this layout reflow when mounting an OverlayTrigger which is not shown by default (should be the only time this calc needs to happen in `componentDidMount`??). I am not sure this will fully resolve #353 , but it helped my implementation quite a bit.
Chrome dev tools with several hundred tooltips:
Before: http://i.imgur.com/e4UZ5l6.png , http://i.imgur.com/Tw39F9t.png 
After: http://i.imgur.com/bU0f7VY.png .
> Added check if we don't need to calc calculate the overlay position on mount

- src/Carousel.jsx
- test/CarouselSpec.jsx
This PR is based on #405. I’ve changed the commit message and added a test.
Closes #405.
> Fixed behaviour of carousel controls if wrap=true

- src/NavItem.jsx
Current NavItem titles are restricted to strings, which is not how Bootstrap was designed. Changing this to node to allow for more complicated functions.
> Changing NavItem title prop to node

- src/AffixMixin.js
- src/DropdownStateMixin.js
- src/FadeMixin.js
- src/Modal.js
- src/OverlayMixin.js
- src/utils/domUtils.js
With this change, event listeners are attached to the component DOM node's owner document instead of to the window root document. The two are not the same when the component is mounted inside an IFrame, for example using [react-frame-component](https://github.com/ryanseddon/react-frame-component).
In my case, this fixes incorrect positioning of tooltips and broken close handlers of dropdown buttons.
> Use .ownerDocument instead of root document

- .eslintrc
It removes 17 unnecessary eslint warnings.
Since 0.17.0 the ESLint no-unused-vars rule does not detect variables used in JSX
[react/jsx-uses-vars](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-uses-vars.md)
Like in: (Button.js)
```javascript
let Component = this.props.componentClass || 'a’;
...
return (
<Component ...
```
eslint warning: `Component is defined but never used.`
> Add react/jsx-uses-vars option for eslint.

- src/AffixMixin.js
- src/DropdownStateMixin.js
- src/FadeMixin.js
- src/Modal.js
- src/OverlayMixin.js
- src/utils/domUtils.js
- test/OverlayMixinSpec.js
As noted by @lukemcgregor on ee0382e that code breaks when trying to access `.ownerDocument` on `null`.
I attempt to fix that here by using the root document as a fallback and abstracting that to a domUtils function.
I also added one test case for this fix, but I'm not sure it's the best way to test it.
> [fixed] Don't try to access .ownerDocument on null

- src/Carousel.js
- src/CollapsableNav.js
- src/PageItem.js
Accorging to http://www.w3.org/TR/WCAG20-TECHS/H33.html
The `title` attribute is used to provide additional information to help clarify
or further describe the purpose of a link.
Еherefore I set type for `title` to `string`.
> Define types for properties to satisfy eslint warnings for src/*. (6 less)

- docs/.eslintrc
- ie8/.eslintrc
- src/TabbedArea.js
- test/.eslintrc
- test/BadgeSpec.js
After that there is only 25 warnings left.
And all of them are for src/*
> 44 less superfluous eslint warnings in docs and tests.

- src/Nav.js
- src/PanelGroup.js
- src/SubNav.js
I wasn't able to find a way to add only one option { ignore: "bsStyle" } to file 
in comments block /* .. */ so that others options { ignore: ["children", "className"] } 
from .eslintrc would be merged with it.
It seems there is no way to merge eslint options in comments /* ... */
with options from .eslintrc.
> [fixed] Missed propTypes validations for Nav, SubNav and PanelGroup.

- docs/build.js
- docs/server.js
- docs/src/CodeMirror.client.js
- docs/src/CodeMirror.js
- docs/src/NavMain.js
- docs/src/Routes.js
- ie8/server.js
- package.json
- tools/amd/build.js
- tools/build.js
- tools/dist/build.js
- tools/fs-utils.js
- tools/lib/build.js
- tools/release-scripts/changelog.js
- tools/release-scripts/pre-conditions.js
- tools/release-scripts/release.js
- tools/release-scripts/repo-release.js
- tools/release-scripts/tag-and-publish.js
- tools/release-scripts/test.js
- tools/release-scripts/version-bump.js
- webpack/strategies/development.js
- webpack/strategies/docs.js
- webpack/strategies/ie8.js
- webpack/strategies/optimize.js
- webpack/strategies/test.js
- webpack/webpack.config.js
In eslint 0.19.0 were fixed `semi` and `no-unused-vars` rules for ES6 code.
> [fixed] Update eslint dev dependency and fix new warnings.

- src/ProgressBar.js
Using stacked ProgressBar with a maximum superior to 100 could lead to
rounding issues that made the bar incomplete.
See issue #396 for mor details on the error
> [fixed] ProgressBar percentage issue when stacked

- docs/client.js
- docs/src/CodeMirror.client.js
- ie8/src.js
- package.json
- test/index.js
- tools/build.js
- tools/lib/build.js
- tools/release-scripts/changelog.js
- tools/release-scripts/pre-conditions.js
- tools/release-scripts/repo-release.js
- tools/release-scripts/test.js
- tools/release-scripts/version-bump.js
`import from` => `import`
Babel is more strict now as for `import` syntax.
According to
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import
>Import an entire module for side effects only, without importing any bindings.
>`import "my-module.js";`
> [fixed] Fix ES6 syntax for 'import'. Dev dependency update.

- test/FormGroupSpec.js
- test/InputSpec.js
- test/index.js
- webpack/webpack.config.js
This is a fix for bug in tests, discovered by bug #507.
When mode is `production` webpack strips out code for development mode.
React `console warnings` also are removed in `production`.
In that case tests don't `see` any console warnings from React.
Consequently code like this (in tests)
console.warn.called.should.be.false;
is useless.
Also this PR contains some refactoring for tests.
1) Refactor DRY code. Move it to global space.
2) Checking console warnings is done for all components now. It's a win.
3) Also this is some help for future React deprecations detections.
The `stub` is used instead of `spy` to prevent console output polluting.
But anonymous function in second argument of `assert` gives us
the warning message we should be aware of if the test fails.
This PR is also a …
> [fixed] Fix for tests.

- src/BootstrapMixin.js
- src/Col.js
- src/Glyphicon.js
- src/index.js
- src/styleMaps.js
- src/utils/CustomPropTypes.js
- test/BootstrapMixinSpec.js
- test/CustomPropTypesSpec.js
Proposed fix for #306 and partial fix for #440.
> [added] styleMaps.addStyle and CustomPropTypes.keyOf

- docs/src/ReactPlayground.js
Bug was introduced by babel@5 update.
I had missed then console output about `className ReferenceError`.
The output of `compiledCode` content with error in console
helped to find quickly where exactly was the error.
> Fix bug in ReactPlayground.

- src/Input.js
- test/InputSpec.js
Beginning is at #509.
Actually the fix itself begins from `Add tests for fixing bug507` [552de20](https://github.com/react-bootstrap/react-bootstrap/commit/552de20)
TravisCI would fail without merging #513.
And it would need to create additional PR for test unskipping.
With #513 this PR is `green` on TravisCI https://travis-ci.org/AlexKVal/react-bootstrap/builds/58300955
> [fixed] Fix for #507

- src/ListGroup.js
- test/ListGroupSpec.js
Check if child is array before accessing props
fixes #548
> [fixed] ListGroup work with single child contained in array

- src/TabbedArea.js
The check is doing by React now.
```js
propTypes: {
defaultActiveKey: React.PropTypes.any
```
This comment had served as trigger for the idea at https://github.com/react-bootstrap/react-bootstrap/issues/574 at the first place.
> Remove stale TODO note.

- tools/build.js
Conversation is here #547.
Idea for this patch totally belongs to @mtscout6.
I have just tested it and made PR.
As @dozoisch has mentioned  
> docs-build runs with docs-only and doesn't take the same branch in the file
There is no recursion in scripts and everything works fine as expected.
> Fix for bug 547 in tools/release.

- src/ListGroup.js
- src/ListGroupItem.js
- test/ListGroupSpec.js
Currently 
```html
<ListGroup>
<ListGroupItem onClick={() => null}>1st Child</ListGroupItem>
<ListGroupItem>2nd Child</ListGroupItem>
</ListGroup>
```
will result in
```html
<ul class="list-group">
<a class="list-group-item active">1st Child</a>
<span class="list-group-item">2nd Child</span>
</ul>
```
This P/R fixes the above to render a `<div>` instead.
A test case has also been added to `ListGroupSpec.js`
> [fixed] ListGroup rendering a ul when ListGroupItem has an onClick handler

- tools/amd/build.js
- tools/build.js
- tools/constants.js
- tools/dist/build.js
- tools/lib/build.js
- tools/release-docs-scripts/release-docs.js
- tools/release-scripts/changelog.js
- tools/release-scripts/release.js
- tools/release-scripts/version-bump.js
As you suggested in my other pull request (https://github.com/react-bootstrap/react-bootstrap/pull/536) the ```src/``` root folder was a good candidate to add to constants. I also added constants for other folders which simplified the build files. Since I took it a bit further I thought it better to create a separate PR.
> Use new path constants

- src/TabbedArea.js
- test/TabbedAreaSpec.js
TabbedArea TabPane rendering doesn't carry across the className
property.  This means it is not easy for users to customize
the look/feel of the tabs.
Added className to the properties copied in the renderTab function
and also pass additional properties down via ...other
> [added] TabbedArea NavItem renderTab() className [fixes] #516

- README.md
I added a wiki page which has the 1.0.0 road map. I'm looking for feedback on what else we should put in there. When this pull request is done I'll remove the "[Draft]" specifier and that will be our goal. I did not put a release date, because... it will be ready when it's ready.
https://github.com/react-bootstrap/react-bootstrap/wiki#100-roadmap-draft
/cc @react-bootstrap/collaborators
> Add link to 1.0.0 Roadmap in README

- src/Input.js
- test/InputSpec.js
react-bootstrap/react-bootstrap#342
By converting over to use an es6 class we could have future components such as `Submit` and `RadioGroup` extend the current implementation and override a some of the provided hooks.
Hooks provided:
* `renderInput()`
* `renderFormGroup()` - I *really* dislike that `if type=submit` check, so I planned to use this hook in the `Submit` implementation.
* `renderChildren()` - This could potentially be overriden in the `Checkbox` and `Radio` implementations so we could ditch that `isCheckboxOrRadio()` check.
There might be a few others that would be useful to override that I haven't mentioned in the list. This could be a little more refined.
> Convert Input to es6 class

- src/DropdownButton.js
- test/DropdownButtonSpec.js
As mentioned on #376, making rounded buttons using classes becomes harder unless we can add custom classes to the wrapped Button element. 
Before fixing #376 this worked OK, but the change broke existing code (ie. code that assumed the classes went to the Button element) that cannot be fixed unless this property is introduced.
> Support adding button class to DropdownButton

- tools/build.js
This was a minor issue I saw during the last release.
> Fix building docs status updates with `npm run build`

- test/index.js
When I add deprecation warning for any element,
afterEach() hook catch it, but it is not clear in which test.
```
✖ "after each" hook
AssertionError: collapsable in CollapsibleNav is deprecated. Use collapsible instead. 
```
with this fix it adds a line with a full "path" of the failed test:
```
...
In 'CollapsibleNav Should create div and add collapse class'
```
> Show test title in afterEach() hook.

- src/utils/deprecationWarning.js
I realize the check for `NODE_ENV === production` fixes the issue for production builds but I regularly test with IE9 locally while developing.
> [IE9] Check for console before using console.warn

- src/ListGroup.js
- test/ListGroupSpec.js
Fixed `ListGroup` render to allow setting id on element through spread `{...this.props}` on element.
> [fixed] #597 able to set ID on ListGroup

- docs/src/GettingStartedPage.js
- package.json
- src/templates/factory.index.js.template
- src/templates/factory.js.template
- test/FactoriesSpec.js
- tools/amd/build.js
- tools/generateFactories.js
- tools/lib/build.js
- tools/public-components.js
Allows import of components pre-wrapped in factories with 'react-bootstrap/lib/factories'.
I had same problem as this guy: https://github.com/react-bootstrap/react-bootstrap/issues/423.
> adds ability to require components already wrapped in factories

- docs/server.js
```sh
$ npm run docs
...
WARNING in ./~/babel-core/browser.js
...
This seems to be a pre-built javascript file. ...
```
> Get rid of webpack warning with `npm run docs`

- docs/examples/ModalContained.js
- docs/examples/ModalOverlayMixin.js
- docs/examples/ModalStatic.js
- docs/examples/ModalTrigger.js
- src/Modal.js
- test/ModalSpec.js
Vanilla Bootstrap Modal does not have the CSS class `hidden` by default on the `div.modal-content`. It was added to react-bootstrap in commit https://github.com/react-bootstrap/react-bootstrap/commit/13f395d2304727d65ee22242423150c22b73addb that added support for bsStyle property to Modal for setting the header color. There were a number of changes and why `hidden` was added to `div.modal-content` isn't clear.
My reason for not wanting this is when using say react-select inside a modal, the dropdown should be visible in the event it overflows the modal.
> [fixed] Modal div.modal-content should not have hidden class

- .babelrc
- karma.conf.js
- package.json
- register-babel.js
- run-babel
- tools/amd/build.js
- tools/build-cli.js
- tools/build.js
- tools/generateFactories.js
- tools/lib/build.js
- tools/release
- tools/release-docs
- tools/release-scripts/release.js
- webpack.config.js
- webpack.docs.js
- webpack/webpack.config.js
This will allow us to configure babel in one central location from now
on. Prior to this any time we ran a babel compile, babel-loader, or
babel-node we had to configure them individually which can be error
prone in the long run.
> Use .babelrc for babel configuration

- docs/examples/InputSizes.js
- docs/src/ComponentsPage.js
- docs/src/Samples.js
- src/FormGroup.js
- test/FormGroupSpec.js
- test/InputSpec.js
`FormGroup` now honors the `bsSize` property by applying form-group-lg and form-group-sm, for bsSize="large" and bsSize="small", respectively. 
This allows us to do something as simple as `<Input bsSize="large" />` which was not possible before.
> Input bsSize now propgates correctly for css form-group-\*

- docs/src/ComponentsPage.js
- docs/src/IntroductionPage.js
- docs/src/NavMain.js
- docs/src/Root.js
- docs/src/Routes.js
This PR is kind of proposal / draft.
Critics and additions are welcomed.
This work is based on `git cherry-pick`s from Matthew Honnibal PR
syllog1sm@3e54374
syllog1sm@a7e749e
syllog1sm@6f44556
Also added missed space on ComponentsPage.
This PR is successor of #149.
> Simple Introduction Page

- .travis.yml
- karma.conf.js
- package.json
Reverts react-bootstrap/react-bootstrap#630
It seems TravisCI didn't like my play with 26 re-runs of tests using Chrome
and they have disabled `chromium-browser`.
Back to `PhantomJS` because of new PR's failing tests.
> Revert "Use Chrome on TravisCI instead of PhantomJS."

- .travis.yml
- karma.conf.js
- package.json
Reverts react-bootstrap/react-bootstrap#635
Today I received notice about `karma-chrome-launcher` update.
The only commit in this version is `put 'which' back` https://github.com/karma-runner/karma-chrome-launcher/commit/d2c7f23cc63c656b024c52e702ba34d142d96436
As it turned out it is a cure for yesterday's problem with `Travis + Chrome`.
(Travis had not been deleting `chromium`. hurray :balloon: )
I've checked it [on my travis acc](https://travis-ci.org/AlexKVal/react-bootstrap/builds/61951566) before doing this revert of `revert`.
> We again "Use Chrome on TravisCI instead of PhantomJS.""

- docs/src/ComponentsPage.js
* Fix some spacing around code blocks
* `OverlayMixin` is not a component
* Consistently use double quotes for attributes/JSX props
> Copyediting fixes to component documentation

- src/FormGroup.js
- test/FormGroupSpec.js
- test/helpers.js
> Don't warn about bsSize when it's not specified

- package.json
https://github.com/webpack/extract-text-webpack-plugin/issues/57 is resolved.
I've checked how it looks `npm run docs` now.
The same as with 0.3.8.
I'm not merging it because I may miss something subtle,
because there are no code tests for this issue, only visual.
At least it needs @mtscout6 visual check and therefore approval.
> [changed] Updated extract-text-webpack-plugin. Dev dependency.

- src/ModalTrigger.js
- src/OverlayTrigger.js
- src/utils/createContextWrapper.js
- test/ModalTriggerSpec.js
- test/OverlayTriggerSpec.js
For react-bootstrap/react-bootstrap#465
No need to document this. If this is accepted, I'm going to add an `OverlayTriggerWithRouterContext` (better name welcome) to react-router-bootstrap to make that use case easier.
I don't think there's a better way to do this than to make a new component class every time because of `childContextTypes` and `contextTypes` both being static.
> Add context-forwarding trigger factory methods

- docs/build.js
- docs/server.js
- docs/src/Root.js
Return `<DOCTYPE!>` to pages.
First time it was introduced here
https://github.com/react-bootstrap/react-bootstrap/blob/120ba6d38a4/Gruntfile.js#L204
Then it was moved here
https://github.com/react-bootstrap/react-bootstrap/commit/addc3965b0d832a3721983d0a891a03a086c8225#diff-31cfa4797a188b7ab32b049b80c82ea6R63
And finally it was lost `Root` => `React` easy to overlook
from `var RootHTML = Root.renderToString()`
to `var RootHTML = React.renderToString()`
here
https://github.com/react-bootstrap/react-bootstrap/commit/804c24a33f390166a89276f68772fa64b1510ba8#diff-4cd8a3a29faaf037ff2ec547bf1635abL10
and here
https://github.com/react-bootstrap/react-bootstrap/commit/804c24a33f390166a89276f68772fa64b1510ba8#diff-ce9d98be04f7a23d325c274fc1a0a089L21
After that `Root.renderToString()` method (and …
> Return <DOCTYPE!> back and little refactoring of docs/build.js

- src/Carousel.js
- src/TabbedArea.js
- test/CollapsibleNavSpec.js
Detection of them has become possible as a result of https://github.com/babel/babel-eslint/pull/97
ref: [space-infix-ops](http://eslint.org/docs/rules/space-infix-ops)
> Fix eslint `space-infix-ops` rule warnings.

- src/ButtonInput.js
It was my fault adding wrong disabling syntax.
This line
```js
/* eslint no-unused-vars: 0 object-shorthand: 0 */
```
spreads out on the whole file regardless where it is placed.
> Fix eslint one-line disabling.

- src/Panel.js
- test/PanelSpec.js
Currently we're clobbering the classes on the passed-in element.
> [fixed] Forward classes to panel title

- package.json
Upgrade to ^0.21.2 after release fixes eslint/eslint#2545
Per https://gitter.im/eslint/eslint?at=555637f5811d64626eebc65f, it will be at least a day or two until a new bugfix release comes out, so we might as well downgrade to get CI to pass.
> Downgrade eslint to get linting to pass

- webpack/strategies/docs-development.js
Without this commit we've got
`{ test: /\.json$/, loader: 'react-hot!json' }`
and it should be just as
`{ test: /\.json$/, loader: 'json' }`
> Fix regexp to test regexps in tools.

- webpack/strategies/test.js
Without this test failure stack traces were getting reported based on the finalized concatenated file by webpack.
> Fix sourcemaps in test error stack traces

- .eslintignore
- package.json
There's no need to explicitly white list AND black list what we are linting. So, let's just use the black list from the .eslintignore file.
> Cleanup Lint command

- src/Popover.js
- src/Tooltip.js
- test/PopoverSpec.js
- test/TooltipSpec.js
This adds the `animation` property to the `Tooltip` and `Popover` components by adding the `FadeMixin` and an `animation` property to those components.
This will use the have the `animation` property set to `true` by default since that is consistent with Bootstrap.
This also adds a test spec for Popover and Tooltip since one didn't exist before.
> [added] Property for animation on Popover and Tooltip

- docs/examples/DropdownButtonBasic.js
- src/MenuItem.js
- test/MenuItemSpec.js
This adds an `active` property to the `MenuItem` component in order to set the `active` class. The result is a highlighted item in the dropdown menu.
The default value for the property is `false` in order to adhere to the Bootstrap default.
This should take care of #352
> [added] Active property to MenuItem component

- docs/build.js
- package.json
- tools/build-cli.js
- webpack/webpack.config.js
Useful for debugging production issues that do not manifest in the dev
isomorphic and hot reloading scenario.
Inspired by #677 (Helps us solve that bug :smile:)
> Add npm run script for docs prod unoptimized preview

- docs/src/Root.js
Fixes most of #677 
The only part it does not fix is on the home page if the url does not include `index.html`. This is because react-router is placing an `active` class name on the brand in the `Navbar`. I don't see a quick easy way to deal with that at the moment.
> Fix single quote bugs for docs in production

- docs/examples/CollapsibleParagraph.js
- docs/src/ComponentsPage.js
- docs/src/ReactPlayground.js
- src/CollapsibleNav.js
https://facebook.github.io/react/blog/2015/03/10/react-v0.13.html
https://facebook.github.io/react/docs/component-api.html#getdomnode
> getDOMNode() has been deprecated. Use React.findDOMNode() instead.

- karma.conf.js
- package.json
There is a bug with Chrome right now that makes testing rather painfully
slow if no part of the Chrome windows is visible. This has made it
really difficult to do much very fast since I'm constantly waiting for
Chrome to complete running tests. The bug is defined in
https://github.com/karma-runner/karma-chrome-launcher/issues/44.
The difference in test execution time is currently 30 seconds if not
visible, or 1.5 seconds when it is. Since I get the same results via
Phantom I'd like have the option to quickly do so when needed.
> Add capability to run Phantom locally

- .travis.yml
Node 0.12 keeps getting killed for no distinguishable reason, and we
aren’t really doing anything that targets anything in the core of Node.
Our tests are run in a browser which is the really important part, and
the tools we use test the various releases, so we could rely on their
successful runs.
When the merger between Node and iojs completes then we'll change to the
latest release they produce together.
> Only run CI against latest iojs

- webpack/base.config.js
This should handle the race condition @AlexKVal encountered with the build process as addressed in https://github.com/react-bootstrap/react-bootstrap/pull/710#issuecomment-104021320.
> Handle race condition with creation of babel-cache directory

- package.json
just for ref in the new `css-loader` version added
[new :local syntax](https://github.com/webpack/css-loader/commit/475d39e763050397b83f342760b87470efdd7e7e)
added experimental :extend and from syntax
> [changed] Update css-loader. Dev dependency.

- package.json
- src/Modal.js
- test/server/ModalSpec.js
Using document reference in the render method will throw an error
on React.renderToString call on the server side.
See react-bootstrap/react-bootstrap#717.
The proper solution is to remove document.querySelector check. Obviously
we cant detect this feature on the server side, besides it leads to
differencies btw server and client side rendering output, so React will warn
about it, ex:
1. `render` on the server side will apply classes: `modal fade`
2. `render` on the client side will apply clasess: `modal fade in`
Also karma test environment is not suitable for testing server side rendering,
so mocha test run againt nodejs was added.
> [fixed] server side rendering for Modal component

- src/utils/deprecationWarning.js
Checking for window object gives reference error in node.js (isomorphic apps) so do typeof check instead.
> Fix deprecationWarning for node

- src/Modal.js
- test/ModalSpec.js
Modals are now focused when opening them, as requested by #612 . I've also stored the element that was previously focused, so its focused can be restored when the Modal is closed (it is the same behaviour Bootstrap does).
I was unable to do tests for this, as it has a dependency on document.activeElement (and the tests I've looked into only used TestUtilities.renderIntoDocument, which renders to a detached DOM node, so I'm guessing we can't test this without attaching it to the DOM).
> Modals are focused on opening, for improved acessibility

- src/OverlayTrigger.js
Fixes #724 
Was calculating bod scrollTop in a way that didn't work in Firefox. This bug is not present on IE11.
Checked by hand with Chrome 44, Firefox 40, Safari 8 on OS X 10.10 because I'm still not sure how I'd write proper tests for this.
> [fixed] Fix scroll top calculation for overlays

- package.json
`npm run docs-prod` Visually docs seem are the same.
There is only one change in code [module mode](https://github.com/webpack/css-loader/commit/42db9bc4b29c7709eaa0fc022a796a3383bd4f09) actually.
And for us it is not breaking.
--
module mode [breaking change]
new extends syntax
added :global and :local
added module mode
removed old deprecated syntax
breaking change if you are using local scope (it was experimental)
> Update css-loader 0.14.1 Dev dependency.

- src/CollapsibleNav.js
- test/CollapsibleNavSpec.js
Because of `-2` this code `indexOf('navbar-collapse') === -2` hasn't been working anyway.
But tests were green because the resulted logic was right someway.
This commit refactors it to clarify deduplication logic
by using `classnames'` [Alternate `dedupe` version](https://github.com/JedWatson/classnames/commit/9acbd433ee)
`classes['navbar-collapse'] = collapsible`
=>
`let classes = collapsible ? this.getCollapsibleClassSet('navbar-collapse')`
`getDOMNode()` => `React.findDOMNode()`
And test was refactored too.
We can count class occurrences much simpler as
```js
let occurrences = (classDOM.match(/navbar-collapse/g) || []).length
```
> Refactor duplication-removing logic for CollapsibleNav.

- docs/dev-run
- docs/server.js
- package.json
- webpack/docs.config.js
This is useful for cross-browser testing if you have VMs with dedicated versions of browsers.
Since the webpack-dev-server runs on a different port and we need to add http headers to allow cross-origin requests we need this in order to run the docs on one machine and test on another.
The drawback is that in order to reach the webpack-dev-server directly you will have to use the ip address and not `localhost`. Normal usage of the docs can still be reached with `http://localhost:4000` though.
> Add means to load local dev docs on a different machine

- .travis.yml
This is a temporary measure until nodejs/io.js#1850 is resolved.
> Locking down CI to iojs v2.1.0

- .babelrc
- package.json
- src/Interpolate.js
- src/OverlayTrigger.js
Instead of
`let props = Object.assign({}, this.props);`
use
`let props = {...this.props};`
which is transpiled into
`var props = _extends({}, this.props);`
Instead of
```js
return Object.assign({}, offset, {
height: node.offsetHeight,
width: node.offsetWidth
});
```
use
```js
// ES6
return {
...offset,
height: node.offsetHeight,
width: node.offsetWidth
};
```
which is transpiled into
```js
// ES5
return _extends({}, offset, {
height: node.offsetHeight,
width: node.offsetWidth
});
```
> Remove Dev dependency "babel-plugin-object-assign".

- package.json
Fixes `peerDependency` warning for webpack.
> Add explicitly node-libs-browser dependency.

- src/DropdownStateMixin.js
- src/RootCloseWrapper.js
Fixes a bug where attempting to close a button dropdown menu, by clicking the *button* itself did not close the menu.
`e.target` is undefined in IE8 so `isNodeInRoot` returned false, allowing the click event to bubble to the document and re-open the menu.
> [changed] Fix button dropdown not closing when clicking button on IE8

- src/ListGroupItem.js
- src/MenuItem.js
- src/NavItem.js
- src/PageItem.js
- src/SafeAnchor.js
- src/SubNav.js
- src/Thumbnail.js
- src/index.js
- test/NavSpec.js
- test/PageItemSpec.js
- test/SafeAnchorSpec.js
Bootstrap uses a lot of styling that is specifically targeting anchor
tags that may also serve in the capacity as a button. Unfortunately
since Bootstrap does not style said buttons we have to use an anchor
tag instead. But in order to maintain keyboard functionality for
accessibility concerns even those anchor tags must provide an href.
The solution is to add an internal `SafeAnchor` component which ensures
that something exists for the href attribute, and calls
`event.preventDefault()` when the anchor is clicked. It will then
continue to invoke any additional `onClick` handler provided.
> Keyboard accessibility for anchors serving as buttons

- src/ButtonInput.js
Yay.. Now we do not need to `escape` excludable properties
```js
let {bsStyle, value, ...other} = this.props;
```
by eslint-disable. :tada: 
Thanks to `babel-eslint@3.1.10` update.
> Remove - now extraneous - eslint warning disabling.

- docs/src/PageFooter.js
Without this you would see v0.23.1-docs.0 in the footer of the docs.
> In docs footer don't show docs version.

- tools/release-scripts/tag-and-publish.js
The default is `latest` which would install the pre-release for users
installing via `npm install react-boostrap`, which we don't want.
> Fixed pre-release to tag as such with npm publish

- tools/release-scripts/release.js
When I published v0.24.0-alpha.0 today the docs were published with it which is less than desirable. This should prevent that from happening again.
> Do not release docs when publishing pre-release

- docs/assets/docs.css
- docs/examples/MenuItem.js
- docs/src/ComponentsPage.js
- docs/src/Samples.js
- src/MenuItem.js
- test/MenuItemSpec.js
The test will currently fail, but I'll rerun them when https://github.com/react-bootstrap/react-bootstrap/pull/604 gets merged.
closes #246
> [added] property disabled on MenuItem

- src/ButtonInput.js
```
src/ButtonInput.js
9:9   warning  bsStyle is defined but never used  no-unused-vars
9:18  warning  value is defined but never used    no-unused-vars
```
https://github.com/babel/babel-eslint/issues/120
Alas, that was a bug, not a feature. :cry:
> Comment out no-unused-vars eslint warnings back.

- src/utils/createSelectedEvent.js
Related to #419 
This is the event that I have started using on the dropdown-revisited branch. Thought I'd pull the event from that branch in hopes that it may help with the events in #786
> [added] `createSelectedEvent` for consistent onSelect handling

- src/ProgressBar.js
- test/ProgressBarSpec.js
And strip out some technical debt.
Checking is done like this
`if (child.type.displayName !== ProgressBar.displayName)`
because neither
`child instanceof ProgressBar`
nor
`React.PropTypes.instanceOf(ProgressBar)`
work.  (don't know why)
I've tried it all hard.
Custom propTypes checker `function onlyProgressBar()` placed after `const ProgressBar` is defined
because of using `!== ProgressBar.displayName` in it.
It is possible to place it at the beginning of file 
if do checking against string constant `!== 'ProgressBar'`.
But I like idea to use generated `displayName` whatever it can be.
--
**Question**: 
What is the purpose of mystical `this.props.interpolateClass` ?
It was added here
[commit#diffR96](https://github.com/react-bootstrap/react-bootstrap/commit/2e120f3c7ecf230c4188e8d0f5fd793e …
> ProgressBar. Assert that chilren can be ProgressBar only.

- src/RootCloseWrapper.js
- src/utils/domUtils.js
just a small internal change, replace `isNodeInRoot()` in RootCloseWrapper, with a elem.contains polyfill in `domUtils`. It offers better performance than recursively walking up parentNodes, not that it matters much in the instances we use it, but its a few lines of code, so why not.
> Add contains "polyfill" to domUtils

- src/SafeAnchor.js
- test/SafeAnchorSpec.js
If we prevent default before applying the `onClick` function provided in
props then we prevent elements from using the `event.preventDefault()`
mechanics for anchors as buttons. For example in the Dropdown re-work
this prevented me from having the Dropdown work when in a Nav since the
toggle is an anchor. Yet that functionality should allow uses to prevent
the Dropdown if they want in their own `onClick` handler. This will
enable such a use case.
> [fixed] SafeAnchor event ordering

- tools/buildBabel.js
Remove links to babel internal api and only use what we really need.
Addresses discussion at #762 
@sebmck Sorry for using your private api, I didn't know how to do what I needed at the time and I wanted to remain as close as possible to the original behavior. I should have asked to expose the api instead of using it like this. 
After some inspection, I realized that I didn't really need the internal api since our need is very simple.
> Unlink babel internal api for build

- tools/amd/bower.json
Removed "classnames" from dependencies because webpack bundles it.
https://github.com/react-bootstrap/react-bootstrap/pull/822#issuecomment-111721675
> Fix bower template

- docs/dev-run
- package.json
:( Windows doesn't do shebangs, so it has no idea how to run that without
the command.
> Fix docs command for windows users

- src/utils/createChainedFunction.js
- test/utils/createChainedFunctionSpec.js
Changes `createChainedFunction` to chain many functions, and to throw if non-functions are provided.
Reasons I'm proposing this to master and not `v0.24.0-rc`:
- This works against all our existing usage of the function
- Not throwing before sounds like a bug to me
@jtenner ~~this introduces that improved function type check you proposed on gitter~~ There is a test proving this wasn't necessary.
@taion it's going to throw now when something other than a func is provided, as you proposed on gitter.
> createChainedFunction improvements

- .babelrc
- package.json
Fixes #579
Reduces size of `dist/react-bootstrap.min.js` from 121,221B to 116,282B at this commit.
Will need to resolve #840 or manually clear `.babel-cache` before building with this change.
As this is against v0.24 RC, no need to update e.g. Bower dependencies, but this is now a runtime dependency when using the standard build.
> Use babel-runtime transformer for helpers

- docs/examples/ModalStatic.js
- package.json
- src/Modal.js
- src/utils/domUtils.js
First few bits of getting the Modal logic up to par with upstream tbs. No breaking changes, no major api rewrites...yet
> Modal improvements

- docs/build.js
- tools/build-cli.js
- tools/build.js
- tools/dist/build.js
- tools/release-scripts/release.js
- webpack/base.config.js
~~Also use default Babel cache directory~~
Fixes #840
I don't know if this is the best/clearest way to do this. What this does is
1. Use cache by default in `build-cli.js`
2. Use cache by default when running `webpack`
3. Do not use cache by default in exported function from `tools/build.js`, and implicitly call that without setting `useCache` from `release.js`
> [fixed] Do not use Babel cache for release build

- src/Modal.js
- test/ModalSpec.js
fixes #842, only move focus to the Modal if `enforceFocus` is true
> [changed] only autofocus modals when enforceFocus is true (the default)

- package.json
changes https://github.com/eslint/eslint/releases/tag/v0.23.0
New:
[prefer-const](http://eslint.org/docs/rules/prefer-const) suggest using of const declaration for variables that are never modified after declared (off by default)
[spaced-comment](http://eslint.org/docs/rules/spaced-comment) require or disallow a space immediately following the // or /* in a comment (off by default)
p.s. what about  `v0.24-rc` ? cherry-pick it or create additional PR ?
> Update eslint. Dev dependency.

- CONTRIBUTING.md
- MAINTAINING.md
We regularly encounter issues that we cannot verify, primarily due to issue authors not responding to our questions for clarity. This proposes a timeline we can all follow to know when it's a good time to close the
issue on our end.
Some of the documentation I acquired from [bootstrap's CONTRIBUTING.md](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md). I really like a lot of what they have in there and if I get more time in the future I may borrow more of what they have.
> Add documentation on support and issues

- tools/build-cli.js
- tools/exec.js
the part of #819
then('return result') is extraneous.
catch() is extraneous. (there is downstream catch)
removeing it prevents duplicate printing of errors.
> Simplify tools/exec

- src/OverlayTrigger.js
Switched to using onMouseEnter and onMouseLeave so that the overlay doesn't redraw every time you cross borders of children elements contained within the trigger.
> fixed flickering when moving between trigger element and children of trigger element in hover mode

- src/DropdownButton.js
- src/Interpolate.js
- src/Modal.js
- src/ModalTrigger.js
- src/OverlayTrigger.js
- src/PanelGroup.js
- src/ProgressBar.js
- src/SplitButton.js
- src/Thumbnail.js
The Future :sparkle:  Yey :raised_hands: :smile: 
Thanks to these
https://github.com/yannickcr/eslint-plugin-react/pull/124
https://github.com/yannickcr/eslint-plugin-react/pull/127
@Cellule additions into `eslint-plugin-react` (yet to be released in v2.5.3)
It became possible to detect these additional `prop types` warnings.
> Add missed prop types validations.

- CONTRIBUTING.md
- README.md
- docs/src/NavMain.js
- docs/src/Root.js
- docs/src/Routes.js
- docs/src/SupportPage.js
Hi again @mtscout6 @mathieumg @AlexKVal and team —
I added a support page to the docs and links to Thinkful in `README` and `CONTRIBUTING` to close #783. Let me know what you think!
Also, in line with feedback from @mtscout6 [here](https://github.com/react-bootstrap/react-bootstrap/issues/783#issuecomment-108999315) and a few other folks — Thinkful will be formalizing our Code of Conduct when we roll out a broader update to Thinkful in the next couple of months (although so far we haven't run into any issues in the sessions). Stay tuned!
> Add community resources and support page to docs

- CONTRIBUTING.md
- docs/assets/style.css
- docs/build.js
- docs/generate-metadata.js
- docs/server.js
- docs/src/ComponentsPage.js
- docs/src/PropTable.js
- docs/src/Root.js
- package.json
- src/BootstrapMixin.js
- src/ButtonGroup.js
- tools/promisify.js
This is a first pass at getting some of the doc info generated. Not having prop lists in our docs was really getting to me. So this is an attempt at a "good enough for now" solution that we can build on. 
you can see that a bunch of info is still missing from the doc info, mostly because there are no doc comments on any Props, but also b/c some stuff isn't statically analyzable. For those cases we can use the jsDoc "doclets" (like @private) to tell the generator how to display the info.
This isn't meant to be a complete solution, but one that is better than what we currently have. I am hoping that others will help start documenting our props as we go.
It should also be said that I am not sure this is working with the doc build command. It does work with the dev server version though
> Generate Prop Documentation

- appveyor.yml
Otherwise the AppVeyor build fails in all PRs. See: https://github.com/npm/npm/releases/tag/v2.12.1
I thought it would have been "released" much quicker than that... We only have to revert this PR once it's released.
> Lock in npm at 2.11 until 2.12.1 is released

- src/Button.js
To document this property.
With this patch:
I've tried to re-use values from [src/ButtonInput.js#L20](https://github.com/AlexKVal/react-bootstrap/blob/8188f39086d5419838fe5a87671151e4111119a4/src/ButtonInput.js#L20)
like this:
```js
import ButtonInput from './ButtonInput';
...
ButtonInput.propTypes = {
type: React.PropTypes.oneOf(ButtonInput.types),
```
but it doesn't document them
Closes #925
> Add missed propType validation for Button 'type' property

- src/Position.js
- test/PositionSpec.js
I missed `[fixed]` for commit at https://github.com/react-bootstrap/react-bootstrap/pull/945 to reflect that fix in `Changelog`
The first commit is a stub exactly for this.
The second one is a basement for `PositionSpec` with ToDo in it.
> Fix commit history for Changelog and add first tests for Position

- package.json
With 
`css-loader@0.15.2`
`webpack@1.10.1`
all works fine again.
Closes https://github.com/react-bootstrap/react-bootstrap/issues/861
> @mathieumg ...probably broke Glyphicon as well.
It looks like glyphs are ok.
`npm run docs`
> Update css-loader dev dependency.

- docs/assets/style.css
- docs/src/Anchor.js
- docs/src/ComponentsPage.js
It feels not quite right that we are not able to give a user a link to exact example / paragraph on the Components page.
Headers are made linkable for UX.
Not principal changes:
Unified formatting for all components.
Fixed several id-s.
It was tedious :sweat_drops: :sweat_smile:
> Add anchors to every component / example on Components page

- src/Col.js
- src/Grid.js
- src/Row.js
Closes https://github.com/react-bootstrap/react-bootstrap/issues/387
This looks like:
and Col:
> Document Grid, Row and Col properties

- src/Input.js
the new version of `eslint-plugin-react@2.7.0` released recently
is able to recognize such patterns as addressed by this patch.
> Add missed 'type' property validator for 'Input'

- docs/examples/ProgressBarStacked.js
- src/ProgressBar.js
- test/ProgressBarSpec.js
Fixes https://github.com/react-bootstrap/react-bootstrap/issues/968
My "cool" and very "animated" screenshot :smile: 
Need one more approval from a member of @react-bootstrap/collaborators
> 'stacked' progress bar renders correctrly 'active' and 'striped' children

- docs/examples/.eslintrc
- docs/examples/Collapse.js
- docs/examples/Fade.js
- docs/src/ComponentsPage.js
- docs/src/ReactPlayground.js
- docs/src/Samples.js
- src/Collapse.js
- src/CollapsibleMixin.js
- src/CollapsibleNav.js
- src/Fade.js
- src/FadeMixin.js
- src/Input.js
- src/Modal.js
- src/Nav.js
- src/Overlay.js
- src/Panel.js
- src/Popover.js
- src/Position.js
- src/Tooltip.js
- src/Transition.js
- src/index.js
- test/CollapseSpec.js
- test/CollapsibleMixinSpec.js
- test/FadeMixinSpec.js
- test/FadeSpec.js
- test/ModalSpec.js
- test/PopoverSpec.js
- test/TooltipSpec.js
- test/TransitionSpec.js
- test/helpers.js
__EDIT__: Should be good to go now!
An experiment in mixin alternatives for transitions. I was already working on a generic version for a project at work and thought it might be valuable upstream here.
`Transition` component is sort of like a streamlined CSSTransitionGroup from react.addons, but expects a single child and doesn't depend on components mounting/unmounting.
If it looks like the sort of thing we might like in core here I'll clean it up and add tests. Feedback appreciated, I added examples to the Component page for easy viewing :P.
Benefits in my eyes:
- Fade doesn't need to clone its element anymore, and we have proper callbacks
- Collapse feels a bit more manageable in component form, rather than having to mixin the behavior
- Transition is nice and extensible for its …
> Transitions Components

- src/Panel.js
http://www.w3.org/TR/wai-aria/states_and_properties#aria-expanded
It is not necessary to set them explicitly to strings.
Here [src/Collapse.js#L51](https://github.com/react-bootstrap/react-bootstrap/blob/c3b41af621e9b4d4fbdc8a095b2d666420735534/src/Collapse.js#L51)
we already do it like this:
`aria-expanded={this.props.in}`
Tests are asserting this
[test/PanelSpec.js#L196](https://github.com/react-bootstrap/react-bootstrap/blob/ccc50e01917ba75e5a983ba068c1db4b790bb85d/test/PanelSpec.js#L196)
[test/PanelSpec.js#L206](https://github.com/react-bootstrap/react-bootstrap/blob/ccc50e01917ba75e5a983ba068c1db4b790bb85d/test/PanelSpec.js#L206)
> Simplify 'aria-expanded' values for 'Panel'

- docs/src/ComponentsPage.js
> Remove 'Collapsible Mixin' example from docs.

- .gitignore
- tools/amd/build.js
- tools/release-scripts/changelog.js
Remove empty 'amd/lib' creation
Remove extraneous copying of 'LICENSE' for bower in building step
(release tool is doing it)
Simplify path to 'changelog' script
> Small fixes for 'tools'

- package.json
This fixes the build issues. See https://github.com/facebook/react/pull/4449.
> Lock Babel to old version due to linting issues

- src/Collapse.js
- src/Fade.js
- src/Overlay.js
- src/Position.js
- src/Transition.js
- test/PositionSpec.js
- test/TransitionSpec.js
Fixes #1018
This restores the old behavior where we only calculate position initially (and when the target changes).
I also ended up modifying the `Transition` implementation a bit to make the state tracking a bit more explicit.
> [fixed] Only calculate overlay position on display

- package.json
It has been fixed.
https://github.com/facebook/react/pull/4449#issuecomment-123484276
`[changed]` tag in the commit is because 'babel' affects output code.
> Unfix 'babel' back.

- .eslintrc
Revert of https://github.com/react-bootstrap/react-bootstrap/pull/992 is not possible
> Enable back 'space-infix-ops' eslint rule

- src/OverlayTrigger.js
I came accross some weird React component life cycle where didUpdate was called after willUnmount. Thus, mounting overlay when there is no mount point naturally raised an error.
> OverlayTrigger: mount overlay if mount point is defined

- src/Overlay.js
- src/Position.js
- test/OverlayTriggerSpec.js
> [fixed] overlay classNames are maintained by overlayTrigget

- package.json
- src/.eslintrc
Because of that 
```js
import pick from 'lodash/object/pick';
```
https://github.com/react-bootstrap/react-bootstrap/pull/1048/files#diff-0d27b0102f68505cf339e89dfe5c6893R8
--
Readme https://github.com/eslint-plugins/eslint-plugin-lodash
> Add 'eslint-plugin-lodash' for 'src'

- src/Pagination.js
- src/PaginationButton.js
- test/OverlayTriggerSpec.js
- test/PaginationSpec.js
usage: `<Pagination ... WrapperElement={<Element/>}/>`
default behavior remains unchanged
use `this.props.children` in Element where you want the numbers to be
Useful for people using react-router because you can wrap the buttons in Link.
note: Bootstrap css targets `.pagination > li > a`
> [added] WrapperElement for Pagination buttons

- src/BootstrapMixin.js
- src/styleMaps.js
- test/BootstrapMixinSpec.js
First part of https://github.com/react-bootstrap/react-bootstrap/issues/988
Solves https://github.com/react-bootstrap/react-bootstrap/issues/537#issue-69286225
partially https://github.com/react-bootstrap/react-bootstrap/issues/543#issue-69510135
and https://github.com/react-bootstrap/react-bootstrap/issues/306#issuecomment-71010320
Added document section looks like this:
> Custom styles with no validation

- src/index.js
- src/utils/index.js
I have to change `src/index.js` because otherwise it warns about deprecation
even when users don't import 'utils/CustomPropTypes'.
But if users import `CustomPropTypes` as
```js
import CustomPropTypes from 'react-bootstrap/lib/utils/CustomPropTypes'
```
there is no warning.
And the deprecation warning cannot be added straight to `utils/CustomPropTypes.js`
because in this case there are a lot of deprecations in console.
--
First part of #937
> Deprecate 'utils/CustomPropTypes' exporting in v0.25

- test/RowSpec.js
coverage: before
coverage: after
> Add missing tests for 'Row'

- src/TabbedArea.js
- test/TabbedAreaSpec.js
Bug is confirmed:
With `animation={false}` all is OK
With `animation={true}` `active` property did not set
--
I've made tests reproducing this bug:
--
Fixes #287 and #557
> Tabbed area. Fix for animated panes rendering.

- src/Modal.js
- test/ModalSpec.js
Fix for #1078
The component must clean up after itself when it was unmounted
> Modal: added finalisation for the component when it was unbound from the tree

- src/Modal.js
- test/ModalSpec.js
pulled out from #1040, needs some additional bike shedding 
cc @mfunkie
> [added] Allow custom Modal dialog components

- src/Modal.js
Not sure where this fell to the floor, but clearly we have no tests around it (will get to that)
> [fixed] regression when clicking "static" modal backdrops

- src/Carousel.js
Using carousel in a modal can sometimes lead to the modal being closed and carousel being unmounted before `setState` is called, causing the `Warning: setState(...): Can only update a mounted or mounting component...` message.
> [fixed] Carousel checks if it is mounted before setting state

- src/Collapse.js
- src/Panel.js
- test/CollapseSpec.js
- test/PanelSpec.js
Also remove redundant aria-expanded from Panel collapsible body
We decided to close #1087 because it didn't really make sense to add a specific role for a generic component.
Removing aria-expanded from components that don't have roles doesn't change the functionality of JAWS or VoiceOver, so we decided that it may be better for the consumer to specify the role of the content.
The Pivotal UI Team
@atomanyih @ctaymor @gpleiss @kennyw12 @matt-royal @nicw @stubbornella
> [fixed] only add aria-expanded to Collapse when an ARIA role is present

- src/Modal.js
- test/ModalSpec.js
Somewhere along the way in 0.24 Modal lost the ability to use a provided className.
In other words, you can now do this again:
```
<Modal className="my-modal-class" ... />
```
I had some code do this and figured it was useful enough to re-add.
> [fixed] Modal uses provided className again

- docs/src/GettingStartedPage.js
Forgot to remove this when we removed factory support.
> Remove reference to factories from documentation

- src/Glyphicon.js
- src/InputBase.js
- test/GlyphiconSpec.js
- test/InputSpec.js
Reference: #502
- Added a new prop on Input named feedbackIcon
- Added tests for ensuring Glyphicons as default
- Added tests for rendering the feedbackIcon
This allows for passing custom icons that may be used instead of the default Glyphicons when an Input is having feedback.
> [added] Custom feedback icon for Input

- docs/src/GettingStartedPage.js
Closes #1115
It looks like (and uses `Anchor` now)
> Clarify ES6 imports

- src/Glyphicon.js
per: https://github.com/react-bootstrap/react-bootstrap/pull/1122#issuecomment-129731182
Something like that ?
> Clarify 'Glyphicon' 'glyph' property

- docs/src/ComponentsPage.js
1. The "extends tabbed navigation" bit was just copied from upstream for no particular reason - it doesn't make any sense here since it's not visible to the user at all
2. As far as I can tell we don't actually support dropdowns here, or I don't see how to use them anyway and it's not in the examples
3. The upstream affix sidebar just says "Tab" (while using the full "Togglable tabs" as the section title), so we may as well be consistent-ish and make the section easier to find
> Clean up tabs documentation a little bit

- src/Tabs.js
- test/TabsSpec.js
Add role="tablist" to the nav inside of tabs. Also backfill a test for adding aria-selected to the nav item for the currently active tab.
The Pivotal UI Team
@atomanyih @ctaymor @d-reinhold @kennyw12 @matt-royal @nicw @stubbornella
> Improve tabs accessibility

- src/Panel.js
Part of #976
Simplify 'expanded' state code. Make it similar way to 'NavBar'.
The API behaviour has not changed.
`expanded` property has no default boolean value because of the same as https://github.com/react-bootstrap/react-bootstrap/issues/976#issuecomment-131048858
```js
isExpanded(){
return this.props.expanded != null ? this.props.expanded : this.state.expanded;
},
```
> Explicitly set default value for `defaultExpanded` property.

- src/Tab.js
for the sake of clarity in documentation.
The part of #976
> Explicitly set default values for boolean properties

- src/Tabs.js
With https://github.com/react-bootstrap/react-bootstrap/pull/1017 I've introduced a new subtle bug
with animation:
This is the fix for it against `v0.25-rc` and new `Tabs` component.
I am sorry :sweat:
> Fix wrong tabs switching animation for 'Tabs' component

- src/TabbedArea.js
With https://github.com/react-bootstrap/react-bootstrap/pull/1017 I've introduced a new subtle bug
with animation:
This is the fix for it.
I am sorry :sweat:
> Fix wrong tabs switching animation for 'TabbedArea' component

- docs/examples/ListGroupLinked.js
- package.json
- src/ListGroupItem.js
- tools/buildBabel.js
- tools/generateFactories.js
This is the last version working as `eslint@0.24` defaults
Fixes this https://github.com/react-bootstrap/react-bootstrap/pull/1184#issuecomment-132470865
--
There are first signs that `eslint-config-defaults` `defaults` are not working for us.
This two wasn't catched by `eslint-config-defaults@^4.0.1` version,
but `3.1.0` does:
--
I propose https://github.com/react-bootstrap/react-bootstrap/pull/1176
> Stick to eslint-config-defaults@3.1.0 version

- .eslintrc
- package.json
- src/Pagination.js
just compare with https://github.com/react-bootstrap/react-bootstrap/pull/1176 
11 vs 22 exclusions :smile: 
It seems `semistandard` is way less stricter and suits more for `R-B`.
> Impose airbnb linting with exceptions

- src/utils/CustomPropTypes.js
- test/utils/CustomPropTypesSpec.js
```js
propTypes: {
collapsable: deprecated(React.PropTypes.bool, 'Use "collapsible" instead.')
```
Beginning: https://github.com/react-bootstrap/react-bootstrap/pull/1184#issuecomment-132801266
> Add 'deprecated' wrapper for property deprecation warning

- docs/generate-metadata.js
- src/Button.js
I just answered a [Stack Overflow question related to the default `type` of a `<Button>`](http://stackoverflow.com/questions/32074972/reactjs-onsubmit-on-form-doesnt-work) and noticed the default value wasn't documented (since it's assigned in a render method as it doesn't always apply).
This PR adds support for a new `@defaultValue` doclet and uses it to document the default for when `type` applies.
Should this also be mentioned as a prose section in the docs? Defaulting to `'button'` is IMO a nicer default than `'submit'`, but the difference in default behaviour compared to a regular HTML `<button>` is a potential gotcha.
> Document Button's default type attribute

- docs/dev-run
- nodemon.json
Why do we need to monitor `node_modules` in the first place ?
--
It will allow to get rid of
and make less load to CPU
> Monitor less files by 'nodemon' with 'npm run docs' script

- .eslintrc
- src/Dropdown.js
- src/MenuItem.js
- src/Modal.js
- src/NavDropdown.js
- src/SplitButton.js
- src/Tabs.js
- src/Tooltip.js
`bsStyle` property is removed from `NavDropdown` component because it doesn't used anywhere downstream.
Remove these warnings:
--
As promised: https://github.com/react-bootstrap/react-bootstrap/issues/646#issuecomment-122575417
> Fix eslint warnings

- .eslintrc
https://github.com/react-bootstrap/react-bootstrap/pull/1186#issuecomment-133755557
I believe that it is just a subtle bug (https://github.com/airbnb/javascript/issues/454).
Sure we could impose additional set of rules e.g. `eslint:recommended`
or just fix it locally by adding `"no-undef", 2` rule into our `.eslintrc`.
> Fix for airbnb bug about 'no-undef' rule.

- src/Panel.js
- src/PanelGroup.js
- test/PanelGroupSpec.js
Adds accessibility, following the guideline specified [here](http://www.w3.org/WAI/PF/aria-practices/#tablist).
The Pivotal UI Team
@atomanyih @ctaymor @d-reinhold @kennyw12 @matt-royal @nicw @stubbornella
> [added] accessibility props for PanelGroup and Panels.

- src/Tab.js
fixes #1238 
It effectively removes the ability to add a title to tab panes, but I don't think that is going to to be an issue...
It is a bit odd that that props doesn't do anything unless inside a `tabs` component, but nothing too weird
> [fixed] title is not passed to tab pane DOM node

- package.json
is there any good reason not to just always pin deps like this to patch versions? That we have to spend any bandwidth on these sorts of breakages is annoying. We rarely need new eslint features, but deal with breakages due to upgrades fairly often it seems
> pin eslint version because of bug in 1.3.0

- docs/src/ComponentsPage.js
- src/Alert.js
- test/AlertSpec.js
Before this change, the dismiss button was focusable in VoiceOver, but not in JAWS. This also moves the position of the SR-accessible dismiss button to the end of the alert.
> [fixed] screen-reader accessible dismiss button on alerts

- src/Dropdown.js
Reworks the focus management so focus is properly returned to the toggle when an item is selected from the list. This partially address #1220 fixing the `focus` trigger case. it doesn't address the hover case though.
need to clean up the commits here...
> [fixed] focus returns to the toggle by default onClose

- docs/src/HomePage.js
https://github.com/react-bootstrap/react-bootstrap/pull/1261#issuecomment-137342050
It looks like:
> Announce about 'React-0.14' branch and 'react-pre' tag.

- src/DropdownMenu.js
- test/DropdownSpec.js
When dropdown without focusable items (e.g. containing only divs to display some content) is opened, exception is raised in `DropdownMenu.focusNext()` method as `items[0]` is not defined.
This commit adds additional check in `focusNext()` method, skipping focusing altogether if there are no focusable items.
> [fixed] Error on opening dropdown without focusable items

- src/utils/childrenValueInputValidation.js
- test/ButtonInputSpec.js
- test/FormControlsSpec.js
Remove PropTypes.number and PropTypes.string in favor of PropTypes.node.
This allows for a number, string, element, or an array of those to pass validation per #1023. Also fixes the ButtonInputSpec test and adds one to FromControlsSpec.
> [changed] allow PropTypes.node in valueValidation

- src/Tabs.js
- test/TabsSpec.js
Fixes #1276 
I think this is okay to PR against `master` because, while the emitted markup does change, the net padding applied when using standard markup does not, and the new behavior is more correct/desirable semantically.
> [fixed] Don't render Grid or Row with Tabs

- src/ListGroup.js
ListGroup shouldRenderDiv check is not using ValidComponentChildren, causing errors if the child is a falsey value.
> ListGroup shouldRenderDiv issue

- src/Tooltip.js
`BootstrapMixin` didn't do anything here, except for adding misleading entries in the props table. The `title` prop doesn't do anything, either.
> Remove extraneous Tooltip prop types

- src/NavItem.js
- src/Tabs.js
- src/utils/ValidComponentChildren.js
- test/NavItemSpec.js
- test/TabsSpec.js
http://www.w3.org/TR/wai-aria-practices/#tabpanel
Only the active tab is focus-able, and rather then hitting tab to change the active tab you use the arrow keys. 
I didn't do the ctrl page up stuff b/c that sounds bit more undecided from reading through. It also seems like it would conflict with anything inside the panel that used that key combo...
> [changed] tab keyboard navigation to be more inline with ARIA spec

- docs/build.js
- docs/client.js
- docs/server.js
- docs/src/Routes.js
- package.json
- test/ModalSpec.js
- test/PanelGroupSpec.js
Going to cut `react-bootstrap@0.25.102-react-pre.0` after this.
> Update for React 0.14.0-rc1 and React Router 1.0.0-rc1

- .eslintrc
- package.json
they have fixed those bugs.
And disable new "eqeqeq" rule. `Require === and !== (eqeqeq)`
http://eslint.org/docs/rules/eqeqeq
> Update eslint dev.dependency

- MAINTAINING.md
- package.json
Now release script runs in "dry run" mode by default.
It prevents `danger` steps (`git push`, `npm publish` etc) from accidental running.
Addresses https://github.com/react-bootstrap/react-bootstrap/pull/1325#issuecomment-140853722
https://github.com/AlexKVal/release-script/pull/19
:cherries:
> Update 'release-script' to 'human safe' version.

- src/ListGroupItem.js
They don't do anything, and they're not used for anything.
> Removed unused props from ListGroupItem

- docs/examples/ImageResponsive.js
- docs/examples/ImageShape.js
- docs/src/ComponentsPage.js
- docs/src/ReactPlayground.js
- docs/src/Samples.js
- src/Image.js
- test/ImageSpec.js
Create an images component as refer to http://getbootstrap.com/css/#images including samples and docs.
> [added] Images Component with Sample and Docs

- docs/src/GettingStartedPage.js
PR addressing the small discussion in issue https://github.com/react-bootstrap/react-bootstrap/issues/1338 and https://github.com/react-bootstrap/react-bootstrap/issues/1339
Proposal for being more specific about the current (and future) support for IE8.
I've split the changes into 2 commits, one addressing IE8 support and one addressing JQuery since I assumed (correct if I'm wrong) that there is no more plan to drop JQuery dependency for IE8
> IE8 docs update to reflect the current status

- docs/src/PropTable.js
- package.json
- src/Dropdown.js
- src/DropdownButton.js
- src/OverlayTrigger.js
`lodash` needs to be customised in order to be IE8 compatible.
Luckily, the owner is providing a package already customised for that purpose, and that package is `lodash-compat` and this is what this PR is about.
I've replaced every call to `lodash` **in the source code** to `lodash-compat`, while leaving the development part untouched (src, tooling, webpack cfg).
What do you think?
> [changed] use `lodash-compat` in src/ for IE8 compatibility

- src/Input.js
https://reactiflux.slack.com/archives/react-bootstrap/p1443209265000177
> Fix deprecation warning message for 'Input type=static' component

- docs/examples/ListGroupCustom.js
- docs/src/ComponentsPage.js
- docs/src/Samples.js
- src/ListGroup.js
- test/ListGroupSpec.js
As discussed, this keeps the handling for the case where all children are `<ListGroupItem>`, but now users can specify the element `<ListGroup>` should output via the componentClass prop, which defaults to a div.
> [added] #1181 ListGroup supports componentClass prop

- src/Tab.js
- src/Tabs.js
- test/TabsSpec.js
Tabs currently allows setting of the pane className through the className prop. This adds a tabClassName prop which gets merged into the corresponding NavItem's className.
I am unsure how to write this up for the docs. Any hints?
> [added] #1320 allow NavItem class to be set

- src/Dropdown.js
- test/DropdownSpec.js
By default, only focus the first dropdown menu item after keydown.
Fixes #1233.
> [fixed] Dropdown focus behavior on click

- src/Dropdown.js
- test/DropdownSpec.js
Actually fixes #1233.
I think this is a little cleaner - http://www.w3.org/TR/wai-aria-practices/#menubutton specifies explicitly to not change focus on space or enter, which I will interpret as also covering mouse clicks.
> Use role to determine dropdown open focus behavior

- package.json
Fixes this and similar errors bundling 0.26:
```
ERROR in ./~/react-bootstrap/lib/Col.js
Module not found: Error: Cannot resolve module 'react-prop-types/lib/elementType'
@ ./~/react-bootstrap/lib/Col.js 23:36-79
```
> Add missing react-prop-types dependency

- package.json
This release is not really compatible with React 0.14.
Fixes #1392 and #1393 (I guess? There's nothing wrong per se with what we have in `package.json` ¯\\\_(ツ)_/¯ , but we're not really compatible with React 0.14 on this release anyway).
> Use caret range for React dependency

- src/NavItem.js
This ignores the `disabled` prop on the `NavItem` BTW... seemed more consistent since e.g. `onClick` on `Button` does the same.
> [fixed] Put onClick on correct element on NavItem

- test/index.js
Logging was previously messed up because this function tried to use `this.currentTest`.
> Fix logging from afterEach hook in tests

- src/Button.js
- src/ButtonInput.js
Hi,
This is an attempt to fix #1428 which is where I'm having trouble using `ButtonInput` in a server side React render. I believe this is due to cross imports between `ButtonInput` and `Button` which might not be an issue when using a client bundle?
The details are in the commit message.
There might be a better way to solve the issue but I hope this helps if it is the preferred route.
Cheers,
Michael
> Remove cross import between Button & ButtonInput

- src/ModalHeader.js
If we have a form in the modal, it triggers the onClick..
> Add missing type="button" in modal header

- docs/src/ComponentsPage.js
It makes a huge difference when you have inline elements.
Compare the following two animations (sorry for poor quality).
The first is with the contents wrapped in a `<div>`;
the second has the contents not wrapped in a `<div>`.
There is no relevant lag;
the stuttering happens because the `Collapse`
can't get smaller than the line height of the alert.
The example already does this, but it's far from obvious
(to ~~a newcomer~~ me, at least!)
that that's what fixes this particular issue.
> Suggest wrapping `Collapse` contents in a `div`

- src/Collapse.js
- src/Fade.js
- src/Nav.js
- test/NavSpec.js
- test/NavbarSpec.js
The API between Nav and Navbar is a mess...
I am a bit worried that this change will break a lot of styles for folks, but that extra element seemed inane. Perhaps it was an attempt at better a11y? at least in a navbar though its unnecessary since its already in a wrapping `<nav>`... in any case I think adding a nav element should be up to the user
> [changed] remove extra wrapping `<nav>` element in Nav components

- src/Modal.js
lodash-compat is what's listed under package.json. This matches how `pick` is imported from other source files in react-bootstrap too.
> Require lodash-compat instead of lodash from Modal.js

- src/Alert.js
The version of the Alert close button that is supposed to be hidden from screen readers has `aria-hidden="true"`, as expected, but did not have `tab-index="-1"` so it may not be skipped when tabbing through the interface
> a11y: fixing the tab-index for the non-screenreader version of the Alert dismiss button

- src/Breadcrumb.js
- src/BreadcrumbItem.js
- test/BreadcrumbItemSpec.js
Makes it easier to use with react-router-bootstrap
Fixes #1569
> Just ignore href on active BreadcrumbItem

- src/Modal.js
Currently these props are not documented. This is causing confusion. See this SO thread for reference: http://stackoverflow.com/questions/31836812/trigger-modal-shown-for-react-bootstrap/34901027#34901027
> Add Modal propTypes for transition callbacks so it will be documented.

- src/SplitButton.js
- test/SplitButtonSpec.js
Fixes https://github.com/react-bootstrap/react-bootstrap/issues/1284
> [fixed] Allow overriding aria-label on <SplitButton> toggle

- docs/src/sections/MenuItemSection.js
- src/MenuItem.js
I just started using `react-bootstrap` and have really liked it so far. I stumbled for a little while over a mistake in the documentation, so I thought I'd take a stab at fixing it.
The section for `MenuItem` lists the wrong arguments for the `onSelect` callback (#1657). While fixing this issue, I also added blurbs for `MenuItem`'s props. Hope this is helpful.
> Correct and improve MenuItem docs

- src/Panel.js
- test/PanelSpec.js
This should fix #1540 
I found a number of different strategies for passing props to children in the codebase. Here I tried to minimize duplication of proptype definitions and their documentation.
For some reason the docs fail to build with a `TypeError: Converting circular structure to JSON` and this seems to be due to how I extended the proptypes. I don't yet understand why, any hints are appreciated.
> [added] Collapsible Panel transition hooks

- docs/src/IntroductionPage.js
On the introduction page in the first line, Reusable is misspelled as Reuseable. This is my first PR :smile:
> Spelling error. Reuseable => Reusable.

- src/MenuItem.js
- test/MenuItemSpec.js
<MenuItem divider className="foo" />
rendered:
<li role="separator" class="divider" />
now renders:
<li role="separator" class="divider foo" />
> [fixed] #1660 MenuItem divider className

- docs/src/ComponentsPage.js
Fix for minor bug on ComponentsPage with the ScrollSpy.  It was unable to set the last section/Anchor as active.
1. Navigate to: [Components Page](http://react-bootstrap.github.io/components.html)
1. Resize browser so that the **ScrollSpy** section should be marked as active in the side nav.
**ScrollSpy** section to be active.
**Affix** section is active.
The `setActiveNavItem` function loops through the sections until it finds the first `afterSection` that is false.  In the case where all sections are true it did nothing.  This change breaks out of the for loop if/when a false value is encountered and then sets the state of the `activeNavItemHref`.
> Fix ComponentsPage ScrollSpy - last section active

- src/Panel.js
- src/PanelGroup.js
- test/PanelGroupSpec.js
- test/PanelSpec.js
Pass event to PanelGroup onSelect handler and cancel expanding if the custom handler returns false
This changes the public API for the onSelect handler from `function handleSelect(eventKey)` to `function handleSelect(eventKey, event)`.
Because the onSelect handler receives the DOM event, it can check what the target element was. Combined with the new behavior when "false" is returned from the handler, clicks on specific elements can be ignored, e.g. a button with onClick logic is included in the panel and clicking it should not toggle the panel.
> [changed] Make Panel expansion cancelable

- .travis.yml
- CONTRIBUTING.md
- MAINTAINING.md
This mostly removes cruft. It'll also be easier to keep around a `next` branch than to keep rolling rc branches.
> Update contributing and maintaining guidelines

- src/Modal.js
- test/ModalSpec.js
This makes it consistent with our use of componentClass elsewhere.
> dialogComponent -> dialogComponentClass on <Modal>

- docs/examples/ProgressBarScreenreaderLabel.js
- docs/examples/ProgressBarWithLabel.js
- docs/src/sections/ProgressBarSection.js
- src/Interpolate.js
- src/ProgressBar.js
- test/ProgressBarSpec.js
This is a silly feature and we shouldn't have it.
> Deprecate interpolation in <ProgressBar label>

- test/ButtonInputSpec.js
- test/DropdownSpec.js
- test/NavbarSpec.js
- test/index.js
- test/utils/bootstrapUtilsSpec.js
I thought this was more explicit but actually it's just dumb.
> Don't require duplicate shouldWarn declarations

- docs/examples/.eslintrc
- docs/examples/CustomButtonStyle.js
- docs/src/ComponentsPage.js
- docs/src/ReactPlayground.js
- docs/src/Samples.js
- docs/src/sections/CustomStylesSection.js
Documentation per request in #1721 
* The `require` statement in `ReactPlayground.js` for `bootstrapUtils` needed `.default`; that area of JavaScript is still unfamiliar to me- advice on a better approach is welcome.
* I am not providing an import hint for `bootstrapUtils` per #1728 comment by @taion. I suspect this will be difficult for new users to figure out since the location of bootstrapUtils looks to require a path (e.g. ```import bootstrapUtils from 'react-bootstrap/lib/utils/bootstrapUtils';```). Feedback/suggestions welcome.
> bsStyle custom style documentation

- src/DropdownToggle.js
Change `type="button"` to `role="button"` for DropdownToggle
> Fixes https://github.com/react-bootstrap/react-bootstrap/issues/1830

- docs/examples/DropdownButtonCustomMenu.js
- docs/examples/PopoverContained.js
Two places that slipped through the change to `ReactDOM.findDOMNode`.
> Fix documentation usage of React.findDOMNode

- src/TabContent.js
- src/TabPane.js
- src/Tabs.js
- test/TabsSpec.js
Resolves #129 
I didn't add tests for this as there weren't any existing ones for `animate` or any of the new transition ones that I could reference.
> Added unmountOnExit support to Tabs

- src/Panel.js
So this fixes the issue, but I am not sure how to test it.
If I run ```npm test``` I don't see the react error show up in the console, and I am not sure why.
Suggestions on how to test the warning doesn't happen are welcome.
> Fix issue #1829.

- src/PaginationButton.js
- test/PaginationSpec.js
Makes it possible to provide an anchor renderer component that makes use of page number information.
Ideally `eventKey` should be renamed to something that makes more sense like `targetPage` to keep it pagination-centric.
https://github.com/react-bootstrap/react-bootstrap/issues/1866
> allow anchor renderer access to target page number #1866

- src/Dropdown.js
- src/DropdownToggle.js
- test/DropdownToggleSpec.js
> Issue 2013

- src/NavDropdown.js
- test/NavDropdownSpec.js
This commit adds the 'active' prop to the NavDropdown component, which
when true adds the 'active' class to the component.
Note that this does not automatically fix https://github.com/react-bootstrap/react-router-bootstrap/issues/167, because the `LinkContainer` does not wrap the entire NavDropdown, but only the individual items. 
Personally I fixed this by using a wrapper component wrapping the NavDropdown which checks in the render() if the path of any of its children currently is active (the same check the LinkContainer performs) like so:
```js
isAnyChildActive() {
let anyChildActive = false;
React.Children.forEach(this.props.menuItems, (child) => {
if (!anyChildActive)
anyChildActive = this.context.router.isActive(child.props.path, false);
});
return anyChildActive;
}
```
(in the …
> Add 'active' prop to NavDropdown component

- src/Panel.js
in #2133 only add 'expanded' argument in the end, but you don't add 'id'
argument. that lead to the argument not matching
> Fixes #2132

- src/OverlayTrigger.js
Noticed this error while inspecting the code (:
> OverlayTrigger: Remove extra comma in createChainedFunction call

- package.json
Noticed that VersionEye was reporting a security issue with marked v0.3.5 when I opened a PR for another bug.
[VersionEye report](https://www.versioneye.com/pullrequests/57c9053112b5260012202580)
Seems like there was a significant security bug in that version, so it's worth upgrading to 0.3.6 for the fix.
> Fix dependency security issue / Upgrade 'marked' -> v0.3.6

- src/Pagination.js
Fixes https://github.com/react-bootstrap/react-bootstrap/issues/2159.
There's an off-by-1 bug in both `startPage` & `hasHiddenPagesAfter` calculations which cause the Pagination component to incorrectly place ellipses & group numbers excluding the first & last numbers.
This error occurs such that the first two numbers [1] ... [2] or the last two [19] ... [20] display with an ellipsis between them, when they should be connected ([1][2] & [19][20]).
It's caused by the `startPage` calculation mistakenly excluding the page `1` away from the active buttongroup when it should be included.
The same goes for `hasHiddenPagesAfter` mistakenly becoming `true` and excluding the last page button away from the button group, causing an ellipsis between the last page button & the group.
**Broken first …
> Fix Pagination ellipsis placement bug

- README.md
The npm script "test-watch" was replaced by "tdd" in #2027.
The README.md is now updated accordingly.
> replace reference to watch-test npm script by tdd in README. fixes #2216

- src/Collapse.js
Fixes #1841
Trigger browser reflow before the start of the collapse animation ( in onExit callback instead of onExiting)
> #1841 trigger browser reflow before starting the collapse animation

- package.json
- glob is used in https://github.com/react-bootstrap/react-bootstrap/blob/2541d75cb30bbe21b283f8c3dd3fd7da4f51a88a/docs/generate-metadata.js
- fixes #2227
> Fix missing glob dev dependency

- src/Panel.js
- test/PanelSpec.js
Replaces #2269
Adds `collapsed` in panel anchor's className, to follow bootstrap examples.
`className` is set to null if there is no need to add `collapsed`
> Fixes #2209 by adding collapsed in anchor className

- src/Carousel.js
- test/CarouselSpec.js
Replaces #2268
Creates 2 more properties on carousel: `prevLabel` and `nextLabel`, for screen readers.
> Adds prevLabel and nextLabel on carousel for screen readers

- src/Dropdown.js
- src/DropdownMenu.js
- test/DropdownSpec.js
This makes the prop added in https://github.com/react-bootstrap/react-overlays/pull/95 available to the dropdown component.
Please let me know if I've overlooked anything in the PR :)
> Expose event prop from RootCloseWrapper in Dropdown

- src/SafeAnchor.js
- test/PaginationSpec.js
This PR makes the default href of an anchor `#` instead of an empty string to make IE happy.
Discussion: https://github.com/react-bootstrap/react-bootstrap/issues/2065
> Changed default href in SafeAnchor to '#' to make IE happy

- src/Nav.js
- src/Navbar.js
- src/NavbarCollapse.js
- test/NavbarSpec.js
**Update 10/17:**
This PR has been improved from its original implementation. To see a running demo of the current iteration, you can run this Plunker here: https://plnkr.co/edit/43i4XA
The proposal has been simplified and improved with these two new props to the `<Navbar>` API:
> **onSelect: React.PropTypes.func**
> A callback fired when a `<NavItem>` grandchild is selected inside a child
> `<Nav>`. Should be used to execute complex toggling or other miscellaneous
> actions desired after selecting a `<NavItem>`. Does nothing if no `<Nav>`
> & `<NavItem>` children exist. The callback is called with an eventKey,
> which is a prop from the `<NavItem>`, and an event.
>
> ```js
> function (
> 	Any eventKey,
> 	SyntheticEvent event?
> )
> ```
>
> For basic toggling after all `<NavItem>` select …
> Feature: Add closeOnSelect & onSelect to Navbar API with tests & docs

- docs/examples/NavbarCollapsible.js
- docs/src/sections/NavbarSection.js
- src/Navbar.js
- test/NavbarSpec.js
I think this naming is a bit more consistent; the prop is `expanded`, not `open`.
Also, update the relevant docs section.
cc @kevinzwhuang
> Rename closeOnSelect to collapseOnSelect

- src/Overlay.js
Addresses #2206 
-----
This should display for `OverlayTrigger` too in the Docs, since it inherits from these props.
> Add placement PropType & default prop to Overlay for docs

- src/Panel.js
In the Panel Component implementation, there is a `shouldRenderFill` function which I think was meant to be used in the `renderBody` function, but was not use. For a cleaner code base, get rid of it or put it to use. I'm putting it to use because it's a good code abstraction as it enhances code readability.
> Refactor Panel to use shouldRenderFill in renderBody function

- src/FormControl.js
- test/FormControlSpec.js
This looks like what should be here.  I was unable to get the tests to run on master, or on my branch.  Here is a gist with the console output trying to run the tests.
https://gist.github.com/sorahn/a9a4f9d4d1fd0af24faa438336ca389d
Fixes #1887
> Add inputRef to FormControl component

- src/OverlayTrigger.js
- test/OverlayTriggerSpec.js
Having `aria-describedby` contain a DOM ID which is not present is invalid behavior, and creates an error in e.g. Google Accessibility Audit (see [Rule AX_ARIA_04](https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#ax_aria_04)).
This fixes #1827.
> Don’t set aria-describedby unless the referenced element is in the DOM

- src/FormControl.js
- test/FormControlSpec.js
This is a fix that I came up with for #1889 that allows FormControl to have a bsSize prop. I know the solution probably may not be the most scalable and elegant but since this seems to be a one off case I thought it might work here.
Let me know if you think this is an acceptable fix, if not, I'm willing to try to find an alternative solution.
> Add support for input-sm and input-lg in FormControl

- src/FormControl.js
I noticed that after my previous PR the sizes did not get added to the docs so I added the line that @jquense told me about.
> Add sizes to FormControl docs

- src/ModalHeader.js
- test/ModalHeaderSpec.js
Implements what was discussed in #2450 . Also added ModalHeaderSpec since it wasn't previously there and wrote a test to make sure the component renders with a closeButton prop now.
> Add support for Modal.Header closeButton without containing Modal component

- docs/examples/NavbarBasic.js
- Change the 4th MenuItem's eventKey from 3.3 to 3.4, thus making all keys unique
Resolves #2458
> Fix Navbar Basic Example eventKeys

- src/Glyphicon.js
It was not immediately obvious to remove the prefix since we specify using the icon name with a link to bootstrap which does use the prefix. It was only after looking at the sample and my written code that I noticed the difference.
While its nothing major I feel that this just adds a bit of clarity to the naming convention.
> Clarify naming expectation for glyph prop

- package.json
- src/Dropdown.js
- src/DropdownMenu.js
- test/DropdownMenuSpec.js
- test/DropdownSpec.js
This PR attempts to resolve #1490. The main things that I changed are:
1) Added a parameter (eventType) to onToggle so that every time onToggle is fired you know exactly what event fired it ('click' if from handleClick, 'keydown' if from handleKeyDown, 'close' if from onClose, 'select' if from onSelect).
2) Added a parameter (source) to handleClose which is the source function that fired the handleClose.
I tried it out locally in my own app and I was able to override the default closing of the dropdown by creating my own state that I called `dropdownOpen` that I passed in as the `open` prop to the Dropdown component. I created a `handleToggle` function that I pass in as the `onToggle` prop which only closes when `open` is `false` and the event that closed it is `close`. Here's what my …
> Add eventType to onToggle and source for handleClose

- package.json
- src/Modal.js
Allow to specify if last focus should be restored after hiding modal. Requires https://github.com/react-bootstrap/react-overlays/pull/145 to be merged.
> Modal: add restoreFocus option

- src/index.js
A very small change but I noticed `PaginationButton` is not exported in `index.js` and I am currently working on a variation of the core Pagination that works a bit differently, and having the standard PaginationButton available would be nice..  Atm I have to re-implement the `PaginationButton` markup
> Export PaginationButton to people can build their own paginations

- src/Nav.js
- test/NavSpec.js
As described in #2539, certain falsy values such as `0` should be acceptable. The truthy condition has been changed to check whether the value is `null` or `undefined` instead.
> #2539: change condition from truthy to not nully

- src/Carousel.js
Bootstrap's documentation for carousel says that `interval` should be set to `false` to prevent automatic cycling, but this is a failing prop in react-bootstrap. Clarifying that `interval={0}` should be used to prevent automatic cycling in react-bootstrap could be helpful.
> added description for carousel interval prop

- src/Thumbnail.js
- test/ThumbnailSpec.js
Addressing https://github.com/react-bootstrap/react-bootstrap/issues/2687
We want to be able to pass the onLoad and onError props from the parent Thumbnail prop to the child img tag. This pull request implements that functionality, as well as adding a few minimal descriptions for each prop in the thumbnail component
This is my first pr for this repo so I don't entirely understand the specific pr process for this repo. Please request changes if needed.
> #2687 Pass onError and onLoad props to its child image

- src/Modal.js
- test/ModalSpec.js
Similar to how <Modal/> allows `dialogClassName` to add class names on top of `modal`, it would be convenient to be able to add class names to the backdrop. Currently the only option is to modify the bsClass.
> Add backdropClassName to Modal props to allow extra class names on backdrop

- src/CloseButton.js
Why it is `import * as PropTypes` ?
`import PropTypes` is fine I think.
> Fix `import * as PropTypes` to `import PropTypes`

- src/SafeAnchor.js
- test/SafeAnchorSpec.js
~If `onKeyDown` prop is supplied, prefer that.~
If SafeAnchor renders an `a` tag, supply onKeyDown handler for "space" that calls the `onClick` handler.
Test that space bar calls click handler.
Addresses https://github.com/react-bootstrap/react-bootstrap/issues/2681
> SafeAnchor a11y - Provide keydown handler for "space"

- src/Carousel.js
- test/CarouselSpec.js
On Carousel update, if prop defaultActiveIndex is > than the number of new children, there will be no active item, and no way to select a new item.
Change is to reset the activeIndex=0 and previousActiveIndex to null (as suggested by @taion in #1914 )
Also added 2 tests to CarouselSpec and verified it fixes my app
> Fix for #1914

- package-lock.json
- package.json
With "newer" node versions (>= 11) you are not able to run `npm install` on react-bootstrap because of execSync became a native node extension and fails (https://github.com/mgutz/execSync/issues/36) with
`Attempting to compile native extensions.`
Upgrading codecov to 2.X.X solves the problem because they dropped dependency to execSync.
> Upgraded codecov because execSync subdependency fails to install

- src/Navbar.js
`navExpanded` was renamed to `expanded` in https://github.com/react-bootstrap/react-bootstrap/commit/f9ea411
> docs: update navbar documentation

- src/Modal.js
> make setModalRef a bound function so that it doesn't get called with null

- docs/src/sections/ModalSection.js
Summary:
------------
We're getting this warning:
`Warning: Accessing factories like React.DOM.code has been deprecated and will be removed in v16.0+. Use the react-dom-factories package instead.  Version 1.0 provides a drop-in replacement. For more info, see https://fb.me/react-dom-factories`
Changes Proposed:
--------------------
> Fix React.DOM.code deprecation warning: Remove deprecated use of React.DOM.code

- docs/src/sections/DropdownSection.js
- src/Dropdown.js
Summary
-----------
The documentation about `rootCloseEvent` for Dropdown does not indicate that it is not usable for `CustomDropdown`.
Changes proposed
-------------------
-------------------
Fixes #2891
> Add documentation note about rootCloseEvent being unavailable to custom dropdowns

- src/OverlayTrigger.js
The current fallback for `relatedTarget` in `handleMouseOverOut` is always `toElement`, but this is not correct for the `mouseover` event,which should use `fromElement` instead (see [the documentation for relatedTarget](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/relatedTarget)).
This bug causes the overlay to not be triggered when tested under chromedriver since `relatedTarget` can be null in some cases.
> Use different properties for mouseover and mouseout in handleMouseOverOut

- www/src/components/PageFooter.js
I noticed that the documentation version was 1.0.0 which was looking at the `www/package.json` version number so I directed it to look at `/package.json`.
Alternatively we could change `www/package.json` version number.
> Change docs footer version reference

- www/src/examples/ToggleButtonGroupControlled.js
- www/src/examples/ToggleButtonGroupUncontrolled.js
- www/src/pages/components/button-group.js
Since part of the documentation got dropped with the switch to gatsby this PR adds `ToggleButtonGroup` and `ToggleButton` back to the Button Groups documentation section and includes all relevant props.
In addition the warning for using Bootstrap JS with the toggle groups as outlined in https://github.com/react-bootstrap/react-bootstrap/issues/2774 is added.
Can you please review the wording of the Bootstrap JS warning?
Note: I think there is still more documentation to be added but I will do this in a seperate PR.
Thanks :)
> Docs for toggle button group

- www/src/pages/getting-started/introduction.js
Locked bootstrap version from MaxCDN for prevent loading of new versions of Bootstrap.
Fixed this issue - https://github.com/react-bootstrap/react-bootstrap/issues/2978
> Lock bootstrap version in Getting Started guide

- www/src/examples/OverlayCustom.js
- www/src/pages/components/overlays.js
Fixes #2997 
I explained in the custom overlays docs the importance of passing down `style` and `className` to the wrapped component.
> Improve custom overlays docs

- src/ProgressBar.js
Fixes #2963
This is the recommended way of doing Component type checking in react hot loader v3. The updated version in v4 using `areComponentsEqual` doesn't seem to work correctly, but this method still seems to work with v4. 
I don't really know how to add any new tests to show this work with RHL, but all the current tests still work.
> Changed ProgressBar check to work with proxied components

- src/PageItem.js
- src/Table.js
- stories/Table.js
- test/TableSpec.js
- www/src/examples/TableDark.js
- www/src/examples/TableResponsiveBreakpoints.js
- www/src/examples/TableSmall.js
- www/src/pages/components/table.js
PR for implementing #3055
- Changed `table-condensed` to `table-sm`.
- Changed `table-inverse` to `table-dark`. There was a confusion caused by the [migration guide](https://getbootstrap.com/docs/4.0/migration/#tables) but I guess I will go fix it there too.
- Brought back the wrapping div for responsive tables. There is again a conflict between the migration guide and the [documentation](https://getbootstrap.com/docs/4.0/content/tables/#responsive-tables).
> Add v4 support for tables

- src/ThemeProvider.js
- test/ThemeProviderSpec.js
- yarn.lock
Maybe we should go a step further and forward it through to the component so it can be attached directly to the DOM node?
> Forward ref

- src/Col.js
Hi, a really small bugfix.
The xs attribute on Col did not work properly, it will generate an erroneous class "col--{size}" instead of "col-{size}".
> V4: Fixing Col xs attribute not working

- src/Tabs.js
Allows one to specify a custom tab animation when using the `Tabs` component. This also can be used as a workaround as `mountOnEnter` is not honored when `animation=false` (ideally a different PR would fix the workaround).
> Allow custom tab animation

- package.json
v1 uses the React context API, which was introduced in React v16.3.
> Specify React 16.3.0 as a peer dependency

- www/src/pages/index.js
On the home page, replace "it's", the contraction of "it is", with "its", the possesive form.
Unfortunately the syntax highlighting on GitHub is still messed up — maybe changing the file extension to `.jsx` would fix that.
> Nit: Fix grammar (it's vs its)

- src/Popover.js
Popover's `outOfBoundaries` proptype should be boolean. (Proptype currently bool in master)
Reference:
- [React Popper doc](https://github.com/FezVrasta/react-popper)
- [react-popper/Popper.js](https://github.com/FezVrasta/react-popper/blob/4e35c6f83242aed0397e5d66c7f8ca17475f1977/src/Popper.js)
fixes issue: #3328
> fix Popover outOfBoundaries proptype

- src/Dropdown.js
- src/DropdownMenu.js
- src/DropdownToggle.js
`title` is a prop for for [`<DropdownButton>`](https://react-bootstrap.netlify.com/components/dropdowns/#dropdown-button-props) and  [`<SplitButton>`](https://react-bootstrap.netlify.com/components/dropdowns/#split-button-props), but not for [`<Dropdown.Toggle>`](https://react-bootstrap.netlify.com/components/dropdowns/#dropdown-toggle-props). 
(A `title` passed to [`<Dropdown.Toggle>`](https://react-bootstrap.netlify.com/components/dropdowns/#dropdown-toggle-props) will just [got forward to its child](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/DropdownToggle.js#L73).)
> Improve documentation

- package.json
- src/AbstractNavItem.js
- src/Dropdown.js
- src/DropdownMenu.js
- yarn.lock
React 16.6 has a deprecation warning about rendering context directly
Fixes #3347
> Render context consumer instead of context itself

- src/Nav.js
- src/NavItem.js
- src/TabPane.js
- test/NavDropdownSpec.js
- test/NavItemSpec.js
- test/NavSpec.js
- test/NavbarSpec.js
- www/src/components/SideNav.js
- www/src/examples/Nav/List.js
- www/src/pages/components/navs.mdx
- www/yarn.lock
- yarn.lock
BREAKING CHANGE: components no longer default to a list
> feat: change default Nav components to non ul/li

- src/FormCheck.js
- src/FormCheckInput.js
- src/FormCheckLabel.js
- test/FormCheckSpec.js
- www/src/examples/Form/Basic.js
- www/src/examples/Form/CheckApi.js
- www/src/examples/Form/CheckCustom.js
- www/src/examples/Form/CheckCustomInline.js
- www/src/pages/components/forms.js
Implemented custom checkboxes and radios mode as discussed in [3047](https://github.com/react-bootstrap/react-bootstrap/issues/3047).
Includes tests and documentation
> Add support for custom checkboxes and radios

- src/Dropdown.js
- src/FormControl.js
- src/FormLabel.js
- src/Nav.js
- src/TabPane.js
- www/src/components/Heading.js
As outlined in https://github.com/4Catalyzer/react-context-toolbox/issues/9, context toolbox needs to only use `Context.Consumer` since it can't navigate to the `Consumer` property reliably.
> Pass Context.Consumer to context toolbox

- package.json
Using double-quotes seems to satisfy the argument parser, and gets thing working again.
> Fix Appveyor build

- types/components/Popover.d.ts
according to the documentation, the `title` prop in `Popover` component should be `node` not `string`
> fix wrong type definition in Popover

- types/components/DropdownButton.d.ts
- types/components/NavDropdown.d.ts
- types/components/Popover.d.ts
This pull request updates some of the typings to match the source code and the documentation:
https://github.com/react-bootstrap/react-bootstrap/blob/c3d64fbb49ea96900d5275dfd6a00b178157adc4/src/DropdownButton.js#L21
https://github.com/react-bootstrap/react-bootstrap/blob/c3d64fbb49ea96900d5275dfd6a00b178157adc4/src/NavDropdown.js#L20
https://github.com/react-bootstrap/react-bootstrap/blob/c3d64fbb49ea96900d5275dfd6a00b178157adc4/src/Popover.js#L65
> Update typings to match source code

- www/src/pages/components/progress.js
Fix prop name `active` to `animated` (to v4).
> Fix animated prop name in ProgressBar

- www/src/examples/Alert/DismissibleControlled.js
[Re: issue # 3503](https://github.com/react-bootstrap/react-bootstrap/issues/3503)
1. The documentation notes that you can pass the `dismissable` (spelled with an "a") prop to an Alert component. However, it should be `dismissible` (spelled with an "i"). I've come to understand that the documentation in `master` is correct, however, the live version of the documentation is not and needs to be refreshed. 
2. The refactored code fixes the spelling error in the `AlertDismissable` class and renames it to the more appropriate `AlertDismissible` for the sake of consistency.
> andrewnystrom:patch-1: Fix spelling mistake regarding Alert component. 

- src/DropdownToggle.js
> fix: Do not pass through undefined child bsPrefix in Dropdown.Toggle

- www/src/pages/components/buttons.mdx
This fixes button size typo in the docs.
> Docs: Fix button size typo

- tools/build.js
```
~/Code/react-bootstrap/tools/build.js:79
.then(() =>
^
TypeError: clean(...).then is not a function
at Object.<anonymous> (~/react-bootstrap/tools/build.js:79:4)
at Module._compile (internal/modules/cjs/loader.js:688:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
at Module.load (internal/modules/cjs/loader.js:598:32)
at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
at Function.Module._load (internal/modules/cjs/loader.js:529:3)
at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
at startup (internal/bootstrap/node.js:285:19)
at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```
At 79 lines in build.js, it using `.then` method. But the current clean method returns `false | Promise`. So, if there is no lib directory, it throws …
> Fix clean method to return Promise always

- tools/build.js
- types/components/NavbarCollapse.d.ts
I tried testing this change in a dependent project, but installing the package from local clone just results in `Cannot find module 'react-bootstrap/Navbar'`. To complicate matters, the build setup seems closely tied to the contributors' development environment. The second commit in this PR fixes the build from a clean state; it only ever worked from a dirty state. There is no `prepare` NPM script: is that intentional?
At the least, this can serve as a starting point.
/cc @jquense
> Add missing props to Navbar.Collapse

- types/components/Modal.d.ts
It is a thing: https://github.com/twbs/bootstrap/issues/26952
The approach of only allowing known values is very brittle. It would be better to do:
`size?: 'sm' | 'lg' | 'xl' | string;`
for this sort of thing. Enumerate the known values but allow unknown ones. Happy to take a stab at fixing this globally if others agree.
> add `xl` to modal size enum

- www/src/pages/components/badge.mdx
Fixes a typo in the markdown formatting in the badges documentation. 
Changes: 
- Formatting changes to `www/src/pages/components/badge.mdx`
> Fixes a typo in the Badges documentation

- src/Spinner.js
- src/index.js
- test/SpinnerSpec.js
- types/components/Spinner.d.ts
- types/components/index.d.ts
- types/simple.test.tsx
- www/gatsby-ssr.js
- www/src/components/SideNav.js
- www/src/examples/Spinner/Basic.js
- www/src/examples/Spinner/Border.js
- www/src/examples/Spinner/Buttons.js
- www/src/examples/Spinner/Grow.js
- www/src/examples/Spinner/Sizes.js
- www/src/examples/Spinner/Variants.js
- www/src/pages/components/spinners.mdx
Adds support for the [spinners components](https://getbootstrap.com/docs/4.2/components/spinners/) introduced in Bootstrap 4.2.
*Changes:*
- Adds new `Spinner` component
- Add tests for new component
- Creates new page in documentation for new component
- Upgrades documentation CSS to Bootstrap 4.2 (given the claimed 4.2 support in the documentation itself) 
*Notes:*
- I wasn't sure about the terminology for the property that switches between the two styles of spinner component. I couldn't think of a good term that wouldn't overlap with an existing property. `animation` was chosen at it was the most representative of the changes the property made, but I feel it may still be too ambiguous. I'm open to alternative suggestions.
- Whilst the documentation claims compatibility with Bootstrap …
> Add support for Spinners

- src/ThemeProvider.js
We should use `useContext` instead of `Consumer` in createBootstrapComponent.
> Use useContext in createBootstrapComponent instead of Consumer

- www/src/pages/migrating.mdx
FormGroup and FormControl are still available in v1 and therefore I think these are not breaking changes.
> Fix migrating.mdx

- www/src/examples/ListGroup/Linked.js
Hi there,
` alertClicked()` function in ListGroup/Linked example wasn't used.  This PR adds onClick parameter to third item.
> Fix ListGroup/Linked example

- types/components/Table.d.ts
Hi, during work with this awesome library I have noticed, that there is a missing prop 'borderless' in TypeScript type definition of Table component. I think it was accidentally missed in this PR #3473.
> Fix Table component TypeScript types

- src/AccordionCollapse.js
- src/AccordionToggle.js
- test/AccordionSpec.js
- www/src/examples/Accordion/AllCollapse.js
- www/src/examples/Accordion/Basic.js
- www/src/examples/Accordion/EntireHeaderClickable.js
Fixes #3614
@bpas247 My bad, some confusion on my end in how our APIs worked
> fix: Fix up accordions a bit

- src/DropdownItem.js
Fixes #3598.
I hope it's okay, that I simplified these `== null` and `!= null` statements.  (active var type is `null|bool` and `makeEventKey() is null|String`)
> fix: DropDownItem prop-types active prop (fix: #3598)

- src/Modal.js
- test/ModalSpec.js
We started setting `display: block` to div.modal at onEnter timing of Transition at Pull #3187. But when we set `animation={false}` to Modal, the Transition object is not created and therefore onEnter (=handleEnter) is not called. This causes empty modal when animation set `false` (I think this is the issue #3399 ). This PR tries to fix this behavior by setting the modal's display style to `block` always.
I think this doesn't break existing behavior because as @jquense says
> we don't allow modals to be in the DOM prior to showing 
the modal's dom element doesn't exist before rendering. So I think it's safe to set display always `block`.
> fix(Modal): set display block always, fixes #3399

- types/components/Nav.d.ts
Open issue https://github.com/react-bootstrap/react-bootstrap/issues/3623
The [documentation for the Nav component](https://react-bootstrap.netlify.com/components/navs) lists `defaultActiveKey` as a supported property.
In this case I didn't add a specific type for Typescript but instead just used the existing type for `activeKey` from `NavProps`. This matches the typing of `Tab.d.ts`
> Add defaultActiveKey to NavProps in Nav.d.ts

- src/Carousel.js
- types/components/Carousel.d.ts
The docs in https://github.com/react-bootstrap/react-bootstrap/blob/85550d39e07071322a43de79d28547611c036dae/src/Carousel.js#L43-L47 describe the behavior of setting `interval` to `null`, but `null` is missing in the typescript type definition.
> Allow null for Carousel interval in Typescript, fix typo in docs

- www/src/examples/Overlays/Overlay.js
excluding warning messages for using "Overlay" component, mainly for properties: "outOfBoundaries" and "show".
> excluding warning messages for using "Overlay" component

- .travis.yml
Before:
| Browser | Version |
| --------- | -------- |
| Firefox   | 56 |
| Chrome | 62 |
After: 
| Browser | Version |
| --------- | -------- |
| Firefox   | 66 |
| Chrome | 73 |
Should fix #3635. I guess just a Firefox bug which is now fixed.
> chore(ci): Using latest Chrome and Firefox releases to perform CI tests

- .eslintrc
- package.json
- www/src/pages/components/navbar.js
- Ran prettier to fix CI
- moved prettier Eslint rule into eslintrc file, so that it will be automatically recognized by Visual Studio Code e.g. and automatically fixed
> fix: ran prettier to fix CI

- www/src/pages/components/modal.js
When reading through the docs I noticed that the name used in the docs to Vertically center the modal is incorrect.
> Altering "verticallyCenter" prop reference to "centered"

- src/Collapse.js
- test/CollapseSpec.js
Fixes #3394
Found this issue while I was attempting to create a Bootstrap menu without a Navbar.Brand component (I just wanted links).  The problem I ran into was when the browser was re-sized to show the collapsed menu and the collapsed menu was expanded, then collapsed and finally the browser was resized to show the full menu, the menu's height was set to 0px.
I have put a full comment in the issue referenced above.
> fix(Collapse): remove 0px menu height on resize and expand/collapse

- types/components/Modal.d.ts
This is to resolve issue #3741 where the `Modal.d.ts` file is missing the `scrollable` flag in the `ModalProps` interface, while the `proptypes` for the component have the flag.
> fix(types): add scrollable to ModalProps interface to match component

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
That are just the default GitHub templates for Bug and Feature. Any suggestions which information we should omit or add there?
Reference:
- https://help.github.com/en/articles/creating-issue-templates-for-your-repository
> chore: added GitHub issue templates

- types/components/FormLabel.d.ts
- types/simple.test.tsx
I'm not sure if just extending `FormLabelProps` with `ColProps` is the preferred way to solve this issue or if you would want something that actually enforces that the column size props are only valid when `column` is `true`.
I can make the typing stricter if that's preferred. It also seems like generally types aren't imported around and reused so if that's a problem I can copy them over completely from `Col.d.ts`
> fix(types): add bootstrap sizes for Form.Label as column

- types/components/DropdownMenu.d.ts
Change from `alignRight?: true` to `alignRight?: boolean`
PropTypes of `DropdownMenu` state that alignRight is a boolean and can be undefined (`alignRight: PropTypes.bool`) but the TypeScript definitions don't allow `false`.
> Fix alignRight type

- www/src/pages/components/input-group.js
Fix small typo in Forms -> input groups -> multiple inputs section
> docs(input-group): fix typo in description

- src/TabPane.js
> fix(TabPane): wrong assigned Transition event(unmountOnExit)

- src/Row.js
This allows for users to be able to properly pass refs to the
underlying component.
Fixes #3923.
> Refactor Row to use forwardRef

- src/Popover.js
The propTypes of the `placement` prop for `Popover` should only be of types:
- auto
- top
- bottom
- left
- right
as per the [bootstrap upstream docs](https://getbootstrap.com/docs/4.0/components/popovers/#options)
Fixes #3951.
> fix: Popover placement prop-types to correct list of props

- tools/build.js
Release notes: https://github.com/sindresorhus/execa/releases/tag/v2.0.0
https://github.com/react-bootstrap/react-bootstrap/issues/3964
> fix: build step due execa version bump (fix #3964)

- www/.eslintrc.js
- www/src/components/ReactPlayground.js
- www/src/examples/.eslintrc
- www/src/examples/Alert/Dismissible.js
- www/src/examples/Alert/DismissibleControlled.js
- www/src/examples/Button/Loading.js
- www/src/examples/Button/ToggleButtonGroupControlled.js
- www/src/examples/Carousel/Controlled.js
- www/src/examples/Collapse.js
- www/src/examples/Fade.js
- www/src/examples/Form/ValidationNative.js
- www/src/examples/Modal/Basic.js
- www/src/examples/Modal/CustomSizing.js
- www/src/examples/Modal/DefaultSizing.js
- www/src/examples/Modal/Grid.js
- www/src/examples/Modal/VerticallyCentered.js
- www/src/examples/Nav/Dropdown.js
- www/src/examples/Overlays/Overlay.js
- www/src/examples/Overlays/PopoverContained.js
- www/src/examples/Overlays/ScheduleUpdate.js
- www/src/examples/Overlays/TooltipOverlay.js
- www/src/examples/Tabs/Controlled.js
- www/src/examples/Toast/Autohide.js
- www/src/examples/Toast/Dismissible.js
With the release of React hooks, it seems appropriate to migrate our simple controlled component examples in our docs to use them. This will give users straightforward examples on how to use our API with React hooks.
Note: Although this is a complete re-write of most of the class component examples, there are still class component examples in our docs that we won't be able to migrate to function components. This is mostly due to them implementing parts of our API that requires the example components to be instantiated (e.g. passing in the `container` prop for `Overlay` shown in this [example](https://github.com/react-bootstrap/react-bootstrap/blob/b0ed370f667d4d8afdfd59375f4240cc653380b1/www/src/examples/Overlays/PopoverContained.js#L23)).
> Migrate doc examples to functional components

- src/AccordionToggle.js
- src/index.js
- src/useAccordionToggle.js
- www/src/examples/.eslintrc
- www/src/examples/Accordion/CustomToggle.js
- www/src/pages/components/accordion.mdx
Adds a hook that API users can utilize to make custom `AccordionToggle` components.
Also comes with a re-factoring of `AccordionToggle` to utilize the `useAccordionToggle` hook.
Fixes #3796.
> feat: Add useAccordionToggle hook

- types/components/Popover.d.ts
- types/components/PopoverContent.d.ts
- types/components/PopoverTitle.d.ts
- types/components/index.d.ts
I need this to add popovers to my app
> fix: Add types for Popover sub-components

- src/Carousel.js
- test/CarouselSpec.js
- types/components/Carousel.d.ts
See issue [4136](https://github.com/react-bootstrap/react-bootstrap/issues/4136)
> fix(Carousel): fixes #4136 - reverse carousel slide navigation direction for touch

- README.md
Before:
After:
Second version is more common I guess, that's why I'm changing it here. :)
> docs: README.md enhancements

- types/components/Navbar.d.ts
It's already supported by the JS code and it allows the navbar never to
expand.
Fix #4174
> Change Navbar expand prop TypeScript definition to allow false value.

- src/Modal.js
- www/src/examples/Modal/WithoutAnimation.js
- www/src/pages/components/modal.js
https://github.com/react-bootstrap/react-bootstrap/issues/4190
> fix(Modal): directly show backdrop if no animation (fix: #4190)

- src/Button.js
- src/Fade.js
- src/InputGroup.js
- src/Jumbotron.js
- src/ListGroup.js
- src/ListGroupItem.js
- src/SafeAnchor.js
- src/Spinner.js
- src/SplitButton.js
- src/Tabs.js
- src/Toast.js
- src/ToastHeader.js
- src/Tooltip.js
- test/DropdownItemSpec.js
- test/SafeAnchorSpec.js
The first pass-through of migrating more class components to properly forward their refs, via `React.forwardRef`.
Relevant to #4012 and #4031.
> fix: Migrate more components to properly forward refs

- src/AccordionCollapse.js
- test/AccordionSpec.js
A general re-write of the way we test the Accordion component,
as the previous behavior wasn't explicitely testing the
functionality of the Accordion component.
>  test(Accordion): change accordion spec to test closer to design

- types/components/Toast.d.ts
- types/simple.test.tsx
I don't know how to fix this, but that's at least the test for it.
Would be cool if someone could help me :)
> fix(types): Toast component

- src/Navbar.js
This migrates the Navbar component to be a function component, which should resolve the lifecycle deprecation warnings.
fixes #4240
> fix(navbar): resolve lifecycle warning issue

- src/Form.js
- src/FormCheck.js
- src/FormCheckInput.js
- src/FormCheckLabel.js
- src/FormControl.js
- src/Switch.js
- src/index.js
- test/FormCheckSpec.js
- types/components/FormCheck.d.ts
- types/components/FormControl.d.ts
- types/components/FormGroup.d.ts
- www/src/components/PropTable.js
- www/src/examples/Form/Switch.js
- www/src/pages/components/forms.js
> feat: add Switches

- www/src/examples/Overlays/PopoverContained.js
Fix example here => https://react-bootstrap.github.io/components/overlays/#overlays-container
Event shall be destructured into a "target" variable in order handle click to work properly.
> docs: Fix PopoverContained sample

- src/AbstractNav.js
- test/NavSpec.js
- test/TabContainerSpec.js
Due to changes made in #4031, `AbstractNav` now needs to explicitly pass `role` down to `Component`.
Fixes issue reported in #4313.
Updated tests to catch the problem.
> fix(AbstractNav): Re-add role attribute to abstract nav

- CHANGELOG.md
regenerated by running `yarn changelog -r 3`
> chore: added missing versions to changelog (fix: #4270)

- README.md
i don't know why I've forgot this one
>  docs: updated link for old bs3 docs in README

- www/src/examples/ResponsiveEmbed.js
Updated to be to be consistent with documented API. Without this, the example would produce a type error as follows:
```
TypeScript error in /home/rod/git/projectphoenix/src/components/post.tsx(32,4):
Type '{ children: Element; aspect: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<ResponsiveEmbed> & Readonly<ReplaceProps<"div", BsPrefixProps<"div"> & ResponsiveEmbedProps>> & Readonly<{ children?: ReactNode; }>'.
Property 'aspect' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ResponsiveEmbed> & Readonly<ReplaceProps<"div", BsPrefixProps<"div"> & ResponsiveEmbedProps>> & Readonly<{ children?: ReactNode; }>'.  TS2322
30 |         </Card.Title>
31 |         <Badge variant="primary">example_tag</Badge>
> 32 | …
```
> Update ResponsiveEmbed example

- src/TabContainer.js
- src/Tabs.js
Replace `uncontrollable` with equivalent `useUncontrolled`.
Fixes #4368.
> fix(TabContainer): Resolve lifecycle deprecation

- src/NavbarToggle.js
- test/NavbarSpec.js
> Navbar toggle correct 'collapsed' className when collapsed

- types/components/Modal.d.ts
- types/components/Popover.d.ts
This PR updates the type definitions for the Popover and Modal components.
Over time new props have been added to the Modal and Popover components, but these new props are not yet included in the respective typescript type definitions.
> fix(types): add missing Popover and Modal props

- types/components/ToggleButton.d.ts
Found a typo in the ToggleButton component, which blocks disabling Togglebuttons.
> ToggleButton Component: Typo in props

- www/src/pages/utilities/react-overlays.js
This PR aims to address #4455, where the link to the `react-overlays` documentation page isn't working because of a conflict with Gatsby/React's internal routing (and throws an invisible 404 in the console). To fix this, I've added `target="_blank"` and `rel="noreferrer noopener"` to the anchor tag, so it opens in a new tab (and will look for the site rooted at `https://react-bootstrap.github.io/react-overlays/` rather than using the SPA router).
> docs: makes link to react-overlays open in a new tab

- types/components/Alert.d.ts
- types/components/DropdownItem.d.ts
- types/components/DropdownToggle.d.ts
- types/components/NavLink.d.ts
- types/components/SafeAnchor.d.ts
- types/components/Spinner.d.ts
- types/components/Tabs.d.ts
- types/components/ToggleButton.d.ts
- types/components/ToggleButtonGroup.d.ts
- types/components/helpers.d.ts
- types/simple.test.tsx
This is the real solution to solve the problem in https://github.com/react-bootstrap/react-bootstrap/pull/4512. 
With this change the `As` generic argument and the dependent props are correctly inferred for both Intrinsics ('div', 'a', ...) that where already working as well as other react-bootstrap Components ('SafeAnchor',  'Button') **new fix!!**
Here is a playground snippet comparing the two solutions. 
http://www.typescriptlang.org/play/?jsx=2#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdWAHpLHDAJ5hZwDyIwGAB4AKgBo4AVQB8cALxwACsFwBrURICiTXABsArgBMsQ1Vg4QCccXDMWrM6fUYto8Tt0xYwuvFkXEYKhCAJIAdmFYUHDMMFhhhujYeDAAdJq6WCDxMCJcWBKKsgr8gkJ0cF4pqQDCJJCRYTABEEEA6oIAFtgEoRFR0mIVSnSyAGTDis7MrPDATVEEfnAAQqgBWATATC1BQgCC6LHxiVX46ZnZTXncsgDew2gA-ABccIf0lQBG65RbTK84KgYFB5gBzegAXwYMzccD0aHQaw2- …
> fix typings for Components passing props to other component

- src/FormCheck.js
- src/FormCheckInput.js
- test/FormCheckSpec.js
- types/components/FormCheckInput.d.ts
Addresses react-bootstrap/react-bootstrap#4565
I haven't written tests yet:
- I won't spend the time unless a maintainer says this feature could be accepted
- I can't write tests unless I can run them:
- `npm test` returns a billion errors before I have even made any changes
- Following the guidelines in CONTRIBUTING.md leads me to try `npm run tdd FormCheckInput` which fails (cannot find module), or `npm run tdd src/FormCheckInput` which also fails (syntax error: unexpected identifier classNames in `import classNames from 'classnames';`, which I haven't touched)
> Add 'as' prop to Form.Check

- package.json
This PR updates the minimum react requirements for the "bootstrap 3" track. #4244 refactored the code to use the `UNSAFE_` methods. These methods were only introduced in [`react@16.3.0`](https://github.com/facebook/react/blob/master/CHANGELOG.md#1630-march-29-2018) so that version is going to be necessary for it to work.
Please let me know if you would like me to add version increment (0.33.0?) to this PR to support the release of a React 16.9 friendly version of the Bootstrap3 package. Happy to include that. Additionally let me know if there's anything else you'd like modified.
> Update min required React for UNSAFE_ lifecycles

- CONTRIBUTING.md
- www/src/pages/components/overlays.js
Issue: #4598
The official term is "function component"
Removed "stateless" in found occurrences
> Remove "stateless" before function component

- www/src/examples/Overlays/OverlayTrigger.js
- www/src/pages/utilities/react-overlays.js
Hey there! This is a super quick PR that implements a fix for the problem in [react-bootstrap/react-overlays#312](https://github.com/react-bootstrap/react-overlays/issues/312). It now uses the `Tooltip` component, which properly handles down the props that were causing problems!
> docs: updating example in overlay-trigger documentation

- test/BreadcrumbItemSpec.js
- test/ModalSpec.js
- test/OverlayTriggerSpec.js
- test/SplitButtonSpec.js
- test/index.js
Sometimes the following tests are failing:
https://github.com/react-bootstrap/react-bootstrap/runs/248586391#step:8:591
```
<OverlayTrigger>
✖ Should pass transition callbacks to Transition
Firefox 69.0.0 (Mac OS X 10.14.0)
uncaught exception: AssertionError: expected 'next' to equal 'prev' (:0)
✖ "after each" hook for "allows only ProgressBar in children"
Firefox 69.0.0 (Mac OS X 10.14.0)
console.error.expected is undefined
./test/index.js/<@webpack:///test/index.js:63:1 <- test/index.js:227223:7
✖ "after each" hook for "should contain `embed-responsive` class"
Firefox 69.0.0 (Mac OS X 10.14.0)
console.error.expected is undefined
./test/index.js/<@webpack:///test/index.js:63:1 <- test/index.js:227223:7
```
https://github.com/react-bootstrap/react-bootstrap/runs/248886920#step:8:483
``` …
```
> tests: reworked sometimes failing tests

- .github/workflows/nodejs.yml
Basically the same deal as the [React Overlays issue](https://github.com/react-bootstrap/react-overlays/pull/448).
> ci(actions): fix build not triggering on forked prs

- src/Carousel.js
Regarding issue #3508.
The class "carousel-item" is duplicated because it gets passed from the parent as well as the carousel item itself:
`export default createWithBsPrefix('carousel-item');`
We fix this by no longer passing the class from the parent.
> #3508 fix duplicate class "carousel-item"

- package.json
- src/Dropdown.js
- src/Navbar.js
- src/Panel.js
- src/PanelGroup.js
- src/TabContainer.js
- src/Tabs.js
- src/ToggleButtonGroup.js
- src/utils/bootstrapUtils.js
- test/DropdownButtonSpec.js
- test/DropdownSpec.js
- test/NavbarSpec.js
- test/PanelGroupSpec.js
- test/PanelSpec.js
- test/TabsSpec.js
- yarn.lock
Fixes #4398 for [`uncontrollable`](https://github.com/jquense/uncontrollable) components:
* Dropdown
* Navbar
* Panel
* PanelGroup
* TabContainer
* Tabs
* ToggleButtonGroup
In conjunction with https://github.com/react-bootstrap/react-bootstrap/pull/4244, this stops most of the warnings. The only warnings that remain are from [`react-overlays ^0.8.0`](https://github.com/react-bootstrap/react-overlays/tree/v0.8.3).
Also fixes the tests that broke since `uncontrollable` may now return `forwardRef()` components, which cannot be inspected with ReactTestUtils. (See https://github.com/facebook/react/issues/13455 for details.)
> Fix(Bs3): Remove unsafe lifecycles by upgrading uncontrollable to ^7.0.2

- src/Col.js
Minor typo fix which appears in the layout component documentation
> Fix typo in Col layout docs

- www/src/components/ComponentApi.js
Seems like GitHub is extracting the warnings, so better to exclude it that we now have no warnings anymore.
> fix: added eslint pragma for ignoring dangerouslySetInnerHTML

- www/src/pages/components/list-group.mdx
Fixed a small typo in the docs of ListGroup component where it says `List.Item` instead of `ListGroup.Item`.
> docs: List.Item to ListGroup.Item

- src/ListGroup.js
- test/ListGroupSpec.js
- www/src/examples/ListGroup/Horizontal.js
- www/src/examples/ListGroup/HorizontalResponsive.js
- www/src/pages/components/list-group.mdx
This PR aims to implement the requested feature in #4410, exposing a prop to allow for [horizontal list groups](https://getbootstrap.com/docs/4.3/components/list-group/#horizontal). The prop, `horizontal`, is stringly-typed and supports six values:
* `null` - vertical flow. This is the default
* `true`/boolean attribute - list group items flow horizontally across all breakpoints
* `sm` - list group items flow horizontally for `sm` viewports and above
* `md` - list group items flow horizontally for `md` viewports and above
* `lg` - list group items flow horizontally for `lg` viewports and above
* `xl` - list group items flow horizontally for `xl` viewports and above
In addition, there's a styling conflict with horizontal list groups and using the `flush` variant, as noted in [the Bootstrap …
> feat: adds support for horizontal list groups via layout prop

- src/ToggleButton.js
- types/components/ToggleButton.d.ts
This is a first pass at handling the ref forwarding work for the ToggleButton.
https://github.com/react-bootstrap/react-bootstrap/issues/4194
- I think that `innerRef` can be removed for this component, as well as the previously added "wrapping ref" that was exported. I'm new to this project so that could totally be wrong.
> [#4194] - ref forwarding for ToggleButton

- types/components/FormControl.d.ts
- types/simple.test.tsx
These changes seemed get the types sorted out for my project.  I added some tests to `simple.test.tsx` to confirm and demonstrate my usage.
May want to consider adding a test-types script to package.json and including it in the main test script.
```
"test": "npm run lint && npm run dtslint && npm run test-browser && npm run test-node && npm run test-types"
"test-types": "tsc --noEmit -p types"
```
> fix(FormControl): onChange and innerRef ts decls (#3583,#3568,#2781)

- www/src/pages/components/navs.mdx
Hey there! This is a very small PR that follows up on #4314, which is that vertical navs (created by `class="flex-column"` are not styled properly when used on Tabs (`variant="tabs"`), which is an issue core to Bootstrap's stylesheet.
Let me know if I should change the language of the docs!
> docs(Navs): mentions that vertical navs styled as tabs are unsupported by Bootstrap

- CONTRIBUTING.md
A minor tidy up for the wording and formatting within the CONTRIBUTING doc
> Spelling/grammar/formatting fixes for CONTRIBUTING

- types/components/AccordionToggle.d.ts
Change the type definition for the useAccordionToggle hook to avoid errors with typescript.
*Related Issue:*
https://github.com/react-bootstrap/react-bootstrap/issues/4792
> Fix useAccordionToggle type

- types/components/Overlay.d.ts
The type is incorrect, and is a regression from v0.x; react-overlays supplies the event to the `onHide` callback.
Reference:
- `onHide` is called from the `useRootClose` hook: https://github.com/react-bootstrap/react-overlays/blob/master/src/Overlay.js#L74
- `useRootClose` passes the event to the `onClose` function: https://github.com/react-bootstrap/react-overlays/blob/master/src/useRootClose.js#L59
> Fix type of Overlay's onHide prop

- src/Tooltip.js
> prevent `non-boolean attribute` warning when passing `show` to Tooltip

- src/index.js
Added the missing NavLink export to index.js that was accidentally missing from my last PR.
> Added NavLink to index.js

- src/Modal.js
- src/ModalDialog.js
This PR applies the backport fix for (#3373 and #2666) which was already applied in PR #3187 for Bootstrap 4.
> fix(Modal): prevent closing if mouseup was outside

- src/Row.js
Hi
I'm not sure if there is a reason why Row does not have a display name? But I could see that Col (and most other components that uses React.forwardRef) has one, so I just added it to Row as well.
Adding a display name makes components using forwardRef, appear correctly in the React Developer Tools extension for chrome.
> Add displayName to Row

- src/Breadcrumb.js
A very minor change to the docs for Breadcrumb -- it uses an `<ol>` vs a `<ul>`.
> docs: fix element type used for Breadcrumb

- test/TabContainerSpec.js
- test/ToastSpec.js
- I wrote test cases to increase coverage for Toast.js and TabContainer.js
- I removed a fallback for id in Tabcontainer.js since there was no way (I could think of) that can happen. Please let me know if I should revert the refactoring.
related #3889
> increase test coverage with minor refactor

- src/Container.js
- test/ContainerSpec.js
- www/src/examples/Grid/Container.js
- www/src/examples/Grid/ContainerFluid.js
- www/src/examples/Grid/ContainerFluidBreakpoint.js
- www/src/pages/layout/grid.js
An attempt at extending `<Container>` with breakpoints as in #4884
**I have not updated docs yet since I want to make sure we find consensus about how this prop should work for the Container component.** I will add docs once we have decided if this is a good idea or not.
- Adds "breakpoint" prop to `<Container>`
- Permits only "sm", "md", "lg" and "xl" (same as Bootstrap classes)
- if fluid is set it takes precedence since fluid and container-[breakpoint] should not be combined
- updated test for `<Container>` to include breakpoint
I first considered setting sm, md, lg and xl as booleans, but realised that would allow for all kinds of fails since then you could set more than one as true at the same time (not good).
And since we already have fluid I left that prop alone and extended on it. …
> #4884 add responsive containers

- www/src/components/ComponentApi.js
> docs: Use import name in source links

- src/Modal.js
Hello everyone,
This PR is referring to the following issue https://github.com/react-bootstrap/react-bootstrap/issues/3645 which is not yet fixed.
If `ModalManager` is constructed with `defaultProps` there is still a chance that `document.body` is not yet present.
By delaying the construction until the constructor of the `Modal` is actually called, we can avoid this problem.
I know that one can avoid this problem by moving all JS includes to the body, but that can be impractical and weird in larger project, where you gotta keep track of all the includes that are being loaded.
Best,
Jo
> Don't construct ModalManager while document.body may still be null

- types/components/ListGroup.d.ts
Hi,
This PR fixes a minor oversight with PR #4864 - the ListGroup component has a horizontal prop which is either a boolean (makes it horizontal) or a string (this makes the ListGroup horizontal at a given breakpoint) - PR #4864 only covers the boolean use case.
Thanks!
> Added type string to ListGroupProps horizontal prop

- src/AccordionCollapse.js
Accordion.Collapse cannot have more than one child else the application will crash with the error `Unhandled Rejection (Error): React.Children.only expected to receive a single React element child.` Added a comment to reflect that.
> Add Comment to AccordionCollapse.js

- src/SplitButton.js
- test/SplitButtonSpec.js
https://github.com/react-bootstrap/react-bootstrap/issues/5008
> Allow type to be set for SplitButton non-toggle Button

- www/src/pages/index.js
Previously, the hyphen at the end of the line caused whitespace to appear between `React-` and `Bootstrap` on the homepage
> Fix whitespace on homepage

- src/FormControl.js
- test/FormControlSpec.js
- types/components/FormControl.d.ts
The React Typescript definition for an input supports strings, an array
of strings, or numbers. I've adjusted the types and PropType of the
"value" prop to support this.
Reference:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2058
https://github.com/react-bootstrap/react-bootstrap/issues/5028
Fixes #5028
> Adjust type of FormControl to support numbers

- CHANGELOG.md
Include responsive containers in changelog. Only the types fix was included.
Since beta 17 seem to be unpublished, this adds responsive containers to the changelog
> Update CHANGELOG.md for beta 17

- src/FormControl.js
- test/FormControlSpec.js
- types/components/FormControl.d.ts
- www/src/examples/Form/Range.js
- www/src/examples/Form/RangeCustom.js
- www/src/examples/Form/SelectCustom.js
- www/src/examples/Form/SelectCustomSize.js
- www/src/pages/components/forms.js
This PR adds the Range input to Form.Control.
It also adds the custom prop to Form.Control and is usable if type is set to range or if as is set to select. It also handles sizing of the select element if custom is set.
It has added tests as well as updated documentation.
> #3047 Range input and allow for custom prop for select and range input

- src/Row.js
- test/RowSpec.js
- types/components/Row.d.ts
- www/src/examples/Grid/RowColLayout.js
- www/src/examples/Grid/RowColLayoutColWidth.js
- www/src/examples/Grid/RowColLayoutColWidthBreakpoint.js
- www/src/pages/layout/grid.js
This PR extends <Row> to accept sizing prop similar to how <Col> does it.
I created an issue for this, #4887 , and here is my attempt at an PR for it.
- Extends Row.js with logic from Col.js
- Updated RowSpec.js with what it should handle with the above changes
- Updated docs with some examples and text that (hopefully) explains how it works
There are some gotcha's I found while creating this:
- The sizing prop into `<Row>` doesn't set the column widths, rather it sets the number of columns that should fit next to each other
- Setting `<Row md={4}>` will override `<Col xs={6}>` on medium devices (Row-sizing props takes precedence based on breakpoint as it does in Bootstrap)
- Setting `<Row md={4}>` will NOT override `<Col md={6}>` on medium devices
I'm unsure if this is clear enough in …
> #4887 Add support for setting columns in <Row>

- src/TabContainer.js
- src/TabPane.js
- src/Tabs.js
The Tabpane component has a bug where when set to unmount on exit, any transitions are ignored. The solution was already discussed in issue #3497 by @sisp and @jquense ; I am shepherding it to the library.
@sisp created a [codesandbox](https://codesandbox.io/s/xl5n993np4) showing how in the latest release of react-bootstrap `<TabPane ... unmountOnExit=true />` on does not execute the transition between tabs.
Refs #3497
> fix: Allow tab to un/mount with transition

- src/BreadcrumbItem.js
- test/BreadcrumbItemSpec.js
- types/components/BreadcrumbItem.d.ts
As discussed with @taion in #5022, in addition to `linkAs`, the inner `span` which was added when inactive should be dropped. The tests have been adapted in consequence.
Fixes #4472. Supersedes #5022.
> feat: can customize BreadcrumbItem's inner link

- src/FormLabel.js
- test/FormLabelSpec.js
- types/components/FormLabel.d.ts
Fixes #4883 
Make FormLabel support `as` prop, analogous to how it's done on other components.
> Make FormLabel support `as` prop

- types/components/Modal.d.ts
The docs have a manager property but it's missing from the types
> fix(Modal): TypeScript manager typings

- types/components/FormLabel.d.ts
- types/simple.test.tsx
Fixes #5056 and adds 'sm' and 'lg' as types for FormLabel column
> #5056 fix types for FormLabel

- .github/workflows/nodejs.yml
- www/src/pages/getting-started/introduction.mdx
- www/src/pages/getting-started/theming.js
This PR is the continuation of my [comment in #4627](https://github.com/react-bootstrap/react-bootstrap/pull/4627#issuecomment-598713995)
- Re-structure getting started with sensible header levels and ordering of information.
- Rename "Importing" to "Importing Components"
- Reorder some sub contents within their headers
- Add missing space in theming
- Updated a link from bootstrap 4.3 docs to 4.4.
> docs: Update & re-structure getting started

- src/Modal.js
- test/ModalSpec.js
fixes #5084. Adds test to check that aria-labelledby is set on the Modal element.
> #5084 sets aria-labelledby on correct element

- src/OverlayTrigger.js
- test/OverlayTriggerSpec.js
Sets flip to true if placement is auto. Discussed in #5111. As an added bonus the possible placements are now displayed on the OverlayTrigger API in the docs.
> #5111 Set flip to true if placement is auto in OverlayTrigger.js

- www/src/pages/components/cards.mdx
Add mention that `<Card.Text>` is a `<p>` tag and can be used multiple times.
This was requested in #5071 so I created this. I'll let you decide if it should be merged, we should do it another way or simple leave it as is.
> #5071 Update cards docs

- src/ToastHeader.js
When I'm passing `onClose` event to `Toast` - this method doesn't receive `event` prop and it's not possible for example to call `event.stopPropagation()` to prevent firing `Toast.onClick` method
> Passing event to onClose prop

- types/components/Overlay.d.ts
The upstream `react-overlays` type for the injected `ref` is actually `React.RefCallback<HTMLElement>` (see https://github.com/react-bootstrap/react-overlays/blob/3646ef243f95c6b91ce05da63b39ce5ee612f465/src/Overlay.tsx#L37). 
That type expands to `(instance: T | null) => void`, not the previous `(instance: T) => void`, so these types were naturally incompatible...
I think the longer-term fix would be to actually expose `OverlayInjectedProps` from `react-overlays` ([this bit](https://github.com/react-bootstrap/react-overlays/blob/3646ef243f95c6b91ce05da63b39ce5ee612f465/src/Overlay.tsx#L31-L45)) and use it here.
Before this is released, a client code fix is e.g.
```patch
{({
placement,
scheduleUpdate,
arrowProps,
outOfBoundaries,
show: _show,
+  ref,
...props
}) => (
-  <div {...props}>
+ …
```
> types(Overlay): fixed type for `ref`

- src/BootstrapModalManager.js
Noticed this while working on TypeScript typings 😄
> BootstrapModalManager: fix typo marging -> margin

- src/FormControl.js
- test/FormControlSpec.js
- types/components/FormControl.d.ts
- www/src/examples/Form/SelectCustomHtmlSize.js
- www/src/pages/components/forms.js
**Description**
The commit of this PR adds support for the size attribute of select and input elements. This is especially useful in case someone wants to create a select table with multiple visible options. (Check https://www.w3schools.com/tags/att_select_size.asp for details.)
**Changes**
**Related issue**
#4499
> feat(FormControl): Add support for html size attribute

- www/gatsby-browser.js
- www/gatsby-ssr.js
fix #5159 FontAwesome icons flash from a large one down to a proper one
> [docs] Fix FontAwesome icons' flash when press F5

- package.json
- src/Modal.js
- test/ModalSpec.js
- www/src/examples/Modal/StaticBackdrop.js
- www/src/pages/components/modal.js
- yarn.lock
Resolves #5163 
This adds the animation using the bootstrap class `modal-static`. The animation will appear on static backdrop modals when clicking the backdrop or pressing escape when `keyboard` is set to `false`.
> feat(Modal): Add modal static backdrop animation

- www/src/examples/Form/FormDisabled.js
- www/src/examples/Form/FormDisabledInputs.js
- www/src/examples/Form/FormFile.js
- www/src/examples/Form/FormText.js
- www/src/examples/Form/FormTextInline.js
- www/src/examples/Form/GridAutoSizing.js
- www/src/examples/Form/GridAutoSizingColMix.js
- www/src/examples/Form/GridAutoSizingCustom.js
- www/src/examples/Form/GridColSizes.js
- www/src/examples/Form/Inline.js
- www/src/examples/Form/InlineCustom.js
- www/src/examples/Form/InputReadOnly.js
- www/src/examples/Form/SelectSizes.js
- www/src/pages/components/forms.js
Added missing Form.Text API into the docs.  Also added more docs/examples so the forms section is more in sync with official bootstrap docs.
> docs(Form): Added missing Form.Text API and more docs/examples

- src/AccordionToggle.js
- src/FormCheck.js
- src/FormCheckInput.js
- src/FormControl.js
- src/FormFile.js
- src/FormFileInput.js
- www/src/examples/Button/ToggleButton.js
- www/src/examples/Card/BgColor.js
- www/src/examples/Dropdown/ButtonSizes.js
- www/src/examples/Dropdown/DropDirections.js
- www/src/examples/Dropdown/SplitVariants.js
- www/src/examples/Dropdown/Variants.js
- www/src/examples/Form/FormDisabled.js
- www/src/examples/Form/FormText.js
- www/src/examples/Form/FormTextInline.js
- www/src/examples/Form/GridAutoSizing.js
- www/src/examples/Form/GridAutoSizingColMix.js
- www/src/examples/Form/GridAutoSizingCustom.js
- www/src/examples/Form/GridComplex.js
- www/src/examples/Form/Inline.js
- www/src/examples/Form/InlineCustom.js
- www/src/examples/Form/ValidationTooltips.js
- www/src/examples/Overlays/PopoverPositioned.js
- www/src/examples/Overlays/TooltipPositioned.js
This PR fixes a bunch of console warnings in the docs along with some prop types and doc examples.
Props changes are as follows:
Accordion `children` - Docs was wrong here about enforcing a single child and you can use any node, so I deleted this as it was not needed.
FormCheck, FormCheckInput, FormControl, FormFile, FormFileInput - Removed isRequired since some of the components default it to `false` anyway.
> docs: Fix docs proptypes and console warnings

- www/src/components/NavMain.js
2 fixes here for these mobile view issues:
1. On the root page, the expanded dropdown menu is being covered by the jumbotron
2. Part of the bootstrap 3 menu option text overflows off the dropdown menu
> docs: Fix version dropdown

- test/CarouselSpec.js
This might fix all those random test failures we've been seeing with each PR:
AssertionError: expected 2 to equal 0
AssertionError: expected 1 to equal 0
I believe setting interval to null should be ok for these tests here since we are testing the carousel indicators clicks and we don't want it to automatically transition.
> test(Carousel): Set interval to null for indicator click tests

- src/OverlayTrigger.tsx
- src/ToggleButtonGroup.tsx
- test/OverlayTriggerSpec.js
resolves a slew of requests I haven't looked up yet
> feat(OverlayTrigger): expose `show` for manually controlling visibility

- .babelrc.js
- package.json
- yarn.lock
react-bootstrap 0.33 is the only demand for core-js 2 in my legacy project now, and while I work on migrating to bootstrap 4, I would love to have core-js 3, since it would solve alot of dependency issues in unrelated code!
- babel version ^7.0.0 =>  ^7.4.0
- core-js 2 => 3
> Bump versions

- package.json
- src/DropdownMenu.tsx
- src/Overlay.tsx
- src/OverlayTrigger.tsx
- src/Popover.tsx
- src/usePopperMarginModifiers.tsx
- yarn.lock
depends on the react overlays bump. 
this still doesn't cover this problem https://github.com/popperjs/react-popper/issues/375 but at least it won't lock up and crash
> fix(Popover): arrow offset when scrolling offscreen

- src/NavContext.tsx
This Merge Request adds `displayName` to `NavContext` to address issue when ParcelJS eliminates identical files when creating a production bundle, similar to #5089.
The following `Navbar` doesn't work:
```
<Navbar bg="light" variant="light" className="header">
<Navbar.Brand className="mr-auto">Alt. Pocket</Navbar.Brand>
<Nav>
<NavDropdown title="Actions" id="basic-nav-dropdown">
{/* a few NavDropdown.Item items */}
</NavDropdown>
</Nav>
</Navbar>
```
It produces an error:
```
react-dom.production.min.js:196 TypeError: x.getControllerId is not a function
at AbstractNavItem.js:28
at Si (react-dom.production.min.js:154)
at lo (react-dom.production.min.js:172)
at Bo (react-dom.production.min.js:263)
at Qu (react-dom.production.min.js:230)
at Bu (react-dom.production.min.js:229)
at Iu …
```
> Give displayName to NavContext

- src/Dropdown.tsx
- src/NavDropdown.tsx
- test/DropdownItemSpec.js
- tests/simple-types-test.tsx
- www/src/examples/Dropdown/DropdownItemTags.js
- www/src/pages/components/dropdowns.mdx
> feat(Dropdown): Add Dropdown.ItemText component

- src/Modal.tsx
- src/ModalDialog.tsx
- test/ModalSpec.js
- tests/simple-types-test.tsx
- www/src/examples/Modal/FullScreen.js
- www/src/pages/components/modal.js
Adds prop `fullScreen` which supports `true` or breakpoints `sm` and up.
https://v5.getbootstrap.com/docs/5.0/components/modal/#fullscreen-modal
> v5: Add fullscreen modal support

- www/src/components/DocsAlert.js
The classic issue of checking a string as if it was a boolean
value.
Also comes with a styling change to put more of an emphasis on
the branch name (when it is being specified).
> fix(docs): type mismatch with environment variable

- src/Form.tsx
- src/FormControl.tsx
- src/FormRange.tsx
- test/FormControlSpec.js
- test/FormRangeSpec.js
- tests/simple-types-test.tsx
- www/src/examples/Form/Range.js
- www/src/examples/Form/RangeCustom.js
- www/src/pages/components/forms.js
V5 combines native and custom ranges.
Changes:
- Create new `FormRange` component - v5 no longer uses the .form-control class and instead uses its own `.form-range` class
- Remove `custom` and `bsCustomPrefix` props from `FormControl` - This is the last control to break out of form control, so it's not needed anymore
- Add associated docs and tests
> v5: Add FormRange component

- .github/workflows/ci.yml
Adds the configuration necessary for triggering our ci builds on
pushes and pull requests to the bs5-dev branch.
> ci(v5): add configuration for pushes and pull requests

- www/src/pages/migrating.mdx
Mainly just a copy/paste of the previous migration docs, along
with a brief summary of the breaking changes so far.
> docs(v5): add migration docs

- src/FormControl.tsx
- src/FormFile.tsx
- src/FormFileButton.tsx
- src/FormFileInput.tsx
- src/FormFileLabel.tsx
- src/FormFileText.tsx
- src/helpers.ts
- test/FormControlSpec.js
- test/FormFileSpec.js
- tests/simple-types-test.tsx
- www/src/examples/Form/File.js
- www/src/examples/Form/FileApi.js
- www/src/examples/Form/FileButtonTextHTML.js
- www/src/examples/Form/FileButtonTextScss.js
- www/src/examples/Form/FormFile.js
- www/src/examples/Form/FormFileSizes.js
- www/src/examples/Form/ValidationTooltips.js
- www/src/pages/components/forms.js
https://v5.getbootstrap.com/docs/5.0/forms/file/
https://v5.getbootstrap.com/docs/5.0/migration/#forms
Changes:
- Dropped file from `FormControl` - v5 removed native file support
- Dropped `custom` and `bsCustomPrefix` props from `FormFile` - custom file input is the new norm
- Added `button` prop - To support custom nodes placed in the Browse button span
- Added `FormFileText` and `FormFileButton` components - The markup for the file input has changed and these were added to support those.  
- Dropped `lang` and `data-browse` - translations and button text are now controlled in html so lang isn't needed.  `data-browse` is replaced by the `button` prop, which allows you to place a node into `FormFileButton`
- Added `size` prop
- Tests, docs, example changes
> v5: Refactor file control and drop file from FormControl

- README.md
- www/src/components/NavMain.js
Is it fine that I've created the Netlify deployment for the Bootstrap 5 version? https://react-bootstrap-v5.netlify.app/
> docs: updated Netlify links for Bootstrap 5

- src/InputGroup.tsx
- test/InputGroupSpec.js
- tests/simple-types-test.tsx
- www/src/examples/InputGroup/Basic.js
- www/src/examples/InputGroup/ButtonDropdowns.js
- www/src/examples/InputGroup/Buttons.js
- www/src/examples/InputGroup/Checkboxes.js
- www/src/examples/InputGroup/MultipleAddons.js
- www/src/examples/InputGroup/MultipleInputs.js
- www/src/examples/InputGroup/Sizes.js
- www/src/pages/components/input-group.js
- www/src/pages/migrating.mdx
https://v5.getbootstrap.com/docs/5.0/forms/input-group/
Note: 
I did run into an issue with the dropdowns that might need to be solved in another PR.  The new markup for dropdowns has the dropdown toggle and menu directly under the `InputGroup`.  
In v4 this was solved with `<DropdownButton as={InputGroup.Prepend}>`, but there's no parent element within `InputGroup` this time.
I don't think there's a way to solve this with the existing components... anybody have any suggestions?
Changes:
- Drop `InputGroupPrepend` and `InputGroupAppend`
- Replace input in `InputGroupCheckbox` with `FormCheckInput`
- Fix tests and examples
> feat(v5): Drop InputGroupPrepend and InputGroupAppend

- www/src/examples/ButtonGroup/Toolbar.js
- www/src/examples/Form/ColorPicker.js
- www/src/examples/Form/FileApi.js
- www/src/examples/Form/GridAutoSizing.js
- www/src/examples/Form/GridAutoSizingColMix.js
- www/src/examples/Form/GridAutoSizingCustom.js
- www/src/examples/Form/Validation.js
- www/src/examples/Form/ValidationFormik.js
- www/src/examples/Form/ValidationNative.js
- www/src/examples/Form/ValidationTooltips.js
Missed a bunch of `InputGroup.Prepend`s in the forms page.  Fixed that along with some console warnings from other examples.
> docs(v5): Fix errors and warnings

- src/NavDropdown.tsx
- tests/simple-types-test.tsx
Fixes issue #5339 
I changed the `NavDropdownProps` to extends from `DropdownProps` instead of `BsPrefixPropsWithChildren`. This way it will include all of Dropdown's props.
> Fix NavDropdown alignRight failing typescript check.

- src/Row.tsx
- test/RowSpec.js
- tests/simple-types-test.tsx
- www/src/examples/Grid/RowColLayout.js
- www/src/pages/layout/grid.js
https://v5.getbootstrap.com/docs/5.0/layout/grid/#row-columns
> With .row-cols-auto you can give the columns their natural width.
> feat(v5): Add row-cols-auto support

- src/ButtonGroup.tsx
- src/ToggleButton.tsx
- src/ToggleButtonGroup.tsx
- test/ButtonGroupSpec.js
- test/ToggleButtonGroupSpec.js
- tests/simple-types-test.tsx
- www/src/examples/Button/ToggleButton.js
- www/src/examples/Button/ToggleButtonGroupUncontrolled.js
- www/src/pages/components/buttons.mdx
- www/src/pages/migrating.mdx
https://v5.getbootstrap.com/docs/5.0/migration/#buttons
https://v5.getbootstrap.com/docs/5.0/forms/checks/#toggle-buttons
Changes:
- add `bsPrefix` for `.btn-check` -  This is a new class for the input
- `id` is now required - The markup has changed so the label is adjacent to the input.  Need `id` and `htmlFor` to make the button click toggle the input
- removed `focus` and `active` class management from ToggleButton - These are no longer present in upstream ToggleButton examples and are not needed
- dropped `toggle` from ButtonGroup - The `.btn-group-toggle` is gone
- docs/tests updates
> feat(v5): ToggleButton changes

- src/Carousel.tsx
- src/CarouselItem.tsx
- src/index.tsx
- test/CarouselSpec.js
- www/src/examples/Carousel/IndividualIntervals.js
- www/src/pages/components/carousel.mdx
Adds the ability to specify intervals per-item, which should
hopefully match the functionality of the upstream feature.
TODOs:
fixes #5305
> feat(carousel): add individual item intervals

- src/Popover.tsx
- src/Tooltip.tsx
https://v5.getbootstrap.com/docs/5.0/migration/#popovers
https://v5.getbootstrap.com/docs/5.0/migration/#tooltips
> Popovers
> Renamed .arrow to .popover-arrow
> Tooltips
> Renamed .arrow to .tooltip-arrow
> feat(v5): Set new arrow class for popover and tooltip

- src/ToggleButtonGroup.tsx
- test/ToggleButtonGroupSpec.js
- tests/simple-types-test.tsx
I am using react-bootstrap in a React/TypeScript project and after upgrading from 1.0.1 to 1.3.0 TypeScript tells me, that "Property 'vertical' does not exist on..." on the `ToggleButtonGroup` component.
So here I added the `vertical` property to the `ToggleButtonGroup` component.
(right now I am making heavy use of `// @ts-ignore` before every ToggleButtonGroup and it works as expected)
> feat(ToggleButtonGroup): Add vertical option

- src/AccordionCollapse.tsx
- test/AccordionSpec.js
- test/NavSpec.js
Fixes #4176
I moved the `SelectableContext` consumption to `NavDropdown` because it looks like this context is used in conjunction with `Nav` in triggering `onSelect` for `NavDropdown`s.
I've added the test in `Nav` to make sure I didn't break anything in that API and another test in `Accordion` to make sure the a dropdown would not trigger the accordion context.
This would also close the PR #4772.
> fix(Accordion): Use empty SelectableContext to prevent dropdown from closing accordion

- src/Col.tsx
- www/src/pages/migrating.mdx
https://v5.getbootstrap.com/docs/5.0/migration/#utilities
> Decreased the number of responsive order utilities per breakpoint. The highest order utility with a number now is .order-5 instead of .order-12.
This PR just changes the TS types to restrict string numbers to max 5
> feat(v5): Set ColOrder types to max 5

- www/src/pages/components/dropdowns.mdx
Changed  'a' to 'of'. It reads a bit nicier and I think it's gramatically correct.
Before:
` but it's very specific to a certain kind a menu. <ARIA /> menus, must`
After:
` but it's very specific to a certain kind of menu. <ARIA /> menus, must`
> docs: Fix small typo in Dropdown documentation

- src/DropdownToggle.tsx
it is better practice to include props.children directly to the component here (?) I can't think of a reason why it is passed separately like this...
> pass {props.children} via ...props in DropdownToggle.tsx

- src/OverlayTrigger.tsx
Should be valid as per:
https://react-bootstrap.github.io/components/overlays/#customizing-trigger-behavior
> fix(OverlayTrigger): Add func as valid prop type for children

- src/Fade.tsx
- tests/simple-types-test.tsx
Fixes #5397 and #5336.
Had some difficulties with the types when extending `TransitionProps` from RTG types, so opted to type `Fade` in a similar way to `Collapse`.  Unsure if this is the best way.
> fix(Fade): fix TS props to work with TransitionType

- src/DropdownItem.tsx
- src/ListGroupItem.tsx
Fixes #5401
I kept the TS type for `eventKey` as string in `DropdownItem` since it's been this way back in Aug 2019.
> fix: Allow falsy eventKeys in DropdownItem and ListGroupItem

- src/usePopperMarginModifiers.tsx
- test/usePopperMarginModifiersSpec.js
I'm facing a bug where the popover arrow isn't properly aligned with the overlay target when using prefixed classes. I'm solving the problem in user-space. Just took a moment to create a PR in case that this feels like a proper fix.
<div align="center"><img width="230" alt="Screen Shot 2020-09-01 at 22 01 00" src="https://user-images.githubusercontent.com/1887029/91927282-b4c4b680-ec9e-11ea-90cb-b7720d4ea0a3.png"></div>
> Fix popover arrow misaligned when class is prefixed

- src/Col.tsx
- src/Container.tsx
- src/ListGroup.tsx
- src/Modal.tsx
- src/ModalDialog.tsx
- src/Navbar.tsx
- src/Row.tsx
- tests/simple-types-test.tsx
- www/src/examples/ListGroup/HorizontalResponsive.js
- www/src/examples/Modal/FullScreen.js
- www/src/pages/components/list-group.mdx
- www/src/pages/components/navbar.js
- www/src/pages/layout/grid.js
Adds XXL support for 
- Row
- Col
- Container - `fluid` prop
- ListGroup - `horizontal` prop
- Modal/ModalDialog - `fullscreen` prop
- Navbar - `expand` prop
> feat(v5): Add XXL support

- www/src/examples/Form/TextControls.js
When using React-Boostrap with TypeScript `rows="3"` will cause a type error: `Type 'string' is not assignable to type 'number | undefined'.`  
Thanks for maintaining React-Bootstrap!
> Fixing small type error in docs for form controls

- www/package.json
- www/yarn.lock
Rolls back the resolution versions (borked by #5385) due to a known [issue](https://github.com/benjamn/ast-types/issues/383) with the `ast-types` dependency.
> fix(docs): roll-back resolution versions

- src/FormCheck.tsx
- src/helpers.ts
- test/FormCheckSpec.js
- www/src/pages/components/forms.js
This PR improves the docs in the FormCheck component.
Fixes #4767 and #5151
- Mentions that `label` and `id` are required props for a switch and fixes proptypes to check this
- Fill in missing docs for inline, disabled, title, label props
- Fixes switch tests so it doesn't fail with new proptype check
- Fix lint warning in helpers.ts
- Change types to extend HTMLAttributes - I notice that when using inline event handlers, the vars are implicitly set as `any`.  This resolves that to the proper type.
> feat(FormCheck): Allow custom controls to render without a label

- src/Button.tsx
- test/ButtonSpec.js
This bugfix aligns the `<button>` variant class implementation with Alert/Badge/Navbar -- only outputing a `prefix-variant` formatted class when a variant is specified and avoiding the situation of outputting `.btn-null` or `.btn-` when the variant is null or an empty string respectively.
This adds several tests to confirm that the default variant gets removed but also the invalid variants don't get outputted.
Split from #5456
> fix(Button): display variant only when set

- test/ModalSpec.js
Added coverage for `centered` and `scrollable` props.
Related to [#3889](https://github.com/react-bootstrap/react-bootstrap/issues/3889)
Happy Hacktoberfest!
> Increase modal test coverage

- src/Modal.tsx
Fixes [#5447](https://github.com/react-bootstrap/react-bootstrap/issues/5447).
> [ Docs - Modal ] Default size prop is missing in Modal documentation. 

- www/src/components/SideNav.js
- www/src/examples/CloseButton/Basic.js
- www/src/examples/CloseButton/Disabled.js
- www/src/examples/CloseButton/Labelled.js
- www/src/examples/CloseButton/Variants.js
- www/src/pages/components/close-button.mdx
See #5468. Some adjustment of the TS API may be required, see below where the `variant`'s type is the string literal of `'white'` (`PropTypes.oneOf[null, 'white']`?):
> docs(CloseButton): add component page

- www/src/pages/components/cards.mdx
Looks like this one was missed in the docs, opening so I can send the link to a student learning React 🙂
> Add CardColumns ComponentApi component to docs

- CONTRIBUTING.md
- MAINTAINING.md
- README.md
- www/src/components/NavMain.js
The old invite was putting joiners into an error state due to the Code of Conduct gate! Not ideal.
> Use main Reactiflux invite

- .github/workflows/ci.yml
Workaround for the error we've been seeing with `brew update`.
Ref: actions/virtual-environments#1811
> Workaround for macOS CI brew update error

- src/Dropdown.tsx
- src/DropdownButton.tsx
- src/DropdownMenu.tsx
- src/NavDropdown.tsx
- test/DropdownButtonSpec.js
- test/DropdownItemSpec.js
- test/DropdownMenuSpec.js
- test/NavDropdownSpec.js
- www/src/examples/Dropdown/ButtonDark.js
- www/src/examples/Dropdown/NavbarDark.js
- www/src/pages/components/dropdowns.mdx
- www/src/pages/migrating.mdx
https://v5.getbootstrap.com/docs/5.0/components/dropdowns/
Added the dark dropdown variant initially.
Changes:
- Set default element of DropdownDivider to hr
- Add variant prop for DropdownMenu
- Add menuVariant prop for DropdownButton and NavDropdown
I noticed that Bootstrap changed their dropdown menu/item markup back to using ul/li in https://github.com/twbs/bootstrap/pull/28591 . We should probably do the same here.  I wanted to get some feedback before adding those changes though. In `DropdownItem`, I could make it so the props control the `li` element, then apply the anchor specific props/classes to the inner anchor... but then this probably need additional props to control rendering of the anchor.  Alternatively, add a bare `li` wrapping element and keep the current implementation …
> feat(v5): Update dropdown

- www/package.json
- www/yarn.lock
react-docgen updated their dependency, so ast-types doesn't need to be in resolutions anymore.
> chore: Remove ast-types from resolutions

- src/FormCheck.tsx
This should make e.g. `onChange={e => e.target.checked}` work out of the box.
> fix(types): Specify FormCheck's onChange type exactly

- .github/workflows/ci.yml
This is supposed to be fixed upstream so we don't need this workaround anymore.
> chore(ci): Undo macOS brew workaround

- src/DropdownMenu.tsx
Passing `style` to `DropdownMenu` currently gets overwritten with the style from popper instead of being merged.  This was a regression from the typescript merge.
> fix(DropdownMenu): Fix base styles being overridden by popper styles

- src/Alert.tsx
- test/AlertSpec.js
I believe this is the fix for the following issue I opened: https://github.com/react-bootstrap/react-bootstrap/issues/5544
It looked like the ternary was just backwards, where if a Transition was being used, it would add the props both to the Alert, and the Transition, where it should be the other way around, and only add the props to the Alert, if NO Transition is being used.
The test I wrote fails without this change.
Manual testing and tests seem to verify this conclusion.
> Properly rest html props for `Alert` when `transition={false}`

- src/Button.tsx
- test/ButtonSpec.js
- www/src/examples/Button/Block.js
- www/src/pages/components/buttons.mdx
`.btn-block` has been dropped:
https://getbootstrap.com/docs/5.0/components/buttons/#block-buttons
https://getbootstrap.com/docs/5.0/migration/#buttons
Changes:
- Drop `block` and related tests
- Fix up button block example with css util classes
> feat(v5): Drop block prop from Button

- src/Toast.tsx
- www/src/pages/migrating.mdx
https://getbootstrap.com/docs/5.0/migration/#toasts-1
> Made default toast duration 5 seconds.
> feat(v5): Change Toast default delay to 5000

- .github/workflows/ci.yml
Fixes the following error
> Error: Calling brew cask install is disabled! Use brew install [--cask] instead.
> chore(ci): Fix brew cask install

- src/DropdownButton.tsx
- src/SplitButton.tsx
- tests/simple-types-test.tsx
Adds missing props from `Dropdown` for `SplitButton` and fixes `as` props for `DropdownButton`.
> fix: fix types for DropdownButton and SplitButton

- src/AbstractNavItem.tsx
- src/ListGroupItem.tsx
- test/ListGroupItemSpec.js
- test/NavSpec.js
Fixes a couple of accessibility issues:
- Prevents disabled list group items from being focused when tabbing.
- Allow inactive tab items to be focused when tabbing
Fixes #4737
> fix: Prevent focus on disabled nav items or list group items only

- www/src/examples/Form/FormTextInline.js
- www/src/examples/Form/ValidationFormik.js
- www/src/examples/Form/ValidationTooltips.js
- Fix #5585 
- Props `id` in `Form.Text` changed to `passwordHelpInline`.
- Fix #5574
- Added `terms: false` within the `initialValues` prop and set the schema to restrict the checkbox must be checked.
> Fix some bugs in example code in docs.

- src/InputGroup.tsx
- test/InputGroupSpec.js
- www/src/examples/Form/ValidationFormik.js
- www/src/examples/Form/ValidationInputGroup.js
- www/src/examples/Form/ValidationNative.js
- www/src/examples/Form/ValidationTooltips.js
- www/src/pages/components/forms.js
> To detect what elements need rounded corners inside an input group with validation, an input group requires an additional .has-validation class.
Ref: https://getbootstrap.com/docs/4.6/components/forms/#input-group-validation
> feat(InputGroup): Add hasValidation prop

- tests/simple-types-test.tsx
- www/src/examples/Carousel/IndividualIntervals.js
- www/src/examples/Carousel/Uncontrolled.js
Fixes #5627
1. The alt attribute in both the [first example (uncontrolled)](https://react-bootstrap.github.io/components/carousel/#example) and [Individual Item Intervals](https://react-bootstrap.github.io/components/carousel/#individual-item-intervals) of Carousel are wrong. I fixed both of them.
2. The same typo appears also in `tests/simple-types-test.tsx`. I am not sure if you prefer that to be also fixed, so I have fixed that with a seperate commit.
> docs: fix alt attribute of the second slide in examples of <Carousel>

- src/Overlay.tsx
- test/OverlayTriggerSpec.js
#5621 
How about this? The user will have to add the classes himself when he is using a function `overlay`
> show tooltips for func overlay without transition

- www/src/pages/components/overlays.js
Just a small typo fix I noticed while reading the docs.
> Spelling correction in overlay.js

- src/Collapse.tsx
- src/Fade.tsx
- src/transitionEndListener.ts
Fixes #5648 
Fixes #5641
Fixes #5230
This replaces the `addEndListener` with one that only invokes the callback only if transition occurs on the element containing the fade/collapse animation.  
Couldn't get tests to work here.  Parsing the transition-duration from the node results in a NaN.
> fix: Prevent transitionend events in children nodes from cutting off animations

- src/Carousel.tsx
- src/FormLabel.tsx
- src/PageItem.tsx
- src/ProgressBar.tsx
- src/SplitButton.tsx
- test/CarouselSpec.js
- test/FormLabelSpec.js
- test/ProgressBarSpec.js
- test/SplitButtonSpec.js
- tests/simple-types-test.tsx
- www/src/components/Announce.js
- www/src/components/ImportApi.js
- www/src/components/LinkToSource.js
- www/src/components/NavMain.js
- www/src/examples/Badge/Button.js
- www/src/examples/Form/GridAutoSizing.js
- www/src/examples/Form/GridAutoSizingColMix.js
- www/src/examples/Form/GridAutoSizingCustom.js
- www/src/examples/ProgressBar/ScreenreaderLabel.js
- www/src/examples/Spinner/Basic.js
- www/src/examples/Spinner/Buttons.js
- www/src/pages/components/alerts.mdx
- www/src/pages/components/list-group.mdx
- www/src/pages/components/progress.js
- www/src/pages/components/spinners.mdx
Replace sr-only with visually-hidden 
Rename srOnly prop to visuallyHidden
> feat(v5): replace screen reader classes

- src/DropdownMenu.tsx
This fixes a margin issue with dropdowns in Bootstrap 5.
Bootstrap uses a default offset of `[0, 2]` for Popper:
https://github.com/twbs/bootstrap/blob/5c32767e0e0dbac2d934bcdee03719a65d3f1187/js/src/dropdown.js#L75
Also looks like we don't need `usePopperMarginModifiers` anymore since upstream no longer uses margins in the styles.  The popper margin warning isn't there anymore.
> fix(DropdownMenu): use Bootstrap default offsets

- www/src/components/CssCodeBlock.js
Fixes #5678
Update the CSS CDN link to use jsdelivr, as Bootstrap's maxcdn link is giving AccessDenied errors.
> Change CSS CDN link to use jsdelivr

- www/src/examples/Overlays/ScheduleUpdate.js
Change `content` prop to `body` in an example.  Missed this in the PopoverBody refactor.
> docs(Popover): fix example

- src/ToastHeader.tsx
Upstream doesn't use margins for close button anymore
> fix(Toast): remove margins on close button

- src/Accordion.tsx
- src/AccordionBody.tsx
- src/AccordionButton.tsx
- src/AccordionCollapse.tsx
- src/AccordionHeader.tsx
- src/AccordionItem.tsx
- src/Button.tsx
- src/CardImg.tsx
- src/FormRange.tsx
- src/FormSelect.tsx
- src/Image.tsx
- src/InputGroup.tsx
- src/ModalHeader.tsx
- src/SplitButton.tsx
- src/Table.tsx
- src/ToastHeader.tsx
- src/helpers.ts
Simplify some types in helper.ts.  We don't need to re-declare `className` or `children` ourselves, since it's already handled in the base react props.
> refactor(types): simplify types

- src/Carousel.tsx
- src/transitionEndListener.ts
Fixes #5143
In the crossfade transition, the slide that switches out uses a transition delay which isn't accounted for in our `addEndListener` handler. This causes the slide to disappear prematurely, resulting in that flash.
Here's some links to compare the behavior between RB bugged/fixed carousel and upstream bootstrap's carousel:
Bootstrap 4.6:
https://getbootstrap.com/docs/4.6/components/carousel/#crossfade
RB before fix:
https://react-bootstrap.netlify.app/components/carousel/#crossfade
RB after fix:
https://deploy-preview-5671--react-bootstrap.netlify.app/components/carousel/#crossfade
> fix(Carousel): fix crossfade animation

- package.json
Let's see if this resolves all those timeout issues in ci when installing deps
> chore(ci): add yarn timeout to prevent install errors

- src/AbstractNav.tsx
- src/AbstractNavItem.tsx
- src/DropdownItem.tsx
- src/DropdownToggle.tsx
- src/ListGroup.tsx
- src/ListGroupItem.tsx
- src/Nav.tsx
- src/NavContext.tsx
- src/NavLink.tsx
- src/SelectableContext.tsx
- src/Tab.tsx
- src/TabContainer.tsx
- src/TabPane.tsx
- src/Tabs.tsx
- src/types.tsx
This fixes a number of type inconsistencies surrounding event keys.  The types were changed to allow string and number only.
> fix(types): fix types for event key

- src/Modal.tsx
- test/ModalSpec.js
I think this is a good time to remove `ref._modal`? 
Should we merge/pass the ref along to `BaseModal`?
> refactor(Modal): forward ref to react-overlays Modal

- src/AbstractModalHeader.tsx
- src/Offcanvas.tsx
- src/OffcanvasBody.tsx
- src/OffcanvasHeader.tsx
- src/OffcanvasTitle.tsx
- src/OffcanvasToggling.tsx
- src/index.tsx
- test/OffcanvasSpec.js
- www/src/components/SideNav.js
- www/src/examples/Offcanvas/Backdrop.js
- www/src/examples/Offcanvas/Basic.js
- www/src/examples/Offcanvas/Placement.js
- www/src/pages/components/offcanvas.mdx
https://getbootstrap.com/docs/5.0/components/offcanvas/
Offcanvas is a simpler version of Modal, so ended up using Modal as a base and removed the unneeded pieces.  I also moved code from `ModalHeader` into `AbstractModalHeader` so both `ModalHeader` and `OffcanvasHeader` can share it.  They only differ by a `bsPrefix`.
I used a root close handler in here to handle the case where there isn't a backdrop.
Preview: https://deploy-preview-5738--react-bootstrap-v5.netlify.app/components/offcanvas/
> feat(v5): add Offcanvas component

- www/src/examples/Toast/Placement.js
* The issue revolved around the short text of inside the `Toast.Body`.
* To maintain the uniformity in the code examples, `mr-auto` has been used on the Brand (Bootstrap) so that it aligns to left always. Possibly, doing something like `mr-2` would have added spacing and solved the issue but it would be exclusive hack for this code example only. 
* So better workaround I found was to change text inside the Toast. Longer text would increase the overall `width` of the div and so this works.
* Maybe adding `width` property might have served the similar solution; but found changing text a simpler and intuitive way.
Please let me know your views upon this PR. Would be active in responding to review comments. Thanks :)
> Update Toast Documentation to fix #5742

- src/AbstractNavItem.tsx
- src/DropdownItem.tsx
- src/DropdownToggle.tsx
- src/ListGroup.tsx
- src/ListGroupItem.tsx
- src/Nav.tsx
- src/NavLink.tsx
- src/SelectableContext.tsx
- src/Tab.tsx
- src/TabContainer.tsx
- src/TabPane.tsx
- src/Tabs.tsx
- src/types.tsx
chore(types) : Backported EventKey type changes from commit [6260997] to the BS4 master branch for issue #5739
I aimed to have the changes be as similar as possible to those in the BS5 commit referenced.
> chore(types) : Backported EventKey type changes from commit 6260997

- CONTRIBUTING.md
Hello! First time contributor here. As I was reading the contributor docs, I had questions about where the Component API docs were being auto generated and with what technologies. So I thought I would provide more information in that section for other newcomers. Let me know if I can do anything to improve these changes or if you need to reject my request for any reason. Thanks!
> docs(contributing): expand Documentation section and add links

- src/usePopperMarginModifiers.tsx
- yarn.lock
Fixes #5769
Popper starting from 2.84 no longer uses `state.modifiersData['arrow#persistent']` for the arrow padding.  This was changed in https://github.com/popperjs/popper-core/pull/1255.
We need to pass the padding through our own arrow modifier now.
> fix(Popover): fix arrow alignment when running Popper >= 2.84

- src/Tabs.tsx
- test/TabsSpec.js
Changes tabs to use the recommended markup in upstream bootstrap.
Also fixes #5530
Ref: 
https://github.com/twbs/bootstrap/pull/32630
https://getbootstrap.com/docs/5.0/components/navs-tabs/#javascript-behavior
> refactor(Tabs): use buttons instead of anchors

- src/Dropdown.tsx
- src/DropdownButton.tsx
- src/DropdownContext.ts
- src/DropdownMenu.tsx
- src/SplitButton.tsx
- src/types.tsx
- test/DropdownButtonSpec.js
- test/DropdownMenuSpec.js
- test/DropdownSpec.js
- tests/simple-types-test.tsx
- www/src/examples/Dropdown/MenuAlignResponsive.js
- www/src/examples/Dropdown/MenuAlignRight.js
- www/src/examples/InputGroup/ButtonDropdowns.js
- www/src/pages/components/dropdowns.mdx
- www/src/pages/migrating.mdx
This PR simplifies the menu alignment API by consolidating `alignRight` and `menuAlign` props into a single `align` prop that's exposed on the Dropdown and DropdownMenu components.
A couple breaking changes in here:
1. Remove `alignRight` from Dropdown and DropdownMenu
2. Remove `menuAlign` from DropdownButton and SplitButton
Also fixed a couple of things I noticed while refactoring:
1. Added support for XXL breakpoint for responsive menu alignment
2. Fix broken responsive alignment by adding `data-bs-popper` to the DropdownMenu.  Bootstrap now uses this attribute in their css to do the alignment
> refactor(Dropdown)!: simplify menu alignment API

- www/gatsby-config.js
- www/package.json
- www/yarn.lock
Fixes this error in Netlify deployment:
> node: ../src/coroutine.cc:134: void* find_thread_id_key(void*): Assertion `thread_id_key != 0x7777' failed.
Aborted (core dumped)
Netlify uses node v16 now which isn't compatible with `fibers`
Ref: https://github.com/laverdet/node-fibers/issues/451
> docs: fix Netlify deployment

- src/DropdownMenu.tsx
In the earlier version, only dark variant was available by adding type string developer will have more control of dropdown variant.
> Add custom variant support for Dropdown.Menu Component.

- src/Dropdown.tsx
- src/DropdownMenu.tsx
- src/DropdownToggle.tsx
- src/InputGroup.tsx
- src/InputGroupContext.tsx
- test/DropdownSpec.js
- www/src/examples/InputGroup/SegmentedButtonDropdowns.js
- www/src/pages/components/input-group.js
Follow-up to #5351.  This fixes the incorrect HTML being rendered.
When dropdowns are inside input groups there are a few differences in the markup.
1. There is no wrapping `.dropdown` element
2. The `.show` class is on the button toggle
3. Dropdown menus must always be rendered because the css uses `nth-last-child` to remove the inner border radius
This approach uses a context to determine if we're inside an input group.  Also added a segmented button example.
> fix(Dropdown): fix HTML structure when inside InputGroup

- src/Offcanvas.tsx
- test/OffcanvasSpec.js
Bootstrap renamed the `.offcanvas-backdrop` class to `.modal-backdrop` and applied a fade animation in v5 stable.
> fix(Offcanvas): fix backdrop class

- www/src/components/ReactPlayground.js
On the toast component page of the documentation, an img element was not rendered when using an animated toast.
The problem was caused by the holder.js not been activated for loading the src of img elements, when the toast component was re-rendered.
In order to solve this issue, we implemented a mutation observer API.
> Fix(docs): fix missing img on toast (fix #5729)

- src/Modal.tsx
- test/ModalSpec.js
This PR addresses issue: #5788 
When setting a transition that is longer than the default `300ms` timeout as set by the `Fade` component's default props, the Modal is unmounted on exit before completing the animation. By setting the `timeout=null` for the Fade component, we let the Transition complete fully through the `transitionEndListener`.
> Update Modal's dialog and backdrop transition timeout

- src/FormLabel.tsx
- test/FormLabelSpec.js
When the `<Form.Label>` component is rendered with the prop `column={true}`, it doesn't forward refs. (It does forward them correctly otherwise.)
> Perform ref forwarding in Form.Label when rendering as a Col

- test/OverlayTriggerSpec.js
The existing coverage is 67% [here](https://codecov.io/gh/react-bootstrap/react-bootstrap/src/master/src/OverlayTrigger.tsx), this branch brings it up to 87% based on my local test runner's report:
> test: adds tests for mouseover trigger and uses fake timers

- src/Toast.tsx
- test/ToastSpec.js
- www/src/examples/Toast/Contextual.js
- www/src/pages/components/toasts.mdx
Resolves: #5825 
Pretty self-explanatory 😄 Adds a `bg` property to `Toast`, along with the examples.
> Add `bg` property to `Toast` component

- src/FormRange.tsx
- src/FormSelect.tsx
- test/FormRangeSpec.js
- test/FormSelectSpec.js
Resolves: #5864 
Fixes the bug described in the ticket, and applies the same `controlId` behavior to `<FormRange />` as specified in comment by @kyletsang
> fix(form): fixed controlId override behavior on FormRange and FormSelect

- src/Dropdown.tsx
- test/DropdownSpec.js
- www/src/examples/Dropdown/AutoClose.js
- www/src/pages/components/dropdowns.mdx
More about the autoClose behaviour [here](https://getbootstrap.com/docs/5.0/components/dropdowns/#auto-close-behavior).
Additionally to the implementation, I've added
- a playground example
- a documentation section
- unit-tests
Preview: https://deploy-preview-5873--react-bootstrap.netlify.app/
> Added autoClose behaviour for dropdowns

- www/src/examples/Button/ToggleButtonGroupControlled.js
Closes #5896 
Fix toggle button group example in the docs by using id for each toggle button
[https://react-bootstrap-v5.netlify.app/components/buttons/#controlled](url)
> Fix toggle button controlled example by using id for each toggle button

- .eslintrc
- README.md
- www/src/components/NavMain.js
Updates the links to the new v4 site.
Also disabled a couple rules in eslint since we're using the new jsx transform.
> docs: update links for new v4 site

- src/BootstrapModalManager.tsx
- src/Modal.tsx
- src/Offcanvas.tsx
- src/helpers.ts
- test/ModalSpec.js
- test/OffcanvasSpec.js
- www/src/examples/Offcanvas/Backdrop.js
Fixes #5905
This fix uses a shared `ModalManager` between `Offcanvas` and `Modal` in order to sync the container state in the scenario where you can trigger the closing/opening of both `Offcanvas` and `Modal` at the same time.  In the case where the `Offcanvas` has the `scroll` prop set to true, we use a local `ModalManager` because the shared one handles overflow styles.  I think this should be ok since we don't need to modify the container styles when scroll is true.
This also fixes some differences in behavior compared to upstream bootstrap where enforce focus should not be enabled when `scroll` is enabled for `Offcanvas`.  The user should be able to select text, or focus outside. In addition, clicking outside `Offcanvas` should not close the `Offcanvas` when `backdrop` is false: …
> fix: use shared modal manager to sync container state

- src/Modal.tsx
- tests/simple-types-test.tsx
Fixes #5934
Types from base modal only expects one child, so we should omit it from RB's modal types.
> fix(Modal): fix children typing

- www/src/pages/getting-started/introduction.mdx
Added @next to have compatible versions of react-bootstrap and bootstrap in the docs.
Fixes #5937 .
> Add @next to installation instructions

- src/Alert.tsx
- src/Badge.tsx
- test/AlertSpec.js
- test/BadgeSpec.js
This sets a default variant of "primary" for Alert and Badge, allowing them to be used without having to set a variant.  Bootstrap's docs on Alerts/Badges require the use of a contextual class (https://getbootstrap.com/docs/4.5/components/alerts/) in order to have proper styling.
This aligns Alert and Badge variant functionality with that of Button and Navbar, where default variants are provided and can be used like `<Button>Hello</Button>`.
This could be viewed as a breaking change (e.g. for someone using Alert without a variant as it now adds one).  However, it could be viewed as a feature as it is adding & declaring functionality in the public API where behaviour wasn't previously explicitly defined in examples or docs.
> feat: add default variant to Alert and Badge

- src/Fade.tsx
- src/Toast.tsx
- src/ToastFade.tsx
- www/src/examples/Toast/Dismissible.js
Fixes #5998
Bootstrap changed the classes used for the fade animation in toasts.  The opacity is now set in a class called `showing`.  
https://github.com/twbs/bootstrap/blob/d9254c64fa10f465a671a47ce40779807f092f5a/scss/_toasts.scss#L13-L19
Unfortunately I couldn't make it work with the existing `Fade` component since the classes in each transition phase are not compatible with each other. The fade animation for toasts are now in a component called `ToastFade`
> fix(Toast): fix fade animation

- src/usePopperMarginModifiers.tsx
`fn` is mandatory for custom modifiers but it may return `undefined` as stated in [popper.js docs](https://popper.js.org/docs/v2/modifiers/#example-modifier).
fixes "Popper: modifier "popoverArrowMargins" provided an invalid "fn" property, expected "function" but got "undefined"" #6017
> fix: avoid @popperjs/core console warning

- src/Feedback.tsx
- src/FormCheck.tsx
- test/FormCheckSpec.js
- www/src/examples/Form/ValidationFormik.js
- www/src/examples/Form/ValidationNative.js
- www/src/examples/Form/ValidationTooltips.js
- www/src/pages/migrating.mdx
BREAKING CHANGE: FormCheck feedback type is now controlled by `feedbackType` instead of `isValid` and `isInvalid`.
Fixes #3939
Using `isInvalid` and `isValid` didn't really work anyway, so this new prop is more clear on what it does.
> fix(FormCheck)!: use feedbackType to control feedback type

- src/SSRProvider.ts
- src/index.tsx
- www/src/components/SideNav.js
- www/src/pages/getting-started/server-side-rendering.mdx
Re-exports `SSRProvider` from @restart/ui and adds SSR docs
Closes #6026
> feat: add SSRProvider

- src/Col.tsx
- www/src/components/PropTable.js
- www/src/components/ReactPlayground.js
- www/src/css/CopyButton.module.css
- www/src/examples/Overlays/PopoverContained.js
Closes #6025
Address example in #6009
Also fixes some styling in react code editor for the copy button and the required tag in props table
> docs: fix examples and editor layout

- src/Stack.tsx
- src/createUtilityClasses.ts
- src/index.tsx
- src/types.tsx
- test/StackSpec.tsx
- test/createUtilityClassesSpec.ts
- tests/simple-types-test.tsx
- www/src/components/SideNav.js
- www/src/examples/Stack/Buttons.js
- www/src/examples/Stack/Form.js
- www/src/examples/Stack/Horizontal.js
- www/src/examples/Stack/HorizontalMarginStart.js
- www/src/examples/Stack/HorizontalVerticalRules.js
- www/src/examples/Stack/Vertical.js
- www/src/pages/layout/stack.mdx
https://getbootstrap.com/docs/5.1/helpers/stacks/
Adds a stack component where you can specify if the elements stack horizontally or vertically.  There's only one util class prop `gap` for now, but we can easily add more as we go.
I think the `createUtilityClasses` function could be useful in generating classes for responsive utility class props.
> feat: add Stack component

- src/Col.tsx
- www/src/pages/migrating.mdx
BREAKING CHANGE: When using objects in breakpoint props, `span` is no longer `true` by default
As discussed in #5205, removing `true` because it seemed wrong as a default value.
> refactor(Col)!: remove default span value in breakpoint object

- src/Navbar.tsx
- src/NavbarOffcanvas.tsx
- src/Offcanvas.tsx
- test/NavbarOffcanvasSpec.tsx
- www/src/examples/Navbar/NavScroll.js
- www/src/examples/Navbar/Offcanvas.js
- www/src/pages/components/navbar.js
Ref: https://getbootstrap.com/docs/5.1/components/navbar/#offcanvas
Adds component and related docs.
Also fixes the navbar scroll example for bootstrap 5 by adding missing container
Preview: https://deploy-preview-5999--react-bootstrap.netlify.app/components/navbar/#navbar-offcanvas
> feat: add NavbarOffcanvas component

- src/Toast.tsx
correct the type signator for the Toast component onClose property
fixes #5726
> fix(Toast): add optional event arg to Toast onClose

- www/src/examples/Table/Basic.js
- www/src/examples/Table/Dark.js
- www/src/examples/Table/Small.js
This PR updates the `colSpan` attribute in [Table](https://react-bootstrap.netlify.app/components/table/#tables) in the React-Bootstrap documentation. This attribute must be an integer and not a string (which it currently is). Having it as a string throws an error with ReactJS with Typescript enabled.
> Update colSpan in Table documentation

- package.json
- yarn.lock
Closes #6155
Deleted `@restart/context` from main package.json because it was only being used in the docs
> chore: update/clean up @restart packages

- src/Overlay.tsx
Fixes #6173. What was happening is that `placement` prop was being passed to `BaseOverlay` and then passed  to the `overlay` prop, ignoring popper object, which in turn resulted in hard-coded the `placement` property
> fix: prioritize poppers position prop in overlaytrigger

- src/Button.tsx
- src/ToggleButton.tsx
- test/ToggleButtonGroupSpec.tsx
- test/ToggleButtonSpec.tsx
Fixes #6198
Also moved the ToggleButton tests into its own file
> fix(ToggleButton): remove `role="button"` from label

- www/src/components/NavMain.js
> fix(Docs): increase the z-index of the header of the docs page, so that tooltips do not hover it.

- src/Nav.tsx
PR that Closes #6141 
Updates the "navs" docs prop table to include entry for 'defaultActiveKey' via TSDoc comments.
> docs: add defaultActiveKey propType to Nav

- src/Col.tsx
- src/Container.tsx
- src/ListGroup.tsx
- src/Modal.tsx
- src/ModalDialog.tsx
- src/Navbar.tsx
- src/Row.tsx
- src/Stack.tsx
- src/ThemeProvider.tsx
- src/createUtilityClasses.ts
- src/types.tsx
- test/ColSpec.tsx
- test/ContainerSpec.tsx
- test/DropdownMenuSpec.tsx
- test/ListGroupSpec.tsx
- test/ModalSpec.tsx
- test/NavbarSpec.tsx
- test/RowSpec.tsx
- test/createUtilityClassesSpec.ts
- tests/simple-types-test.tsx
- www/src/components/BreakpointTable.js
- www/src/components/SideNav.js
- www/src/examples/CustomBreakpoints.js
- www/src/pages/layout/breakpoints.mdx
Closes #6247
Loosens the types for any breakpoint-related prop so it takes in any string.  For the components that use a hard coded breakpoint list, I've allowed the user to specify their own list of breakpoints in the ThemeProvider so these components can take advantage of it.
Haven't added docs yet.  Wanted to make sure the approach looks good before doing so.
> feat: support custom breakpoints

- src/Carousel.tsx
- test/CarouselSpec.tsx
Issue was brought up in #6263
If you set the slides and then change the `activeIndex`, it will result in the carousel locking up because `isSliding` is set to true and RTG's `onEntered` isn't triggered to reset this.  
Minimal repro:
https://codesandbox.io/s/react-bootstrap-carousel-active-index-forked-xht0f1?file=/src/App.js
Issue appears to be fixed by moving some of the code that handles the rendered active index into a `useEffect` hook.  
Note, I had to tweak the delays of 1 test because the timers seem to be triggering too fast when testing.
> fix(Carousel): fix issue where changing `activeIndex` won't work

- src/Overlay.tsx
- src/useOverlayOffset.tsx
- test/useOverlayOffsetSpec.tsx
Fixes: https://github.com/react-bootstrap/react-bootstrap/issues/6250
`useOverlayOffset` was overriding user-defined `offset` prop. This passes the value explicitly to the helper hook
> fix(useOverlayOffset): use offset prop in useOverlayOffset

- www/src/components/PropTable.js
A fix for this issue: https://github.com/react-bootstrap/react-bootstrap/issues/6270
capitalize downcases all letters but uppercases the first. Upperfirst, uppercases the first letter but leaves all others unchanged.
> replace lodash capitalize with upperFirst in PropTable -fixing issue Docs typo at react-bootstrap #6270

- src/DropdownMenu.tsx
Resolves #6280
Removes `onSelect` prop in `Dropdown.Menu`
> chore(DropdownMenu): remove old onSelect function

- src/Modal.tsx
- test/ModalSpec.tsx
`aria-describedby` should be rendered on the element with the `role="dialog"`
> fix(Modal): render aria-describedby on the top level modal element

- www/src/pages/getting-started/introduction.mdx
npm package bootstrap has 5 tags
latest
latest-5
latest-4
latest-3
latest
The latest tag points to 5.1.3
so there is no need to specify bootstrap's version in the installation command
Expected command: `npm install react-bootstrap bootstrap`
> no need to specify version in npm install command installation docs, react-bootstrap's latest tag is 5.1.3

- package.json
- yarn.lock
Moves `@types/react` into peer deps.  This should be safe for npm 7 users when resolving peer dependencies because of the optional field in `peerDependenciesMeta`.  All users using TS would've installed a version of `@types/react` anyway, so we shouldn't have problems here.
For `invariant`, `prop-types`, and `warning`, those can be safely moved into devDeps because their types aren't exposed on the public d.ts files.  They are just used internally within the implementation.
> fix(deps): clean up @types deps list

- src/Navbar.tsx
- src/NavbarContext.tsx
- src/NavbarOffcanvas.tsx
- test/NavbarOffcanvasSpec.tsx
- www/src/examples/Navbar/Offcanvas.js
Fixes #6309
When the navbar hits the expand breakpoint, it will render the children into a div instead of using the Offcanvas component to do it.  We don't need the functionality when the nav items are shown this way anyway.  One thing that needs to be done is to add a default breakpoint size for xxl in @restart/hooks.
I think this approach should be ok?  Will add tests later after review.
> fix(NavbarOffcanvas): fix rendering of nav items when expand is used

- src/ToastContainer.tsx
- test/ToastContainerSpec.tsx
Fixes #6315.
I am unsure whether we should strictly limit the containerPosition values to [position-* utility classes](https://getbootstrap.com/docs/5.1/utilities/position/) or allow any string, because it is possible to customize the utility classes.
> Add containerPosition prop for ToastContainer

- src/ToggleButtonGroup.tsx
This const variable is already checked on line 95, so must be truthy here as well.
This bug was accidently detected by TypeScript 4.7-RC
> Remove extra `onChange` check

- src/Overlay.tsx
- src/Popover.tsx
- src/Tooltip.tsx
- src/types.tsx
Fixes #6343
Tooltips and popovers no longer have `position: absolute` so popper's initial calculation is incorrect.  @jquense has a good explanation of that here: https://github.com/react-restart/ui/pull/36#issuecomment-933680079
This PR uses the `onFirstUpdate` callback to listen for the initial positioning of the popper, then forces an update to put it in the correct position.
> fix(Overlay): fix initial positioning of overlays

- src/FormCheck.tsx
- test/FormCheckSpec.tsx
- www/src/examples/Form/CheckReverse.js
- www/src/pages/forms/checks-radios.mdx
Added support for reverse prop in Checks and Radios as per v5.2
https://getbootstrap.com/docs/5.2/forms/checks-radios/#reverse
> feat(FormCheck): add support for reverse checks and radios

- src/NavbarOffcanvas.tsx
Fixes #6359
Simplifies the render so it doesn't rely on the `useBreakpoint` hook which isn't SSR safe.  Should be safe to always render the offcanvas component since it only attaches to the dom when `show=true`
> fix(NavbarOffcanvas): fix render to be SSR safe

- src/ModalDialog.tsx
Currently looks the following:
> docs: typo in `ModalDialog.size` prop type

- src/NavbarOffcanvas.tsx
- src/Offcanvas.tsx
- test/OffcanvasSpec.tsx
- www/src/examples/Offcanvas/Responsive.js
- www/src/pages/components/offcanvas.mdx
Closes #6357
Adds a `responsive` prop to Offcanvas. Pulled the logic from NavbarOffcanvas into Offcanvas because it was needed for rendering the responsive offcanvas when it's not shown via flyout.
Ref: https://getbootstrap.com/docs/5.2/components/offcanvas/#responsive
> feat(Offcanvas): add responsive support

- src/Offcanvas.tsx
Fixes #6379
Uses a breakpoint hook and updates the show state in an effect so it's SSR safe.  Tested via visual tests.
> fix(Offcanvas): fix responsive behavior when resizing screen

- src/Dropdown.tsx
- src/DropdownButton.tsx
- src/SplitButton.tsx
Closes #3589
Adds `flip` prop to `SplitButton` and `DropdownButton`.  Removes `flip` prop from `Dropdown`.
> Dropdown flip changes

- src/Tabs.tsx
- test/TabsSpec.tsx
- www/src/examples/Tabs/Fill.js
- www/src/examples/Tabs/Justified.js
- www/src/pages/components/tabs.mdx
Allows the `fill` and `justify` props to be passed to `<Tabs>`
resolves: #6382
> feat(types): Allow fill and justify settings for tabs

- www/src/examples/Tabs/LeftTabs.js
Closes #6393
Fixes keyboard behavior by adding `href="#"` to the anchors
> docs: fix custom tabs example

- src/OverlayTrigger.tsx
Regarding this issue: https://github.com/react-bootstrap/react-bootstrap/issues/6288
Added a note to the documentation for `OverlayTrigger` that the `click` trigger ignores the `delay` to avoid this confusion.
> Added a note in the documentation for OverlayTrigger

- www/src/examples/Carousel/NoTransition.js
- www/src/pages/components/carousel.mdx
Ref: #6266 
Adds a `No animation transition` carousel example to the docs.
> docs: adds Carousel no transition example

- src/CardImg.tsx
- src/Carousel.tsx
- src/CloseButton.tsx
- src/ListGroup.tsx
- src/Nav.tsx
- src/Navbar.tsx
This PR follows on from https://github.com/react-bootstrap/react-bootstrap/issues/4461 and aims to ensure consistency when using custom variants across react bootstrap. Currently a number of components do not properly support custom variants in the way the issue was resolved as not everything uses Variant as a base. (Such as Navbar). 
Given this looks to be the agreed upon approach for custom variants all `variant` attributes might need a type of "| string" adding
By adding "| string" to the remaining typedefs where variant is still using a Union of hardcoded values. This should not cause any bc breaks as it is extending hardcoded unions of strings.
Thanks for looking at this!
> Ensure Consistent API for custom variants

- src/NavbarOffcanvas.tsx
- src/Offcanvas.tsx
- test/OffcanvasSpec.tsx
Fixes #6411
This is a bit of a hack to revert the regular offcanvas back to 2.4 behavior.  
We should fix the behavior so that it follows upstream bootstrap:
- Do not unmount when not shown (Needs a new prop in `@restart/ui` `Modal`)
- Do no render at body level
> fix(Offcanvas): fix children mounting 2x on show when not responsive

- src/Accordion.tsx
- src/AccordionCollapse.tsx
Addresses missing parts of docs from #6400
> docs: add missing Accordion and AccordionCollapse props

- www/src/pages/layout/grid.mdx
> docs: fix typo in grid.mdx

- www/src/examples/AsPropAccordion.js
- www/src/examples/AsPropComponent.js
- www/src/pages/getting-started/introduction.mdx
This is the pull request for Issue  #6430 
Please review the changes and let me know if any other modifications are necessary.
> Docs: Added Example For React Bootstrap Component in As Prop API

- src/Modal.tsx
resolves: #6439
Applies `show` class to Modal when `animation={false}`. [Backdrop has the exact same logic](https://github.com/react-bootstrap/react-bootstrap/blob/9ba8c7c341c249b342099685768d7001d5e10b76/src/Modal.tsx#L439) so this should be safe.
> fix(Modal): apply 'show' class when animation = false

- www/src/components/BrowserGlobalsCodeBlock.js
- www/src/pages/getting-started/introduction.mdx
The current docs endorse `unpkg` as the CDN of choice for developers to use. However, that project is currently unmaintained and [full of issues](https://github.com/mjackson/unpkg/issues).
Full disclosure that I work at [jsDelivr](www.jsdelivr.com), but I think it would be awesome if you React Bootstrap considers endorsing it! It's been actively maintained for the past 10 years and uses a [multi-CDN fallback system](https://www.jsdelivr.com/network/infographic) to prevent any downtime from occurring regardless of provider outages.
Happy to answer any questions or concerns you may have!
> docs: switch cdn to jsDelivr

- src/PageItem.tsx
- src/Pagination.tsx
Fix typo in the pagination api documentation and add missing href description in the page item
> docs: fix typos in the pagination and pageitem docs

- src/PageItem.tsx
- test/PageItemSpec.tsx
Part of #6415.  The span shouldn't have the disabled attribute on it.
> fix(PageItem): remove disabled attribute on span

- src/CloseButton.tsx
I noticed that the api docs had the onclick and aria-label fields missing, so I added it in.
> docs: add docs to close button

- src/ListGroupItem.tsx
- src/Navbar.tsx
- test/FormRangeSpec.tsx
- test/FormSelectSpec.tsx
- test/PaginationSpec.tsx
- tests/simple-types-test.tsx
- www/src/pages/components/button-group.mdx
- www/src/pages/components/navs.mdx
- www/src/pages/components/offcanvas.mdx
- www/src/pages/components/overlays.mdx
- www/src/pages/components/placeholder.mdx
- www/src/pages/forms/range.mdx
- www/src/pages/getting-started/why-react-bootstrap.mdx
- www/src/pages/migrating.mdx
- Fix typos in MDX and some codes.
- Remove unnecessary semicolons and blank lines. This PR removes extra semicolons appearing in docs.
> docs: Fix typos, remove unnecessary semicolons and blank lines

- src/ListGroupItem.tsx
I noticed that the onClick and href is missing for the ListGroupItem api, so I added it in this PR.
> docs: add onclick and href docs to listgroupitem

- src/OverlayTrigger.tsx
- src/TransitionWrapper.tsx
- src/safeFindDOMNode.ts
Based on its body, `safeFindDOMNode` appears to have an incorrect function signature (and TypeScript 4.9 complains about it as a result). The declared type of `React.ComponentClass` refers to *the thing you `new`*, whereas `React.Component` refers to the instance of the class. `setState` is an instance method, not a static method, so will (presumably) never be `in` the former.
> fix(types): Fix type of 'safeFindDOMNode' function

- src/ListGroupItem.tsx
- test/ListGroupItemSpec.tsx
While adding the docs in #6461 , I realize that if `action=false` and `href` is set, a `<div href="...">` is generated.  I think the `href` attribute should only be for the `<a>` tag or custom component if the `as` is specified.
> fix(ListGroupItem): prevent a div with a href

- src/Spinner.tsx
There's no good reason to always type out the animation for the spinner. There are only two choices, and the "border" option is the obvious choice as a default.
This should be a non-breaking change.
> make the spinner animation default to border

- package.json
- yarn.lock
Fixes a TypeScript 4.8 error applications using react-bootstrap may have encountered with usePopper's typing through the transitive dependency: https://github.com/react-restart/ui/issues/65
> fix: update @restart/ui to 1.4.0

- src/Dropdown.tsx
- src/DropdownContext.ts
- src/DropdownMenu.tsx
- test/DropdownMenuSpec.tsx
- test/DropdownSpec.tsx
- www/src/examples/Dropdown/DropDirections.js
Closes #6477
I thought about putting a new option `center` in the `align` prop as that seems more intuitive, but it might get confusing because upstream bootstrap doesn't have support for responsive menu centering.  These classes are also placed on the `Dropdown` component instead of the `DropdownMenu` where the `align` prop is shared...
> feat(Dropdown): add support for centered dropdown menus

- www/src/examples/Badge/Variations.js
- Fix inconsistent code style for "Contextual variations" example. "Pill" is taken as a reference of code style.
<details>
<summary>Current view (screenshot)</summary>
</details>
> docs: Fix consistent code style in Badge examples

- www/src/examples/Modal/Static.js
Fixes #6491
Some of the styles are defined as css variables in `.modal`, so had to add a wrapper with that and change the position from `sticky` to `initial`
> docs(Modal): fix static example

- src/Ratio.tsx
- test/RatioSpec.tsx
Regarding this issue: https://github.com/react-bootstrap/react-bootstrap/issues/6495, suggesting allowing ratios above 100% of the width to allow for portrait style presentation. 
Currently, in the `toPercent()` function, any number above 1 converts to a percent, ensuring that width is always greater than or equal to height. Perhaps, for small numbers above 1 we could infer that the developer wants a portrait style layout. I've suggested 5 somewhat arbitrarily, but it seems absurdly small for a percent height/width ratio so seems safe to me. Suggestions?
> Added support for portrait size ratios

- src/AccordionBody.tsx
- test/AccordionSpec.tsx
Replaces #6407
Forwards transition callbacks on `AccordionBody` to the underlying `AccordionCollapse`
> feat(AccordionBody): add transition callback props

- src/Modal.tsx
- test/ModalSpec.tsx
> fix(Modal): fix modal not closing when keyboard=false

- src/Stack.tsx
Breakpoint params were placed in the wrong spot.  They shouldn't be inside the utility values map.
> fix(Stack): fix incorrect classes being generated

- src/Overlay.tsx
- src/Popover.tsx
- src/Tooltip.tsx
- src/getInitialPopperStyles.ts
- src/types.tsx
- test/getInitialPopperStylesSpec.ts
- www/src/examples/Overlays/Overlay.js
- www/src/pages/components/overlays.mdx
Fixes #6314
Fixes #5270
@jquense this implements what we discussed back then in https://github.com/react-restart/ui/pull/36
I'll add docs for users with custom overlays later, but you can take a look to see if there's any obvious errors with this code.
> fix(Overlay): fix initial render of tooltips and popovers

- www/src/pages/forms/form-text.mdx
I have made the required changes to the documentation. Any alternative choice of words for the changed documentation is appreciated and welcomed.
> docs (Form Text): fixed docs with incorrect documentation.

- src/ToastContainer.tsx
- test/ToastContainerSpec.tsx
Fixes #6552
Allows setting `containerPosition` without needing to specify the `position` prop.  Bootstrap added the `position: absolute` at some point to `.toast-container`, so we don't need to apply the `containerPosition` default value automatically anymore.
> fix(ToastContainer): apply `containerPosition` without `position`

- www/src/theme/Playground/EditorInfoMessage.tsx
- www/src/theme/Playground/index.tsx
- www/src/theme/Playground/styles.module.css
Brings back the copy button (styled like the other codeblocks) and fixes the tabbing behavior for live code like it was in the old docs.
> docs: fix playground tabbing and add copy button

- src/Tooltip.tsx
- src/useOverlayOffset.tsx
- test/useOverlayOffsetSpec.tsx
5.3 introduces similar styling to popovers that throws off the positioning.  We need to apply the same fix we did for popovers to tooltips.
> fix(Tooltip): fix offset

- src/Nav.tsx
- src/Tabs.tsx
- www/docs/components/tabs.mdx
- www/docs/examples/Tabs/Underline.js
The underline variant that appeared with version 5.3 has been added to the Tabs and Nav component.
https://getbootstrap.com/docs/5.3/components/navs-tabs/#underline
> feat: new variant added for tabs

- www/docs/getting-started/color-modes.mdx
This fixes #6637 
There's a simple problem in the docs as mentioned in issue #6637, the passed path to ``<DocLink>`` was missing a slash, in the beginning, to direct to the right page.
Thanks.
``PART OF GTC OPEN SOURCE INTIATIVE``
> Fix (broken color modes link: Bug)

- src/PageItem.tsx
- test/PageItemSpec.tsx
This fixes #5950 
When using Bootstrap Pagination, There is an incomplete API to allow adding custom styles to the ``<Component>`` inside the ``<PageItem>``. there is no className or style prop that is passed to the <Component> to allow for custom styles to be applied, so The developer can't change the color of the ``<a>``  tag inside of the ``<PageItem>`` for example!
I have solved the issue by creating a new two props ( innerStyle and innerClassName ), they are passed to the ``<Component>`` inside of ``<PageItem>``
Thanks.
PART OF GTC OPEN SOURCE INTIATIVE
> Fix(Unable to add custom styles to PageItem Component)

- .babelrc.js
Closes #6475 
Enables the plugin to add `use client` into all of the components.
Found some issues though:
**1. Cannot use a component that has been created with `createWithBsPrefix`.  For example: `CardGroup`**
```
Error: Attempted to call the default export of createWithBsPrefix.js from the server but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.
```
**Potential solution:**
We would need to stop using this function to create components.
**2. Cannot use a component that's been set as a property. For example `Accordion.Body`**
```
Error: Unsupported Server Component type: undefined
at stringify (<anonymous>)
```
**Potential solution:**
Users would have to import the …
> feat: add initial RSC support

- src/ToggleButton.tsx
Prop `id` is required in `ToggleButton`, but wasn't required in interface `ToggleButtonProps`. Also fixed a typo.
> fixed "id" not required in ToggleButton props

- src/Overlay.tsx
Fixes #6619
Need to run the popper update once the target element resolves so that it's positioned properly with `defaultShow=true`
> fix(OverlayTrigger): position overlay properly when defaultShow set

- src/DropdownItem.tsx
Fixes #6651
Simplifies `BsPrefixRefForwardingComponent<typeof BaseDropdownItem, DropdownItemProps>` to `BsPrefixRefForwardingComponent<'a', DropdownItemProps>`
The `typeof BaseDropdownItem` compiles into an import from `@restart/ui/esm/...` but that isn't exposed in the package.json exports.  I'm not sure how to fix the import path, so this small fix will do for now.
> fix(DropdownItem): simplify component type

- src/FormControl.tsx
- test/FormControlSpec.tsx
Currently, when passing `plaintext` alongside with `size` prop, the relevant size class is not set in the input.
> fix(FormControl): add size support when using plaintext

- www/docs/examples/Navbar/Collapsible.js
Minor spelling error for the example component "CollapsibleExample" under Navbars, Responsive behaviors.
www > docs > examples > Navbar > Collapsible.js - Line 16 was missing the "p" in "collapsible" for the NavDropdown's id.
Not trying to be pedantic, just noticed it and figured I'd correct it :)
> docs: Navbar example spelling error in NavDropdown's ID 

- src/OverlayTrigger.tsx
> Convert OverlayTrigger to an arrow function to fix type issues

- src/Dropdown.tsx
- test/DropdownMousedownSpec.tsx
Issue
Closes #6712 and #3196 
This pull request addresses the issue reported in #6712. When a dropdown is open with rootCloseEvent set to 'mousedown,' it currently exhibits flickering behavior when the toggle button is clicked. This issue arises due to the combination of hiding and showing the dropdown within the same click event.
To resolve this issue, I've made the following changes:
Modified the handleToggle function to skip execution when the dropdown is open, and rootCloseEvent is set to 'mousedown,' and the toggle button is clicked. This change prevents the flickering behavior by allowing the dropdown to remain open in this specific scenario.
https://github.com/react-bootstrap/react-bootstrap/assets/100420038/4e68d2d1-8e26-4164-bbbb-cffc3bcd9747
This change is made in response to …
> fix: Prevent Dropdown Flickering on 'mousedown' rootCloseEvent

- src/ModalHeader.tsx
Fixes #6733
Simplifies the built types by removing the `Pick` in the output.  This mirrors RB v2 which doesn't have this bug.
> fix(ModalHeader): fix types

- src/PageItem.tsx
- test/PageItemSpec.tsx
This Pull Request addresses the issue of limited routing flexibility in the `PageItem` component (https://github.com/react-bootstrap/react-bootstrap/issues/6753). By introducing the `anchorAs` prop, it allows the specification of a custom component for rendering links, thereby enabling seamless integration with custom routing libraries like Next.js's `<Link>`.
Changes Made:
- Added a new prop `anchorAs` to `PageItemProps`.
- Updated the `PageItem` component to use `anchorAs` as the component type for rendering the link.
- Ensured backward compatibility by defaulting `anchorAs` to the existing `Anchor` component from `@restart/ui/Anchor`.
Benefits:
- Enhances the flexibility and usability of `PageItem` in applications with custom routing requirements.
- Allows integration with Next.js's …
> feat(PageItem): use "as" property as an anchor element

- src/FormControl.tsx
Looks like [`@types/react` removed the `placeholder` attribute from `HTMLAttributes`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67170).
This may create inconsistencies when using `FormControl`.
The proposed fix replaces it with a more explicit `InputHTMLAttributes`.
> fix(FormControl): ensures compatibility with @types/react@18.2.48

- src/Tabs.tsx
In the Tabs component, the Nav did not receive the ID properties. 
Issue: https://github.com/react-bootstrap/react-bootstrap/issues/676
> fix(Tabs): missed id attribute of tabs

- .eslintrc
- package.json
- src/Carousel.tsx
- test/AccordionButtonSpec.tsx
- test/tsconfig.json
- tests/simple-types-test.tsx
Fixes issues found since update to react 18
> chore: fix ts issues

- src/NavLink.tsx
- src/Navbar.tsx
Just ran into the issue outlined in PR #6654 and wanted to add an explicit note about it to the API docs to both `Navbar` and `NavLink`
> docs: Add notes about NavLink key behavior

- src/NavbarOffcanvas.tsx
- src/Offcanvas.tsx
Fixes #6827
Closes #6828 
The Navbar context should've been used in NavbarOffcanvas instead of the regular Offcanvas
> fix(Offcanvas): do not trigger Navbar onToggle when closing

- www/docs/examples/Grid/Ordering.js
Error in the ["Grid"](https://react-bootstrap.netlify.app/docs/layout/grid/#responsive-grids) docs.
The example in the documentation for ordering suggest that the `order` property takes a value between `1` and `12` (inclusive). However, that is not working properly in the example.
The Bootstrap ["documentation"](https://getbootstrap.com/docs/5.3/utilities/flex/#order) says the range goes from `0` to `5` (inclusive). I changed the values in the example to those two.
> docs: fixed mistake with grid example

- src/Fade.tsx
In React >= 19, accessing element.ref is no longer supported and ref has become a regular prop. It will be removed from the JSX Element type in a future release.
Replaced .ref with .props.ref for React version 19+.
> Update Fade.tsx - element.ref is now a regular prop

- src/Nav.tsx
Fixes #6830
The import wasn't removed due to how we declared `additionalLibraries` for `babel-plugin-transform-react-remove-prop-types`.  It was looking for an exact import path.
https://github.com/react-bootstrap/configs/blob/99ab44dd872eee57d495f188dadee98608a03d23/packages/babel-preset/index.js#L48
> fix(Nav): remove prop-types-extra import from build

- www/src/theme/Playground/Preview.tsx
fixes: #6843 
Hi! as discussed in PR #6852  `to prevent the action on all anchors within code examples within the playground component`, here is the revised solution.
> fix: preventing redirects from live preview

- www/docs/examples/Button/Loading.js
This PR fixes the `no-promise-executor-return` linting error in the `simulateNetworkRequest` function.
As arrow functions are shown as an example of incorrect code in the [rule docs](https://eslint.org/docs/rules/no-promise-executor-return), wrapping the code in curly braces makes the intent more clear and doesn't throw a linting error.
> fix: resolve no-promise-executor-return linting error

- src/AccordionButton.tsx
- src/Col.tsx
- src/index.tsx
- src/useAccordionButton.ts
- src/useCol.ts
- src/usePlaceholder.ts
- www/docs/components/accordion.mdx
- www/docs/examples/Accordion/ContextAwareToggle.js
- www/docs/examples/Accordion/CustomToggle.js
- www/docs/migrating/migrating_v2.mdx
BREAKING CHANGE: Extracts the `useCol` and `useAccordionButton` from `Col.tsx` and `AccordionButton.tsx` so the CJS default export is consistent with other components (ie. no `export.default = ***`).
Fixes #6539
> feat!: extract hooks from component files

- package.json
Before this change (malformed JSON):
```sh
$ cat lib/package.json 
{type: module}
$ cat cjs/package.json
{type: commonjs}
```
After this change:
```sh
$ cat cjs/package.json
{"type": "commonjs"}
$ cat lib/package.json 
{"type": "module"}
```
> Fix syntax of generated package.json files
