react-bootstrap/react-bootstrap

- docs/src/PageFooter.js
> fix visibility of github stars

- src/DropdownButton.jsx
- test/DropdownButtonSpec.jsx
> Move className prop to outer-most element in dropdown

- src/Panel.jsx
- test/PanelSpec.jsx
For react-bootstrap/react-bootstrap#228
> Properly render panel-filling single children

- docs/examples/NavbarCollapsable.js
- docs/src/ComponentsPage.js
I added a bit of doc for the navbar section and added an example of how to use the toggleNavKey!
> [added] Example for collapsable Navbar in docs.

- src/Navbar.jsx
- test/NavbarSpec.jsx
> [fixed] Fix rendering Navbar header when toggleNavKey is 0

- docs/README.md
> docs: Added instructions for npm install in main dir

- docs/README.md
This wasn't explicit, and it wasn't obvious to me at first. Closes #435
> docs: Added line about grunt build

- src/NavItem.jsx
- test/NavItemSpec.jsx
Add role="button" when href==="#".
> Added role="button" to NavItem for aria compliance.

- README.md
- appveyor.yml.tmp
- docs/build.js
- package.json
- tools/amd/build.js
- tools/build.js
- tools/fs-utils.js
- tools/release-scripts/repo-release.js
> Fix Windows build problems

- .eslintrc
- src/CollapsableNav.js
- src/Input.js
- src/Nav.js
- src/Panel.js
- src/SplitButton.js
- src/SubNav.js
- src/TabPane.js
- src/TabbedArea.js
I carefully check every warning and I plan to get through the rest.
This PR for those of them I have checked so far.
> Add some fixes to get rid of eslint superfluos warnings. (145 less)

- tools/dist/build.js
- tools/lib/build.js
> [fix] for #491

- docs/src/ComponentsPage.js
for docs/src/ComponentsPage.js
#494 
#490
> Temporary mute eslint react/no-did-mount-set-state warning

- docs/examples/Input.js
validates based -> validation is based
> [fixed] typo

- src/Badge.js
- test/BadgeSpec.js
The new test fails without the code change.
> Handle multiple children in <Badge>. Fixes #532

- CONTRIBUTING.md
- MAINTAINING.md
- README.md
I have been giving some thought this week to seeking out additional collaborators on this repo. Primarily so I'm not the only bottleneck to getting things done since this project continues to gain support. There are plenty of good folks out there that have already contributed so much and I'm incredibly thankful to all of you. Before I let this out into the wild though I'd like some feedback on this initial draft as to what y'all would like.
/cc @mathieumg @AlexKVal @joemcbride @stevoland @pieterv @trentgrover-wf @JordanTheriault @apkiernan
I'm sure there are others that would be interested in this that I may have missed.
> Adding Maintainers Documentation

- src/Navbar.js
Inconsistent rendering between the client and server primarily around
casing.
Closes #475 
/cc @bobpace
> [fixed] Bug in Server vs Client side rendering of Navbar

- MAINTAINING.md
- tools/release-docs
- tools/release-docs-scripts/release-docs.js
- tools/release-scripts/constants.js
- tools/release-scripts/release.js
- tools/release-scripts/tag-and-publish.js
- tools/release-scripts/tag.js
- tools/release-scripts/test.js
For #552 
This is a work in progress, I just wanted some feedback about this!
@mtscout6 if this is the same thing as what you had in mind, I'll go ahead and do the two other points!
STEPS:
> Adding a new docs-only release

- docs/examples/NavbarBrand.js
- docs/src/ComponentsPage.js
- docs/src/Samples.js
Added example of passing component to navbar brand per #562
> [added] Docs example of passing component to navbar brand.

- MAINTAINING.md
> Docs. Clarify the "publishers team" existence.

- MAINTAINING.md
For maintainers to be aware of #565
> Document --dry-run option for maintainers.

- test/CollapsableNavSpec.js
mv CollapsableNavSpec.jsx => CollapsableNavSpec.js
They have not been executing at all.
> Return missed tests for CollapsableNav.

- src/ModalTrigger.js
- src/OverlayTrigger.js
- test/ModalTriggerSpec.js
- test/OverlayTriggerSpec.js
> [fixed] It is possible to merge OverlayMixin components

- CONTRIBUTING.md
> [added] Clarification about implementing components.

- docs/src/GettingStartedPage.js
As discussed in #487 and commented by @mtscout6 @dozoisch
> Getting Started: document concerns/recommendations on including Bootstrap

- src/CollapsableMixin.js
- src/CollapsableNav.js
- src/CollapsibleNav.js
- src/utils/deprecationWarning.js
I have also refactored #599. 
That way additional IE9 checking code will be also stripped out in production code.
> Fix for bug introduced by deprecation code.

- docs/examples/PanelListGroupFill.js
- src/CollapsableNav.js
- src/CollapsibleNav.js
- src/Nav.js
- src/Navbar.js
- src/Panel.js
- src/PanelGroup.js
- src/utils/deprecatedProperty.js
- test/CollapsableNavSpec.js
- test/CollapsibleNavSpec.js
- test/PanelSpec.js
Restored branch for #603.
I was cleaning up my branches and accidentally removed `AlexKVal:collapsiblePro` branch
and #603 was automatically closed by GitHub :)
And I have not found a way to re-open it.
Closes #425
> [changed] collapsable => collapsible property

- docs/examples/Input.js
Explanation
https://github.com/react-bootstrap/react-bootstrap/issues/586#issuecomment-99553317
As temporary measure for site till refactoring of Input is finished.
> Fix for Input styling on react-bootstrap.github.io

- docs/assets/style.css
- docs/src/HomePage.js
> Add active development warning to docs homepage

- docs/dev-run
- docs/server.js
- package.json
- webpack/strategies/docs.js
Will update changes files both server and client side without needing to
restart.
Resolves #623
> Use webpack-dev-server instead of webpack-dev-middleware

- .travis.yml
- karma.conf.js
- package.json
Thanks to @dozoisch for the hint about it :+1:
> Use Chrome on TravisCI instead of PhantomJS.

- package.json
eslint 0.21.0
New rule `object-shorthand`
It's already implementing here https://github.com/react-bootstrap/react-bootstrap/issues/584
New rule `no-unneeded-ternary`
https://github.com/eslint/eslint/blob/3517fa03ab7c4/docs/rules/no-unneeded-ternary.md
New rule `dot-location`
Enforces consistent newlines before or after dots.
https://github.com/eslint/eslint/blob/ce18710806a/docs/rules/dot-location.md
New option `skipBlankLines` for `no-trailing-spaces` rule
https://github.com/eslint/eslint/commit/5beee9d2e3f35
New functionality:
If you want to extend a specific configuration file, you can use the extends property and specify the path to the file.
```js
{
"extends": "node_modules/coding-standard/.eslintrc",
"rules": {
// Override any settings from the "parent" configuration
"eqeqeq": 1
}
} …
```
> [changed] Updated eslint dev-dependency

- docs/examples/TabbedAreaControlled.js
- docs/examples/TabbedAreaNoAnimation.js
- docs/examples/TabbedAreaUncontrolled.js
- src/TabPane.js
- src/TabbedArea.js
- test/TabbedAreaSpec.js
> [added] TabbedArea allows disabled tabs

- docs/assets/style.css
For react-bootstrap/react-bootstrap#641
> Fix syntax for CSS comment

- src/Popover.js
- src/Tooltip.js
- test/OverlayTriggerSpec.js
Fixes react-bootstrap/react-bootstrap#173
Adds test cases to catch this as well.
> [fixed] Fix propTypes for overlays

- docs/examples/InputAddons.js
> Add input radio and checkbox addon examples

- tools/amd/bower.json
> [fixed] Update classnames dep version for Bower

- src/CollapsibleMixin.js
> Bower cannot use code from react/lib.

- tools/amd/build.js
> [fixed] Put AMD modules under correct path

- src/DropdownButton.js
- test/DropdownButtonSpec.js
I needed this and noticed that the property was in DropdownButton but was not wired up. Hope this was simply an oversight and not intentional.
Did I miss anything?
> [added] DropdownButton now applies onClick prop to Button

- docs/src/ReactPlayground.js
Not sure how this passed tests the first time around.
> [fixed] Remove unused variable

- package.json
See: https://david-dm.org/react-bootstrap/react-bootstrap#info=devDependencies
> Update semver dev dependency to resolve security vulnerability warning

- docs/src/NavMain.js
Our design team has come up with a few logos that are favicon friendly. I'd like to put it up to an anonymous vote for a week and see what comes of it. Thoughts?
https://www.surveymonkey.com/s/X7Q9VX7
> Add link for new logo survey

- docs/examples/PopoverTriggerBehaviors.js
- docs/src/ComponentsPage.js
- docs/src/Samples.js
- src/OverlayTrigger.js
- src/RootCloseWrapper.js
- test/OverlayTriggerSpec.js
> [added] Enable rootClose for OverlayTrigger

- docs/src/ReactPlayground.js
> [fixed] Fix CodeMirrorEditor binding

- docs/src/NavMain.js
> Remove new logo survey link

- src/Modal.js
Replaced document with ownerDocument in Modal as requested by #729
Thanks @taion !
> [fixed] Replaced document with ownerDocument in Modal

- src/CollapsableNav.js
- src/CollapsibleNav.js
> Fix for `babel ES6 import` + `React` quirk.

- docs/examples/ButtonGroupBlock.js
- docs/src/ComponentsPage.js
- docs/src/Samples.js
- src/ButtonGroup.js
- test/ButtonGroupSpec.js
It's pretty simple and straightforward! See the jsfiddle in the original issue for an example.
> [added] Now accepting a `block` property on the ButtonGroup component.

- MAINTAINING.md
- README.md
- docs/src/HomePage.js
Documents proposed changes to the process by which we introduce breaking
changes and or remove functionality.
> Introduce Release Candidate process for breaking changes

- package.json
https://github.com/react-bootstrap/react-bootstrap/pull/744#issuecomment-106072346
> [changed] Remove ES6 sources from npm distribution.

- src/Input.js
- test/InputSpec.js
> [removed] Input type=submit deprecation warning.

- docs/README.docs.md
- docs/README.md
- docs/assets/style.css
- docs/src/NavMain.js
- docs/src/Root.js
- ie8/README.md
- ie8/index.html
[Gitter](https://gitter.im/react-bootstrap/react-bootstrap?at=55689c3dfac5e8bf2e984a8b)
> [changed] Make the brand name consistent.

- .travis.yml
Not it is fixed.
https://github.com/nodejs/io.js/issues/1850#issuecomment-107303709
> Unfix io.js version back.

- package.json
I'm keeping it on exact (working) version.
https://github.com/eslint/eslint/releases/tag/v0.22.0 Updates.
https://github.com/eslint/eslint/releases/tag/v0.22.1
> Update eslint. Dev dependency.

- src/index.js
- src/utils/index.js
Exposes `domUtils`, `CustomPropTypes` and other useful utilities.
Original PR here https://github.com/react-bootstrap/react-bootstrap/pull/745
This has a nicer commit history
> [added] utils namespace

- docs/src/PageFooter.js
> Importing SemVer in the browser causes an error

- src/ButtonInput.js
https://github.com/react-bootstrap/react-bootstrap/pull/791#issuecomment-109647911
> Remove no-unused-vars comment.

- src/Pagination.js
https://github.com/react-bootstrap/react-bootstrap/pull/786#issuecomment-110091107
> Address eslint warning.

- src/PaginationButton.js
Resolves #788 
/cc @roadmanfong
> [changed] `PaginationButton` to use `SafeAnchor`

- src/utils/CustomPropTypes.js
implementation
```js
return new Error(
'Invalid prop `' + propName + '` supplied to ' +
'`' + componentName + '`, expected a DOM element or an object that has a `render` method'
);
```
ref: https://github.com/react-bootstrap/react-bootstrap/commit/804c24a33f390166a89276f68772fa64b1510ba8#diff-6e40506f419cfbb5c93d15e804cc90fdL54
> Sync the description with the implementation.

- src/utils/deprecationWarning.js
- tools/amd/build.js
- tools/buildBabel.js
> Deprecation warning for individual file use in the Bower release

- src/utils/deprecationWarning.js
- tools/amd/bower.json
- tools/amd/build.js
- tools/buildBabel.js
Resolves #693
Dependent on PR #814
> Trim bower release

- docs/build.js
- docs/src/Routes.js
> Fix the docs prod error on the home page alone.

- tools/amd/bower.json
Anyway I thought it could be a little improved.
Now it will be in sync with npm json :smiley: 
(continuation of #822)
> Improve bower.json template.

- .eslintrc
- docs/src/ComponentsPage.js
- src/CollapsibleNav.js
- src/FadeMixin.js
- src/Nav.js
- test/PanelSpec.js
Addresses https://github.com/react-bootstrap/react-bootstrap/pull/810#discussion_r32374534
refs:
http://eslint.org/docs/rules/comma-style
http://eslint.org/docs/rules/one-var
> Impose comma and one-var styles.

- src/OverlayMixin.js
- src/RootCloseWrapper.js
- test/OverlayTriggerSpec.js
Fixes #802
Supersedes https://github.com/react-bootstrap/react-bootstrap/pull/835
> [fixed] rootClose behavior on replaced elements

- .babelrc
> [changed] Enabled "loose" Babel transpilation

- src/Modal.js
Make scrollbar size check lazy, Only called after components have
mounted. fixes #849
> [fixed] Modal Null Exception when react-bootstrap is loaded before the Body tag

- src/Alert.js
- src/Nav.js
- src/NavItem.js
- src/Panel.js
- src/TabPane.js
- src/TabbedArea.js
- test/AlertSpec.js
- test/NavItemSpec.js
- test/NavSpec.js
- test/PanelSpec.js
- test/TabPaneSpec.js
- test/TabbedAreaSpec.js
Some of this is just hard to do without a good answer to: https://github.com/facebook/react/issues/4000 
I've posted a comment asking if there was anything that was feasible for libraries to do
https://github.com/facebook/react/issues/4000#issuecomment-113044968
> Accessibility

- .eslintrc
- karma.conf.js
- package.json
supersedes #860 
Not the most ideal outcome to this, but its the best we got at this point :/
> eslint plugin babel

- src/Button.js
- src/ButtonInput.js
- src/NavItem.js
- src/OverlayTrigger.js
- src/TabbedArea.js
- src/utils/createContextWrapper.js
It is possible now because of #872
> Remove eslint-disable-line for object-shorthand

- package.json
https://github.com/jprichardson/node-fs-extra/releases/tag/0.20.0
no breaking changes.
> Update fs-extra. Dev dependency.

- tools/amd/build.js
- tools/generateFactories.js
- tools/lib/build.js
the part of #819
this doesn't solve #825 (but makes it a bit easier to solve IMHO)
> Simplify factories generation.

- webpack/test-coverage.config.js
> Fix coverage reporting only for src

- src/Jumbotron.js
- test/JumbotronSpec.js
- test/NavbarSpec.js
> Jumbotron componentclass

- package.json
0.1.1 => 0.2.0 because of this PR
https://github.com/karma-runner/karma-mocha/pull/61
> Update karma-mocha. Dev dependency.

- src/Button.js
- src/Col.js
- src/Grid.js
- src/Jumbotron.js
- src/Navbar.js
- src/Row.js
- src/utils/CustomPropTypes.js
- test/utils/CustomPropTypesSpec.js
And change 'componentClass' type into 'elementType' and make it not 'isRequired'
if a default value is provided in getDefaultProps()
Closes #883 and #884
> Add 'elementType' - new custom prop type validator

- CONTRIBUTING.md
Proposed in https://github.com/react-bootstrap/react-bootstrap/pull/887#issuecomment-115276160
/cc @mathieumg
> Add request for screenshots/screencasts for visual changes

- test/utils/CustomPropTypesSpec.js
https://github.com/react-bootstrap/react-bootstrap/pull/886#issuecomment-114820168
> Refactor CustomPropTypes tests.

- CONTRIBUTING.md
- MAINTAINING.md
- README.md
Fixes #863 
Already reviewed as #897
> [changed] Add two-release deprecation policy

- docs/assets/style.css
- docs/src/PropTable.js
Before:
After:
Compare:
ref #887
> Style props tables like Bootstrap options tables

- package.json
> [changed] Update babel-loader

- docs/build.js
- tools/build-cli.js
- tools/build.js
- tools/dist/build.js
- webpack/base.config.js
Superseded by babel-loader#5.2.0
> [removed] Don't need to disable Babel cache

- webpack/base.config.js
https://github.com/react-bootstrap/react-bootstrap/pull/895#issuecomment-115564043
> Fix eslint warnings.

- CONTRIBUTING.md
Addresses @taion's proposal. 
:cherries:
> Clarify [changed] usage in commit headers.

- src/Modal.js
- test/ModalSpec.js
> Address eslint warnings

- docs/generate-metadata.js
- docs/src/PropTable.js
- package.json
Let's you write markdown in your propType comments!
> Add markdown support for prop comments

- karma.conf.js
https://github.com/react-bootstrap/react-bootstrap/pull/871#issuecomment-114106621
> Fix coverage reporting for only 'src'

- docs/generate-metadata.js
- docs/src/PropTable.js
just strokes.
What do you think ?
> Small regexp refactorings.

- src/Modal.js
- src/ModalTrigger.js
> [fixed] Accidental breaking change in Modal trigger

- appveyor.yml
> Unlock npm version back for Appveyor.

- docs/examples/PanelBasic.js
- docs/src/ComponentsPage.js
Closes https://github.com/react-bootstrap/react-bootstrap/issues/466
> Document possibility to pass on any additional properties to Panel

- package.json
`./tools/release` works fine with this update.
> Update fs-extra dev dependency.

- src/Nav.js
- test/NavSpec.js
Closes https://github.com/react-bootstrap/react-bootstrap/issues/422
Added props descriptions look like
> [changed] html id and class attributes handling for Nav

- src/Pagination.js
This PR is the same as #939 to fix two bugs in Pagination, but split the commit for corresponding bugs.
> Split commit of PR #939

- test/PaginationSpec.js
Missed tests for #946
This will fail till #946 is merged.
Then just restart CI-services to check this PR.
> Add missed tests for Pagination

- src/Position.js
Didn't spot this last time... I'm sure that all typos here are fixed already :P
> [fixed] Position.js typo `componentDidUpate`

- docs/assets/docs.css
- docs/src/HomePage.js
> Announce explicitly about help wanted

- CONTRIBUTING.md
> Clarify lodash usage in the code.

- package.json
There is only this change https://github.com/npm/node-semver/commit/41b56fa573d1ef0d1718777a8a21ae1b57ebcd83 in `semver`
> Update semver. Dev dependency.

- .eslintrc
https://github.com/eslint/eslint/issues/3016
> Temporary disable 'space-infix-ops' eslint rule

- .eslintrc
Let travis help with such https://github.com/react-bootstrap/react-bootstrap/pull/848#discussion-diff-34423722
> Impose 'sctrict' "never" eslint rule

- karma.conf.js
- package.json
> Remove unnecessary dev dependencies

- src/ListGroup.js
> [added] ListGroup supports iterator as child

- docs/examples/DropdownButtonBasic.js
- docs/examples/NavBasic.js
- docs/examples/NavDropdown.js
- docs/examples/NavJustified.js
- docs/examples/NavStacked.js
- docs/examples/PaginationAdvanced.js
- docs/examples/PopoverTriggerBehaviors.js
- docs/examples/TabbedAreaControlled.js
- docs/examples/TabbedAreaNoAnimation.js
- docs/examples/TabbedAreaUncontrolled.js
- docs/src/ComponentsPage.js
- docs/src/ReactPlayground.js
- src/Accordion.js
for boolean attributes via examples to cultivate more clean code
Somewhere in comments @mtscout6 has been recommending this approach.
> Encourage usage of just 'attrName' instead of 'attrName={true}'

- .eslintrc
- test/.eslintrc
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-boolean-value.md
> Impose 'react/jsx-boolean-value' eslint rule

- docs/src/ComponentsPage.js
https://github.com/react-bootstrap/react-bootstrap/pull/1008#issuecomment-122278996
> Remove leftover for 'ModalTrigger' from docs.

- docs/examples/ModalCustomSizing.js
- docs/src/ComponentsPage.js
> Fix ModalCustomSizing example

- docs/examples/TooltipBasic.js
> Ensure tooltips are shown in TooltipBasic

- src/Portal.js
> [fixed] Portal doesn't mount extra node

- src/templates/factory.index.js.template
- src/templates/factory.js.template
For details see #825 
Since we haven't pushed 0.24 yet and since that will break the Form Static component anyways, I'd like to get this one in as part of v0.24.
> [changed] Add deprecation warning that factories will be removed

- src/templates/factory.index.js.template
- src/templates/factory.js.template
- src/utils/deprecationWarning.js
https://github.com/react-bootstrap/react-bootstrap/pull/1019
> Make deprecation warnings safe

- src/Tooltip.js
- test/TooltipSpec.js
> [fixed] Tooltip accepts a style prop

- .eslintrc
- package.json
https://github.com/yannickcr/eslint-plugin-react/releases/tag/v3.0.0
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-duplicate-props.md
> Update eslint-plugin-react dev dependency

- src/Modal.js
> Fix description of Modal keyboard prop

- src/Tooltip.js
https://github.com/react-bootstrap/react-bootstrap/pull/1028#issuecomment-123159233
> Remove `style` property exposing

- docs/examples/PanelCollapsible.js
- docs/src/ComponentsPage.js
- docs/src/Samples.js
https://github.com/react-bootstrap/react-bootstrap/issues/190#issuecomment-87897760
Closes #190
> Add standalone collapsible Panel example

- src/Overlay.js
- src/OverlayTrigger.js
- test/OverlayTriggerSpec.js
> [added] Overlay and OverlayTrigger accept Transition callbacks

- test/OverlayTriggerSpec.js
Interesting... And how is it possible ? :smiling_imp:
> Fixed semicolon eslint warning

- docs/examples/ModalStatic.js
- docs/src/ComponentsPage.js
- docs/src/Samples.js
- src/Modal.js
- src/ModalDialog.js
- test/ModalSpec.js
Not sure that `Modal.Markup` is the best name...taking suggestions
> Modal tweak

- package.json
> [fixed] add lodash as direct dependency

- package.json
`babel-eslint` version changer is https://github.com/babel/babel-eslint/pull/152
> Update babel-eslint dev dependency

- src/BootstrapMixin.js
- src/styleMaps.js
> Add 'xs, sm, md, lg' values for 'bsSize'

- src/PageItem.js
> [fixed] Prevent click on PageItem if disabled

- src/Modal.js
- test/ModalSpec.js
> [fixed] Modal error when backdrop is `false`

- src/utils/domUtils.js
- src/utils/overlayPositionUtils.js
Fixes #1050
I started trying to get tests going for this, but it ended up taking a while for me for various reasons. I can come back to it later if needed.
> Overlays don't position themselves properly when target is an SVG

- docs/src/ReactPlayground.js
Got a little carried away here, maybe.
This does the initial render of the examples on the server side. It's not perfect - you still need to wait a while for all the JS to finish running on the client before you can interact with any of the examples, but at least you can see them on initial page load.
> Initially render examples on the server

- test/GridSpec.js
> Add missing Grid tests

- docs/src/GettingStartedPage.js
> Remove bower lib reference from docs

- src/PaginationButton.js
- test/PaginationSpec.js
> Disabled pagination buttons should not fire 'onSelect'

- src/Modal.js
- src/ModalBody.js
- src/ModalDialog.js
- src/ModalFooter.js
- src/ModalHeader.js
- src/ModalTitle.js
- src/Portal.js
A few code style cleanups to get the Modal and Portal components to match the rest of the codebase.
This is my first PR, so let me know if I'm doing anything wrong.  Thanks!
> Modal & Portal code style cleanup to match rest of project.

- .eslintrc
- docs/build.js
- docs/server.js
- docs/src/ReactPlayground.js
- package.json
- test/.eslintrc
- tools/.eslintrc
https://github.com/react-bootstrap/react-prop-types/pull/7#issuecomment-128101274
Fixed now :sparkle:
> Impose 'eslint@0.24' defaults

- src/Affix.js
- src/ModalDialog.js
- src/Popover.js
> Always merge explicitly specified component styles

- docs/assets/style.css
- docs/examples/.eslintrc
- docs/examples/DropdownButtonCustom.js
- docs/examples/DropdownButtonCustomMenu.js
- docs/generate-metadata.js
- docs/src/ComponentsPage.js
- docs/src/ReactPlayground.js
- docs/src/Samples.js
- package.json
- src/DropdownBase.js
- src/DropdownButton.js
- src/DropdownMenu.js
- src/MenuItem.js
- src/NavDropdown.js
- src/RootCloseWrapper.js
- src/SplitButton.js
- src/utils/domUtils.js
- test/DropdownButtonSpec.js
- test/DropdownMenuSpec.js
- test/MenuItemSpec.js
- test/NavDropdownSpec.js
- test/SplitButtonSpec.js
Adds a doc example highlighting the new child components for customization.
It also "fixed" a few things to get them to work consistently, though its up to ya'll whether those were good ideas. Also let me know if the example styling is too much :P :rainbow: 
cc @mtscout6 
related to: #1096
> Dropdown docs and tweaks

- docs/src/ComponentsPage.js
- src/TabPane.js
- src/TabbedArea.js
> Fix mapping TabPane title

- src/Badge.js
- src/Button.js
- src/ButtonGroup.js
- src/CarouselItem.js
- src/CollapsibleNav.js
- src/DropdownButton.js
- src/DropdownMenu.js
- src/FormGroup.js
- src/Grid.js
- src/InputBase.js
- src/Interpolate.js
- src/ListGroupItem.js
- src/MenuItem.js
- src/Nav.js
- src/NavItem.js
- src/Navbar.js
- src/Overlay.js
- src/OverlayTrigger.js
- src/PageItem.js
- src/PanelGroup.js
- src/ProgressBar.js
- src/SplitButton.js
- src/SubNav.js
- src/Table.js
for the sake of clarity in documentation.
The first part of #976
Additionally here was removed stale `animation: true` from `CarouselItem`/`getDefaultProps()`
> Explicitly set default values for boolean properties

- src/Modal.js
> Hide bsStyle from Modal props documentation

- src/index.js
> [fixed] Collapse exported as Fade

- docs/assets/style.css
- docs/src/PropTable.js
- package.json
- src/DropdownBase.js
- src/DropdownButton.js
- src/DropdownMenu.js
- src/MenuItem.js
- src/NavDropdown.js
- src/SplitButton.js
- test/DropdownButtonSpec.js
- test/DropdownMenuSpec.js
- test/MenuItemSpec.js
- test/NavDropdownSpec.js
- test/SplitButtonSpec.js
I kept the changes a localized to the dropdown as possible, this was actually helpful just in that it uncovered a few focus bugs (and made some tests simpler).
changed: onRequestClose -> onToggle
onSelect passes the eventKey directly instead of the selection event.
> changed onSelect behavior

- test/ButtonSpec.js
These are testing something weird/wrong, because `Button` injects its children as the children of the component used, which is not legal for `input`.
> Remove wrong componentClass='input' Button tests

- package.json
`css-loader` https://github.com/webpack/css-loader/commit/717517484685cd772114ffe2504670639c61526e
> Update css-loader dev-dependency

- src/Modal.js
> Document Modal's 'show' property

- docs/examples/LeftTabs.js
- docs/src/ComponentsPage.js
- docs/src/Samples.js
- src/Tabs.js
- src/styleMaps.js
- test/TabsSpec.js
> [Added] Implements a left-aligned version of tabs

- package.json
addresses a potential positioning bug
> bump overlay dev

- src/MenuItem.js
> [fixed] id passthrough for MenuItem

- src/utils/CustomPropTypes.js
Re-implementation for https://github.com/react-bootstrap/react-bootstrap/pull/1217
> Fix 'isRequireForA11y' undefined/null checking

- .eslintrc
- docs/examples/ButtonInput.js
- docs/examples/Input.js
- docs/src/PropTable.js
- src/AffixMixin.js
- src/Carousel.js
- src/Dropdown.js
- src/DropdownMenu.js
- src/InputBase.js
- src/NavItem.js
- src/Navbar.js
- src/Overlay.js
- src/SplitButton.js
- src/Tabs.js
- src/Thumbnail.js
- src/utils/deprecationWarning.js
- test/GlyphiconSpec.js
- test/ThumbnailSpec.js
- tools/build.js
- tools/fs-utils.js
a part of `airbnb` style.
Continuation of https://github.com/react-bootstrap/react-bootstrap/pull/1186#issuecomment-133017636.
> Impose 'brace-style' 'default-case' and 'ident' rules

- .eslintrc
- docs/examples/ButtonInput.js
- docs/examples/Input.js
- docs/src/Anchor.js
- docs/src/PropTable.js
- src/AffixMixin.js
- src/Carousel.js
- src/Dropdown.js
- src/DropdownMenu.js
- src/InputBase.js
- src/ListGroup.js
- src/Nav.js
- src/NavItem.js
- src/Navbar.js
- src/Overlay.js
- src/Panel.js
- src/Popover.js
- src/SplitButton.js
- src/Tabs.js
- src/Thumbnail.js
- src/Tooltip.js
- src/utils/deprecationWarning.js
- test/GlyphiconSpec.js
- test/ThumbnailSpec.js
- tools/build.js
- tools/fs-utils.js
Closes #1219
Depends on https://github.com/react-bootstrap/react-bootstrap/pull/1230
> Make 'id' prop type uniform throughout the project

- src/Tabs.js
> [fixed] allow null activeKey (empty) selection

- src/BootstrapMixin.js
- src/Button.js
- src/ButtonGroup.js
- src/Col.js
- src/Collapse.js
- src/Dropdown.js
- src/DropdownButton.js
- src/DropdownToggle.js
- src/Fade.js
- src/Grid.js
- src/Jumbotron.js
- src/MenuItem.js
- src/Modal.js
- src/Navbar.js
- src/Overlay.js
- src/Pagination.js
- src/PaginationButton.js
- src/Popover.js
- src/Row.js
- src/Tooltip.js
- src/utils/CustomPropTypes.js
- src/utils/childrenValueInputValidation.js
addresses all beginning from https://github.com/react-bootstrap/react-bootstrap/pull/1223#issuecomment-135781237
> Do not import the whole 'react-prop-types' into R-B components

- src/OverlayTrigger.js
- test/OverlayTriggerSpec.js
> [fixed] OverlayTrigger event handlers are properly maintained

- src/OverlayTrigger.js
Addresses an inadvertent revert we did switching the hover triggers to use mouse{enter|leave} instead of out/over, since those events also fire on child elements, causing flicker. Unfortunately the React mousenter/leave implentation is [broken](https://github.com/facebook/react/issues/4251), so we need to simulate it ourselves.
> [fixed] OverlayTrigger hover triggers on mousenter/leave

- docs/examples/GridBasic.js
- This isn’t breaking anything that I’m aware of, however for
consistency and naming sake, I’ve renamed it accordingly.
Awesome project btw! Thanks for all of your work!
> Fixing wrong reference for gridInstance

- README.md
https://gitter.im/react-bootstrap/react-bootstrap?at=55e28cf3017739836ed481d0
> Clarify about 'React-0.14' releases in the Readme.

- .travis.yml
What do you think about it, guys ?
> Enable 'node_modules' caching on TravisCI

- docs/examples/NavDropdown.js
- argument count was wrong in invocation of `onSelect` callback.
> [documentation] - fixes example argument types

- package.json
Lets us not bifurcate this dep between mainline and React 14
> Update uncontrollable dependency

- package.json
This is just to allow these to get merged into the React 14 branch to use the new optimizations in the build.
> Update Babel dependencies

- package.json
- src/ButtonGroup.js
- src/Collapse.js
- src/Dropdown.js
- src/DropdownToggle.js
- src/Fade.js
- src/MenuItem.js
- src/utils/childrenValueInputValidation.js
reflect https://github.com/react-bootstrap/react-prop-types/pull/14
> Update dev.dependency 'react-prop-types'

- docs/src/ComponentsPage.js
- test/ImageSpec.js
https://github.com/react-bootstrap/react-bootstrap/pull/1293#issuecomment-141706119
> Fix eslint warnings and move 'Images' up before 'Thumbnail'

- .travis.yml
> Switch to node@4

- docs/assets/style.css
- docs/examples/PopoverContained.js
- docs/examples/PopoverPositionedScrolling.js
Fixes #1177 per the recommendation there
> Fix contained popover examples

- docs/examples/.eslintrc
- docs/examples/CollapsibleNav.js
- docs/examples/NavbarBasic.js
- docs/examples/NavbarBrand.js
- docs/examples/NavbarCollapsible.js
- docs/src/ComponentsPage.js
- docs/src/NavMain.js
- docs/src/ReactPlayground.js
- src/NavBrand.js
- src/Navbar.js
- src/index.js
- src/utils/ValidComponentChildren.js
- test/NavBrandSpec.js
- test/NavbarSpec.js
as described in issue #1158: Use NavbarBrand component for Navbar brand
> Added NavBrand component, including docs

- docs/src/GettingStartedPage.js
> Explain why to import components from lib/

- src/Overlay.js
> Document `onHide` prop on Overlay

- src/index.js
> [fixed] Actually export the Image component

- src/NavBrand.js
- src/Navbar.js
- test/NavbarSpec.js
Also simplified the rendering code a bit
Fixes #1384
> [fixed] Toggle button when using NavBrand

- docs/src/GettingStartedPage.js
- webpack/webpack.config.js
Fixes #1397 
I'll release this as v0.27.1.
> Don't include react-dom in the bundles

- test/PaginationSpec.js
because of React-0.14 changes
Fix for https://github.com/react-bootstrap/react-bootstrap/pull/1376#issuecomment-146909059
> Fix for #1376

- src/NavItem.js
- test/NavItemSpec.js
Fixes https://github.com/react-bootstrap/react-bootstrap/issues/1089
> [fixed] Incorrect 'aria-selected' on NavItem

- src/DropdownToggle.js
- test/DropdownToggleSpec.js
Prefer children for label, but default to title otherwise
Fixes #1410
> [fixed] DropdownTitle children v. title

- src/MenuItem.js
- test/MenuItemSpec.js
Fixes https://github.com/react-bootstrap/react-router-bootstrap/issues/112.
Same caveat as on #1413.
> [fixed] Respect onClick on MenuItem

- src/MenuItem.js
Fixes https://github.com/react-bootstrap/react-bootstrap/issues/1263
> [fixed] Falsy href handling on MenuItem

- src/Nav.js
- test/NavSpec.js
Per upstream TWBS docs, they're not supported
> [fixed] Explicitly disallow justified Navbar Navs

- docs/examples/TooltipInCopy.js
> Fix tooltip in copy example

- src/OverlayTrigger.js
> [fixed] OverlayTrigger show/hide timeout management

- src/ResponsiveEmbed.js
> [fixed] Don't clone children in ResponsiveEmbed

- .babelrc
- package.json
Minified bundle goes from 173,816 B to 173,259 B.
> Use dev-expression Babel plugin

- docs/src/ComponentsPage.js
Very small change but it should help this component visibility in the docs as I had totally missed the third example! (I probably would've gone further in the list if I had seen there was a component called like that!
> Added CollapsibleNav to Navbars component list

- src/Navbar.js
- test/NavbarSpec.js
> [changed] Only add the `navigation` role to navbar when not using a <nav>

- src/ModalHeader.js
> [fixed] aria-label properly passed to the Modal header button

- src/Modal.js
- src/ModalBody.js
- src/ModalDialog.js
- src/ModalFooter.js
- src/ModalHeader.js
- src/ModalTitle.js
- test/ModalSpec.js
Cut the modal over to use React-overlays
> Use react-overlays for Modal

- docs/assets/javascript.js
- docs/client.js
- docs/src/ReactPlayground.js
take from that PR
also solarized is a terrible theme
> Added a local js mode for CodeMirror to properly handle jsx

- src/MenuItem.js
https://github.com/react-bootstrap/react-bootstrap/issues/1498
> Define eventKey on MenuItem to be PropTypes.any

- src/DropdownButton.js
- src/SplitButton.js
> [changed] dropdown props are passed through to the dropdown Button

- docs/src/ComponentsPage.js
- package.json
> Add scrollspy behavior to docs

- docs/examples/GridBasic.js
- src/Col.js
- test/ColSpec.js
Although the `hidden-*` classes are not just for columns they are really frequently used on them.
> responsively hiding columns

- src/Modal.js
- test/ModalSpec.js
> Ensure Modal cleanup

- src/Dropdown.js
> [fixed] remove extra tabIndex

- README.md
- docs/src/ComponentsPage.js
- docs/src/HomePage.js
- Drop React v0.13 notes
- Drop Gitter link
- Improve scrollspy on components page
> Update docs a bit

- src/MenuItem.js
- src/NavItem.js
- src/Tabs.js
- test/DropdownButtonSpec.js
- test/DropdownMenuSpec.js
- test/MenuItemSpec.js
- test/NavItemSpec.js
The various onSelect events will now consistently be called with:
eventKey, event (if any)
> [changed] onSelect events consistent signature

- src/FormControls/Static.js
- test/FormControlsSpec.js
> [added] Allow overriding element in FormControls.Static

- src/NavbarHeader.js
- test/NavbarSpec.js
> add custom className to header

- docs/src/sections/NavbarSection.js
Addressing https://github.com/react-bootstrap/react-bootstrap/issues/1696
This is a minor docs update.
> docs(Navbar): Updating docs defaultExpanded

- CHANGELOG.md
- src/MenuItem.js
- test/MenuItemSpec.js
> Fix handling of styling props on special <MenuItem>s

- src/Nav.js
> Tiny cleanup in <Nav>

- src/utils/bootstrapUtils.js
> Don't check for prefixed bsStyle in bootstrapUtils

- docs/src/sections/ButtonSection.js
- src/Button.js
- src/SafeAnchor.js
- test/SafeAnchorSpec.js
- test/TabContainerSpec.js
> disable clicks on anchor Buttons

- src/NavItem.js
- src/PageItem.js
- src/PaginationButton.js
> Make anchor prop handling consistent

- src/TabContainer.js
- src/Tabs.js
Fixes #1822
I don't have a test case here because I'm not sure I could write one without its just looking sorta dumb.
> Don't incorrectly pass onSelect past TabContainer

- src/Nav.js
- src/TabContent.js
- test/TabContainerSpec.js
- test/TabsSpec.js
> fix tab bug

- src/Checkbox.js
- src/Radio.js
- test/CheckboxSpec.js
- test/RadioSpec.js
> Add inputRef to <Checkbox> and <Radio>

- test/TabsSpec.js
- test/TooltipSpec.js
- test/index.js
Fixes related with locale and using multiple deprecation libraries (one internally and another from react-prop-types)
> Fix tests.

- src/TabContainer.js
- src/TabContent.js
- test/TabContainerSpec.js
fixes #1949, fixes #1932, fixes #1892
> Fix tab bugs

- docs/examples/TooltipBasic.js
- docs/examples/TooltipInCopy.js
- docs/examples/TooltipPositioned.js
I'm torn on whether to also include id's on tooltips in examples focusing on other components such as the Modal so I left those out. Thoughts?
> Add required id to tooltip examples

- docs/src/SupportPage.js
See https://github.com/reactiflux/volunteers/issues/25#issuecomment-147538522 and https://github.com/reactiflux/volunteers/issues/17#issuecomment-147300333.
> Reactiflux is on Discord now.

- docs/examples/Modal.js
- docs/examples/Overlay.js
Added remaining id's to examples as referenced in #1965
> Add id to remaining tooltip examples

- docs/examples/.eslintrc
- docs/examples/PagerAligned.js
- docs/examples/PagerDefault.js
- docs/examples/PagerDisabled.js
- docs/src/ReactPlayground.js
- docs/src/sections/PagerSection.js
- src/PageItem.js
- src/Pager.js
- src/PagerItem.js
- test/PagerItemSpec.js
- test/PagerSpec.js
Addresses issue #1757 
Renaming the file from PageItem.js to PagerItem.js is a breaking change so I'm submitting this against the next branch as it says to in CONTRIBUTING.md.
Hopefully I did the PR right this time 😄
Let me know if i've got anything wrong, happy to fix things quickly.
Thanks
> Rename <PageItem> to <Pager.Item>

- src/BreadcrumbItem.js
- test/BreadcrumbItemSpec.js
This makes it consistent with other link items.
> Drop linkId on Breadcrumb.Item

- src/CarouselItem.js
Users should use `<Carousel.Caption>` instead
> Remove caption prop from <Carousel.Item>

- .travis.yml
- package.json
Rename the package.json scripts to match up with names elsewhere
> Clean up tooling a bit

- docs/src/sections/DropdownSection.js
- src/Collapse.js
- src/Modal.js
- test/ModalSpec.js
> Remove unnecessary ref usage and document required usage

- src/OverlayTrigger.js
- test/DropdownMenuSpec.js
- test/OverlayTriggerSpec.js
Fixes #233
Requires #2095 for clean build
> Fix <OverlayTrigger> rootClose regression

- src/Panel.js
> Always pass expanded to renderAnchor in Panel

- docs/examples/TabsWithDropdown.js
- docs/src/Samples.js
- docs/src/SubNav.js
- docs/src/sections/TabsSection.js
- src/Nav.js
- src/NavDropdown.js
- test/NavDropdownSpec.js
> Add tab dropdown support

- docs/src/SubNav.js
- src/NavDropdown.js
- test/NavDropdownSpec.js
> Fix logic for determining child active state

- src/Pagination.js
- test/PaginationSpec.js
fix issue for less items, see #2270
> Active page/item disappears for few items

- src/Dropdown.js
- test/DropdownButtonSpec.js
Fixes https://github.com/react-bootstrap/react-bootstrap/issues/2219
> Pass onMouseEnter and onMouseLeave to <Dropdown>

- docs/src/sections/OverlaySection.js
- docs/src/sections/PopoverSection.js
> Better document overlay container

- test/ModalBodySpec.js
- test/ModalFooterSpec.js
- test/ModalTitleSpec.js
Fix module issue. Change react/lib/ReactTestUtils to react-addons-test-utils
> Fix for build failing

- MAINTAINING.md
Fixes https://github.com/react-bootstrap/react-bootstrap/issues/2385
> Drop last Gitter link [ci skip]

- docs/src/GettingStartedPage.js
Fixes https://github.com/react-bootstrap/react-bootstrap/issues/2411
> Include dependencies in install instructions

- package.json
Fixes https://github.com/react-bootstrap/react-bootstrap/issues/2408
Revert when https://github.com/babel/babel-standalone/issues/73 is resolved
> Pin to babel-standalone that works on Node

- package.json
https://github.com/babel/babel-standalone/issues/73 was resolved
> Unpin babel-standalone

- docs/src/IntroductionPage.js
> fix example

- src/Pagination.js
- test/PaginationSpec.js
Fixes #2431
Still inclined to get rid of all this code. It's hairy and I don't see why it should be in React-Bootstrap.
> Actually fix <Pagination boundaryLinks>

- src/Carousel.js
- test/CarouselSpec.js
Do not set previousActiveIndex if slide animation is disabled
> Fix Carousel slide=false bug

- src/Collapse.js
- src/Fade.js
- src/TabContent.js
- src/TabPane.js
- src/Tabs.js
> Wire up mountOnEnter

- docs/examples/FormControls.js
> Fix <Radio> example

- package.json
Mostly to pull in https://github.com/jquense/uncontrollable/pull/22
> Upgrade `uncontrollable` dependency

- src/Dropdown.js
> remove onClose from dropdown

- docs/examples/.eslintrc
- docs/examples/ButtonGroupToggleCheckbox.js
- docs/examples/ButtonGroupToggleRadio.js
- docs/src/ReactPlayground.js
- docs/src/Samples.js
- docs/src/sections/ButtonGroupSection.js
- src/ToggleButton.js
- src/ToggleButtonGroup.js
I’m tried of rewriting this component all the time :P
> Add toggle button components

- docs/src/sections/PanelSection.js
> Fix misleading typo error in Panel section

- docs/examples/TabsWithDropdown.js
- src/CloseButton.js
- src/index.js
- test/CloseButton.js
> Export CloseButton for public use & Fix example docs error

- src/Radio.js
Quick update to add title to radio label
https://github.com/react-bootstrap/react-bootstrap/pull/2635#issuecomment-305186615
> Add title to radio label

- src/Checkbox.js
> Update Checkbox.js to apply title to label

- README.md
Add react-bootstrap-extended to the related modules section.
> Add react-bootstrap-extended to the related modules section

- docs/src/sections/NavbarSection.js
> Clarify Navbar.Toggle controlling Navbar.Collapse

- src/Dropdown.js
- test/DropdownButtonSpec.js
> Add defaultOpen to Dropdown propTypes

- docs/examples/ButtonGroupToggleCheckbox.js
- docs/examples/ButtonGroupToggleRadio.js
- karma.conf.js
- package-lock.json
- src/ToggleButtonGroup.js
- test/ToggleButtonGroupSpec.js
I don’t know why this commit was lost in https://github.com/react-bootstrap/react-bootstrap/pull/2252
> cleanup, add tests

- docs/examples/ToggleButtonGroupControlled.js
- src/ToggleButton.js
- test/ToggleButtonGroupSpec.js
Fix "ToggleButton's disabled property doesn't work well" #2759
Details are in the above issue.
Thanks.
> Fix ToggleButton's disabled attribute to work

- docs/examples/PanelGroupMultipleExpandable.js
- docs/src/Samples.js
- docs/src/sections/PanelSection.js
In regards to my old PR https://github.com/react-bootstrap/react-bootstrap/pull/2775
Example:
> Updated documentation with multiple expandable Panels.

- package.json
should fix #2803 #2827 #2812 #2712
> update RO range

- src/MediaBody.js
- test/MediaBodySpec.js
> Add align prop to MediaBody (#2824)

- package.json
- yarn.lock
Will merge after CI as a trivial change
> Update react-overlays dependency

- tools/es/build.js
> Fixes #2831 added missing devDependencies

- docs/src/IntroductionPage.js
According to the latest released documentation http://getbootstrap.com/docs/4.0/about/brand/#name
Bootstrap should not be associated with Twitter
> remove twitter association

- docs/README.md
Hi,
I took the liberty of updating the README file by adding some conjunction words to a few of the sentences to help make it read a bit more clearly. I also separated the word "checkout" into two words "check out," which I believe is the more proper usage here, with its verb form.
Thanks so much,
Ben
> Updated grammar of README

- www/src/examples/FormBasic.js
> Fix FormBasic example

- www/src/pages/getting-started/introduction.js
Removed a HTML tag that was not in use from Introduction.
> removed html close tag from instrodution

- src/Panel.js
- src/PanelGroup.js
- test/PanelGroupSpec.js
I ran into this issue myself last week https://github.com/react-bootstrap/react-bootstrap/issues/2926.
Created a test case and a fix.
> Fix PanelGroup Accordion allow more than one panel open #2926

- www/src/pages/components/dropdowns.js
https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Dropdown.js#L88
> Fix ordering of arguments in Dropdown onSelect

- www/src/components/LinkToSource.js
- www/src/css/docs.css
- www/src/pages/components/alerts.js
- www/src/pages/components/badge.js
- www/src/pages/components/breadcrumb.js
- www/src/pages/components/button-group.js
- www/src/pages/components/buttons.js
- www/src/pages/components/carousel.js
- www/src/pages/components/dropdowns.js
- www/src/pages/components/forms.js
- www/src/pages/components/glyphicons.js
- www/src/pages/components/images.js
- www/src/pages/components/jumbotron.js
- www/src/pages/components/label.js
- www/src/pages/components/list-group.js
- www/src/pages/components/modal.js
- www/src/pages/components/navbar.js
- www/src/pages/components/navs.js
- www/src/pages/components/overlays.js
- www/src/pages/components/page-header.js
- www/src/pages/components/pagination.js
- www/src/pages/components/panel.js
- www/src/pages/components/popovers.js
- www/src/pages/components/progress.js
- www/src/pages/components/table.js
- www/src/pages/components/tabs.js
- www/src/pages/components/tooltips.js
- www/src/pages/components/well.js
Rewrote previous PR (#2852) after docs update.
This should now fulfil #428.
> Add LinkToSource before every PropTable

- www/src/pages/components/modal.js
> include props for modal dialog

- www/src/pages/getting-started/introduction.js
- www/src/pages/index.js
> Version usage clarification

- www/src/components/PageFooter.js
We should really have had this in here...
> Docs attribution

- src/BreadcrumbItem.js
> quick fix-up on BreadcrumbItem

- test/BreadcrumbItemSpec.js
Sorry, I think I left this out and the previous PR got merged.
> Fixes a broken BreadcrumbItem spec!

- package.json
- www/package.json
Reverts react-bootstrap/react-bootstrap#3096
> Revert "Add engines to package.json"

- www/src/pages/components/modal.js
> Add warning about multiple modals not supported out of box

- .babelrc.js
- package.json
- yarn.lock
Sorry we should do a non breaking update and then remove this.
> runtime Corejs

- www/src/components/NavMain.js
Fixes https://github.com/react-bootstrap/react-bootstrap/issues/3285
> Fix Discord invite link

- package.json
I meet some deprecation message and found this link
https://github.com/mochajs/mocha/wiki/compilers-deprecation.
So I made some change on config file to prevent that deprecation message.
> Fix deprecation on --compilers

- src/Alert.js
- www/src/pages/components/overlays.js
fix https://github.com/react-bootstrap/react-bootstrap/issues/3290 and a typo
> docs fixes

- www/src/pages/index.js
-Fixed a few typos, deleted unnecessary comma, and deleted a word for grammar.
-Commented out Line 6 for now as commit failure will appear (see below).
> edit text and comment out unused withProps for now

- src/DropdownMenu.js
- yarn.lock
> fix: add flip and forward popperConfig to DropdownMenu

- README.md
Yarn is the our package manager of choice
-to-
Yarn is our package manager of choice
> fix typo in README.md at #27 from

- www/src/pages/index.js
Fixed to "built from scratch" instead of "stratch", which is a grammar mistake in this context.
Cheers :)
> Update index.js / Fix grammar (stratch -> scratch)

- www/src/pages/migrating.mdx
Should fix #3278, please tell me if I missed/misunderstood something :)
> #3278 Corrected typo for "Navbar.Toggle" in migrating.mdx

- www/src/pages/migrating.mdx
> Update Migration Guide

- src/Breadcrumb.js
- test/BreadcrumbSpec.js
> Remove Navigation Role from Breadcrumb

- README.md
- package.json
- www/package.json
I made the latest beta latest on npm. lets do this
> chore: update to point to gh-pages site

- www/src/pages/components/alerts.mdx
Noticed a small typo in the Alert docs.
> Correct prop typo

- www/src/pages/migrating.mdx
> Update migration docs to incorporate Pager component

- src/Col.js
- src/Container.js
- www/src/pages/getting-started/introduction.mdx
Fixes a few typos in some of the documentation on the site.
> Typo Fixes

- www/src/examples/Grid/Responsive.js
> Edit typos

- types/components/Dropdown.d.ts
Fixes #3487, Didn't bother checking out and running the build as I don't have yarn setup.
> Fixing Typo with alignRight prop

- src/TabPane.js
> Fix TabPane unmountOnExit

- src/Carousel.js
https://github.com/react-bootstrap/react-bootstrap/issues/3405
> fix: added 'onSlideEnd' to Carousel (fix: #3405)

- www/src/components/ReactPlayground.js
https://github.com/react-bootstrap/react-bootstrap/issues/3485
> fix: form validation example (fix: #3485)

- package.json
- src/Carousel.js
- types/components/Carousel.d.ts
- yarn.lock
https://github.com/react-bootstrap/react-bootstrap/issues/3509
> feat: added 'as' prop to Carousel (fix: #3509)

- package.json
> update the package doc

- package.json
- src/ListGroupItem.js
- src/Modal.js
- src/ModalDialog.js
- yarn.lock
> Modal scrollable

- types/components/ToggleButtonGroup.d.ts
- types/simple.test.tsx
Checkbox ToggleButtonGroup holds array of T rather than singleton.
> Value typing for Checkbox ToggleButtonGroup

- package.json
- yarn.lock
Fixes https://github.com/react-bootstrap/react-bootstrap/issues/3620
> fix: Fix Babel config for Google WRS support

- package.json
- yarn.lock
As mentioned in #3616, we don't really use storybook for anything currently.
We should just remove it entirely.
Closes #3396
> Remove Storybook

- www/src/pages/components/navbar.js
Changed internal link on the **Overview** of the **Navbar page** to correctly point to the **Containers** section.
> Corrected internal link for the Navbar page Containers section.

- www/src/components/NavMain.js
> feat(docs): link to the bs 3 docs in the header

- types/components/Accordion.d.ts
- types/components/AccordionCollapse.d.ts
- types/components/AccordionToggle.d.ts
- types/components/index.d.ts
- types/simple.test.tsx
> Add Accordion Types

- src/FormLabel.js
- test/FormLabelSpec.js
> Add htmlFor to label when rendered as column

- www/src/components/NavMain.js
- www/src/components/PageFooter.js
- www/src/pages/index.js
> docs: removed search and added notes for BS 4

- www/src/pages/components/overlays.js
Minor typo fix on overlays component page.
> Typo fix in overlays.js

- src/AccordionToggle.js
> fix: Accordion Component not collapsing when toggled twice

- www/src/pages/components/alerts.mdx
Fix a small typo in the Alerts section of the docs.
> Fix typo in alerts.mdx

- www/src/pages/getting-started/theming.js
Fixes PR: https://github.com/react-bootstrap/react-bootstrap/pull/3673
> docs(getting-started): fixed typos

- src/FormText.js
- test/FormTextSpec.js
> fix(FormText): 'muted' prop bug in <FormText />.

- www/src/components/BrowserGlobalsCodeBlock.js
added missing .min.js to fix 404s
> added missing .min.js

- test/TabsSpec.js
- test/ToggleButtonGroupSpec.js
#3889
Increased test coverage for:
ToggleButtonGroup
ToggleButton,
Tabs,
Tab
> test: Add tests for Tabs, Tab, ToggleButtonGroup and ToggleButton

- types/simple.test.tsx
This was probably missed in #4093 before merge.
> feat: Add simple Popover type test

- .github/ISSUE_TEMPLATE/bug_report.md
- src/Container.js
- src/NavLink.js
- src/ToggleButton.js
- www/src/defaultPropDescriptions.js
- www/src/pages/components/forms.js
- www/src/pages/components/list-group.mdx
- www/src/pages/migrating.mdx
:blue_heart: Fix typos across **react-bootstrap repository**
<details><summary>See all fixed files</summary>
<p>
```
react-bootstrap/.github/ISSUE_TEMPLATE/bug_report.md:23:3: "Reproducable" is a misspelling of "Reproducible"
react-bootstrap/src/Container.js:14:45: "availble" is a misspelling of "available"
react-bootstrap/src/NavLink.js:44:38: "amoungst" is a misspelling of "amongst"
react-bootstrap/src/ToggleButton.js:37:46: "amoungst" is a misspelling of "amongst"
react-bootstrap/www/src/defaultPropDescriptions.js:14:12: "amoungst" is a misspelling of "amongst"
react-bootstrap/www/src/pages/components/forms.js:136:43: "propogate" is a misspelling of "propagate"
react-bootstrap/www/src/pages/components/forms.js:254:67: "psuedo" is a misspelling of "pseudo" …
```
> Fix typos across react-bootstrap repository

- src/PageItem.js
- src/Tab.js
- test/DropdownSpec.js
- test/InputGroupSpec.js
- test/ModalSpec.js
- test/PageItemSpec.js
- test/TabsSpec.js
> tests: Increase Test coverage

- src/Button.js
> fix(Button): not pass type prop to custom comp (fix: #3340)

- www/src/examples/Form/Basic.js
`formBasicChecbox` -> `formBasicCheckbox`
> docs: Fix misprint

- www/src/examples/Form/ValidationFormik.js
- validation for lastName field actually validated firstName field instead
> docs: fixed formik validation example for lastName field

- src/Badge.js
- test/BadgeSpec.js
- types/components/Badge.d.ts
- types/simple.test.tsx
> feat: Add the as prop to Badge to support actionable badges

- README.md
- www/src/components/NavMain.js
> docs: updated link for old bs3 docs on Netlify

- src/Image.js
- src/ProgressBar.js
> feat(refs): migrate more components to properly forward their refs

- src/FormCheckLabel.js
https://github.com/react-bootstrap/react-bootstrap/issues/4335
> fix(form): remove unused default props definition 

- package.json
- yarn.lock
> Drops @react-bootstrap/react-popper

- package.json
Fixes https://github.com/react-bootstrap/react-bootstrap/issues/4576
> fix: Fix main and module

- test/CarouselSpec.js
Increase test coverage of Carousel and some refactoring of the tests.
Issue: #3889
> tests: Increase Carousel test coverage

- src/Table.js
#4194
Updates Table component to play nice with a passed ref.
> fix(Table): allow passed in refs to be properly forwarded

- src/Pagination.js
> fix(Pagination): support for ref attribute

- src/ResponsiveEmbed.js
> fix(ResponsiveEmbed): support for ref attribute

- src/TabContent.js
> fix(TabContent): support for ref attribute

- src/Table.js
> style: Rename variable in <Table>

- src/NavLink.js
- src/Popover.js
- src/Toast.js
> fix(Popover): support for ref attribute

- src/ToggleButtonGroup.js
> fix(toggle-button-group): migrate to be ref forwarder

- src/OverlayTrigger.js
- types/components/OverlayTrigger.d.ts
> Updated Overlay Trigger to support flip property

- src/PageItem.js
Forwarding ref for the `PageItem` component.
https://github.com/react-bootstrap/react-bootstrap/issues/4194
> [#4194] - Page item forward ref

- test/NavItemSpec.js
- test/NavSpec.js
Issue: #3889
Most of the not covered statements in the (Abstract)Nav are null check of the reference or the navItem key.
I honestly could not figure out the scenarios when those would be null.
If you could tell me the scenarios I would also add tests for those
> tests: added more Nav/Item tests

- www/src/components/SideNav.js
- www/src/pages/about.mdx
Related [issue](https://github.com/react-bootstrap/react-bootstrap/issues/4624)
> Add About section to the website

- package.json
- yarn.lock
Fixes https://github.com/react-bootstrap/react-bootstrap/issues/4398
> chore: Bump dependencies

- www/src/pages/components/overlays.js
Changed "It's include automatically" to "It's included automatically"
> Fixed small spelling error

- types/components/index.d.ts
Added NavLink to typings as it is missing.
> Added NavLink to the typings

- www/src/examples/Carousel/Controlled.js
> docs(Carousel): removed unused prop from example (fix: #4764)

- test/ModalSpec.js
- test/OverlayTriggerSpec.js
Added tests to test two edge cases. Tested for both if the actual fix in the code works. (by removing it locally).
Related to #3889
> tests: added for Modal and OverlayTrigger

- types/components/ListGroup.d.ts
> Add missing horizontal in ListGroupProps

- www/plugins/gatsby-plugin-sorted-assets/README.md
- www/src/pages/getting-started/theming.js
> fixed typos

- www/src/pages/components/modal.js
"demostrate" -> "demonstrate".
> Fix spelling.

- types/components/Container.d.ts
Adding typescript types to support https://github.com/react-bootstrap/react-bootstrap/pull/4902
> fix(Container): fluid breakpoint typings

- www/src/examples/Card/BgColor.js
> docs(card): simplified BgColor example

- www/src/pages/components/navs.mdx
> docs(Navs): Add missing documentation for NavDropdown on website

- src/BreadcrumbItem.js
- test/BreadcrumbItemSpec.js
- types/components/Breadcrumb.d.ts
- types/components/BreadcrumbItem.d.ts
- types/simple.test.tsx
- www/yarn.lock
> feat(BreadcrumbItem): pass props to li element

- types/components/Overlay.d.ts
> Fix type mismatch between Overlay and Popover & Tooltip

- src/AccordionToggle.js
- test/AccordionToggleSpec.js
> fix(AccordionToggle): default button type=button

- www/src/pages/components/navs.mdx
#5090 fixes import statement in docs
> #5090 Fixes docs for NavDropdown in Navs

- package.json
- types/components/Accordion.d.ts
- types/components/AccordionCollapse.d.ts
- types/components/AccordionToggle.d.ts
- types/components/DropdownItem.d.ts
- types/components/Form.d.ts
- types/components/FormCheck.d.ts
- types/components/FormCheckInput.d.ts
- types/components/FormCheckLabel.d.ts
- types/components/FormControl.d.ts
- types/components/FormFile.d.ts
- types/components/FormFileInput.d.ts
- types/components/FormFileLabel.d.ts
- types/components/FormGroup.d.ts
- types/components/FormLabel.d.ts
- types/components/FormText.d.ts
- types/components/helpers.d.ts
- types/simple.test.tsx
Does this seem better? They types are fairly off right now b/c nothing is actually a class anymore.
> fix(types): more accurate form types

- www/src/pages/components/modal.js
Fix LinkedHeading ID for without animation
> Update LinkedHeading ID for Modal "Without Animation" in docs

- types/components/Form.d.ts
- types/components/Switch.d.ts
- types/simple.test.tsx
> types(Form): added Switch

- src/Overlay.js
> docs: Fix overlay typo

- src/index.js
- www/src/components/ReactPlayground.js
- www/src/examples/.eslintrc
- www/src/examples/Accordion/ContexAwareToggle.js
- www/src/examples/Accordion/ContextAwareToggle.js
- www/src/pages/components/accordion.mdx
based on the idea of diceler found at https://github.com/react-bootstrap/react-bootstrap/issues/4140#issuecomment-604130679. I extended from the existing CustomToggle example making as few changes as possible.
> Added Accordion docs example requested in issue #4140

- src/AccordionContext.js
- src/CardContext.js
- src/NavbarContext.js
This will fix #5089 by making each context unique while bundling with Parcel
> Make each context unique to prevent them being optimized away by Parcel

- src/Feedback.js
- src/FormCheck.js
- src/FormFile.js
- test/FeedbackSpec.js
- test/FormCheckSpec.js
- test/FormFileSpec.js
- types/components/Feedback.d.ts
- types/components/FormCheck.d.ts
- types/components/FormFile.d.ts
- types/simple.test.tsx
- www/src/examples/Form/ValidationTooltips.js
- www/src/pages/components/forms.js
> feat(Feedback): Add support for tooltips

- test/CarouselSpec.js
- test/DropdownItemSpec.js
- test/DropdownSpec.js
- test/InputGroupSpec.js
- test/NavbarSpec.js
- test/PageItemSpec.js
- test/PaginationSpec.js
- test/RowSpec.js
> test: Added more tests

- src/Col.js
- types/components/Col.d.ts
- www/src/examples/Grid/OrderingFirstLast.js
- www/src/pages/layout/grid.js
Column order can also be "first" or "last". See https://getbootstrap.com/docs/4.5/layout/grid/#order-classes
> Add first/last column order

- package.json
- tools/build.js
> chore: fix types build output

- www/src/components/NavMain.js
- www/src/layouts/ApiLayout.js
- www/src/layouts/index.js
https://twitter.com/kwuchu/status/1267436741692133376 and https://github.com/reactjs/reactjs.org
It's literally the least we can do with our small microphone
> in solidarity

- www/src/components/Anchor.js
- www/src/components/Heading.js
This PR is just for rewriting two (Heading and Anchor) components to functional components, if it's good, I'm open to rewrite some other components...
> refactor(Heading+Anchor): Rewrite Heading and Anchor to functional components

- test/CarouselSpec.js
Increase test coverage of Carousel
Issue: #3889
> increased test coverage for Carousel

- src/PageItem.js
Hi 👋
Just a little PR in order to rewrite the createButton returned component into a functional component
> refactor(PageItem): Rewrite createButton return to functional component

- src/Collapse.js
- test/CollapseSpec.js
- test/NavbarSpec.js
- types/components/Collapse.d.ts
Hi 👋
Just a little PR in order to rewrite Collapse component into a functional component
> refactor(Collapse): Rewrite Collapse component as functional component

- src/Button.js
- test/ButtonSpec.js
> fix(Button): Use type attribute if specified

- src/Col.js
- test/ColSpec.js
- types/components/Col.d.ts
- types/simple.test.tsx
- www/src/pages/layout/grid.js
Fixes TS definitions to allow null for span in Col.  Also fix some minor wording in layout docs.
#5205
> feat(Col): Allow false to be used for Col span

- src/Toast.js
- test/ToastSpec.js
> fix(Toast): Fix bsPrefix

- test/CarouselSpec.js
Follow-up to #5221.  There was one more failure I saw yesterday in another PR:
AssertionError: expected 0 to equal 2
> test(Carousel): Fix test failure

- src/Form.tsx
Fixes `onSubmit` types in #5037
> fix(Form): Fix types

- src/Overlay.tsx
- www/src/examples/Overlays/Overlay.js
> fix(Overlay): Fix types and overlay example

- src/OverlayTrigger.tsx
- src/Popover.tsx
- src/ToggleButtonGroup.tsx
- src/Tooltip.tsx
- test/OverlayTriggerSpec.js
> Fix placements

- src/Button.tsx
- src/DropdownButton.tsx
- src/DropdownItem.tsx
- src/Figure.tsx
- src/ModalDialog.tsx
- src/Overlay.tsx
- src/PageItem.tsx
- src/Popover.tsx
- src/ProgressBar.tsx
- src/SafeAnchor.tsx
- src/Spinner.tsx
- src/SplitButton.tsx
- src/TabPane.tsx
- src/ToggleButton.tsx
- src/Tooltip.tsx
- tests/simple-types-test.tsx
Fixes #5278, #5277 and other random type issues
> Fix various types

- www/src/pages/components/forms.js
Added some info about `noValidate` in forms
> docs(Form): Add info about noValidate

- src/PageItem.tsx
- tests/simple-types-test.tsx
fixes #5300 
hopefully this is all that I needed to change! happy to make any other fixes
> Fix TypeScript typing for PageItem

- www/src/components/LinkToSource.js
This PR is raised to fix issue #5308
It is a simple issue but a silent one as well. I thought I should fix so that proud users like me can navigate on the UI easily.
Please accept.
fixes #5308
> Changed the link to point to tsx components

- src/FormControl.tsx
- test/FormControlSpec.js
- tests/simple-types-test.tsx
- www/src/examples/Form/ColorPicker.js
- www/src/pages/components/forms.js
- www/src/pages/migrating.mdx
https://v5.getbootstrap.com/docs/5.0/forms/form-control/#color
> feat(v5): Add FormControl color support

- src/Form.tsx
> fix(Form) : fix type HTMLElement  to HTMLFormElement

- www/src/components/SideNav.js
Hopefully this minor change is all that is necessary.
> Solving sidebar scroll not working #3765

- src/Modal.tsx
- src/ModalDialog.tsx
- test/ModalSpec.js
Adds contentClassName prop for modal, see https://github.com/react-bootstrap/react-bootstrap/issues/3459
> create contentClassName prop

- src/FormLabel.tsx
- test/FormLabelSpec.js
> fix(FormLabel): Add missing class for col label sizing

- src/Badge.tsx
- test/BadgeSpec.js
- www/src/examples/Badge/Basic.js
- www/src/examples/Badge/Button.js
- www/src/examples/Badge/Pill.js
- www/src/examples/Badge/Variations.js
[ x ] Change .badge-variant class to .bg-variant
[ x ] Change .badge-pill class to .rounded-pill
Link: https://github.com/react-bootstrap/react-bootstrap/projects/2#card-42008293
New request from: https://github.com/react-bootstrap/react-bootstrap/pull/5345
> v5: Update Badge classes

- src/DropdownButton.tsx
- src/DropdownMenu.tsx
- src/SplitButton.tsx
- test/DropdownMenuSpec.js
- tests/simple-types-test.tsx
- www/src/examples/Dropdown/MenuAlignResponsive.js
- www/src/examples/Dropdown/MenuAlignRight.js
- www/src/pages/components/dropdowns.mdx
> feat(DropdownMenu): Add responsive menu alignment

- www/src/components/NavMain.js
Changes react-bootstrap version for BS3 to the latest in version dropdown
> docs: Fix BS3 version

- www/src/pages/components/spinners.mdx
Fixes for Documentation typo on Spinner component #5436
> Documentation typo on Spinner component

- www/package.json
- www/yarn.lock
Getting a number of errors in docs as seen in netlify and my local dev env.  This is resolved when rolling back ast-types and babel packages.  
https://app.netlify.com/sites/react-bootstrap/deploys/5f7caea18784c00007406ef6
> 10:54:07 AM: error There was a problem parsing component metadata for file: "AbstractNav.tsx" Maximum call stack size exceeded
10:54:07 AM: 
10:54:07 AM: 
10:54:07 AM:   RangeError: Maximum call stack size exceeded
10:54:07 AM:   
10:54:07 AM:   - path.js:58 NodePath.get
10:54:07 AM:     [www]/[react-docgen]/[ast-types]/lib/path.js:58:26
10:54:07 AM:   
10:54:07 AM:   - path-visitor.js:200 visitChildren
10:54:07 AM:     [www]/[react-docgen]/[ast-types]/lib/path-visitor.js:200:38
10:54:07 AM:   
10:54:07 AM:   - path-visitor.js:166 Visitor.PVp.visitWithoutReset …
> fix(docs): Move ast-types to resolutions

- www/src/pages/components/navbar.js
> docs(Navbar): Fix links

- src/Modal.tsx
Fixes #5527
Ref: https://github.com/twbs/bootstrap/issues/30687
> fix(Modal): Remove role="document" from ModalDialog

- package.json
- yarn.lock
> fix(types): Set @types/react as optional peer dependency

- src/Carousel.tsx
- test/CarouselSpec.js
- www/src/examples/Carousel/DarkVariant.js
- www/src/pages/components/carousel.mdx
https://v5.getbootstrap.com/docs/5.0/components/carousel/#dark-variant
- Adds `variant` to Carousel
> feat(v5): Add Carousel dark variant

- src/PageItem.tsx
> Updated the doc to show PageItem component can take onClick prop

- src/Carousel.tsx
Fixes #5431
I used a single var to track paused state because mouseover/mouseout events can be triggered on touch devices in addition to touch events. In the case of my iPhone, mouseover event is triggered after a touchend event.
I had trouble getting a test to work for this fix.  I was unable to trigger the carousel to automatically run the next slide when simulating touch events.  I ended up testing locally on Chrome and Firefox using simulated touch events and on an iPhone XR.
Preview: https://deploy-preview-5435--react-bootstrap.netlify.app/components/carousel/
> fix(Carousel): fix pause not working properly with touch devices

- src/Navbar.tsx
- www/src/pages/components/navbar.js
> fix(Navbar): remove invalid sticky bottom reference

- src/helpers.ts
- tests/simple-types-test.tsx
> fix: fix TS error with transition types

- package.json
- src/Carousel.tsx
- tests/simple-types-test.tsx
> fix(Carousel): Fix ref type

- www/gatsby-node.js
> docs: switch to new jsx transform

- test/index.js
Ok this is a weird one.  So turns out the failing prop-types checks were in fact, due to the new jsx transform.  
The new react jsx runtime uses a different `checkPropTypes` function than than the old one.  This new function sends in a string with args to `console.error` which fails our check in the `console.error` stub because we weren't expecting unformatted strings.  In contrast, the old runtime uses `checkPropTypes` from `prop-types` and this formats the string prior to sending it to `console.error`.
This patch fixes the `console.error` stub to format the string when there are args passed.
> test: fix tests that use shouldWarn

- src/TransitionWrapper.tsx
Fix some lint issues that came from updating eslint rules
> chore: fix lint

- www/src/examples/Form/CheckInline.js
> added "name" attribute to radio and checkbox examples

- www/src/examples/Navbar/Basic.js
- www/src/examples/Navbar/Brand.js
- www/src/examples/Navbar/Collapsible.js
- www/src/examples/Navbar/ColorSchemes.js
- www/src/examples/Navbar/ContainerOutside.js
- www/src/examples/Navbar/TextLink.js
https://github.com/react-bootstrap/react-bootstrap/issues/5752
Updated navbar examples in https://react-bootstrap-v5.netlify.app/components/navbar/#navbars-containers to add the .container tag per @kyletsang notes.
Preview: https://deploy-preview-5766--react-bootstrap-v5.netlify.app/components/navbar/
> update navbar container

- www/src/pages/getting-started/introduction.mdx
> docs: use specific Bootstrap version in install command

- src/Overlay.tsx
- src/types.tsx
- test/OverlaySpec.js
> feat(Overlay): add ref support

- src/Row.tsx
- test/RowSpec.js
#5751 @kyletsang can't seem to add reviewers, can you let me know if I understood the specs correctly? Thank you!
> changed .no-gutter to g-0

- www/src/pages/index.js
Fixed issue #5797 
Mobile View
Before :
After:
Web View
Before:
After:
> Fixed homepage appearance in mobile view

- src/Offcanvas.tsx
- www/src/examples/Offcanvas/Placement.js
- www/src/pages/components/offcanvas.mdx
Added missing modifier class: .offcanvas-top
https://getbootstrap.com/docs/5.0/components/offcanvas/
> feat(Offcanvas): add .offcanvas-top

- www/src/pages/components/navbar.js
> fix(docs): remove Navbar sticky: bottom (issue #5831)

- package.json
- src/Collapse.tsx
- src/SafeAnchor.tsx
- src/Spinner.tsx
- yarn.lock
> fix(types): fix role prop

- src/DropdownMenu.tsx
- test/NavDropdownSpec.js
> Fix NavDropdown with align="end"

- src/Carousel.tsx
- src/ThemeProvider.tsx
- test/CarouselSpec.js
> feat(Carousel): add RTL keyboard support

- package.json
- src/Modal.tsx
- yarn.lock
> fix(Modal): Fix wrong types on ModalProps

- www/src/pages/migrating.mdx
> docs: add note about breaking changes in Badge

- src/Popover.tsx
- src/Tab.tsx
- src/Tooltip.tsx
- src/types.tsx
- tests/simple-types-test.tsx
Fixes several type issues and fixes TabContainer export
> fix: fix exports and types

- src/Collapse.tsx
- src/Fade.tsx
Related to issue: https://github.com/react-bootstrap/react-bootstrap/issues/5966
> Indicate single child element requirement in Collapse and Fade components

- src/Offcanvas.tsx
- test/OffcanvasSpec.js
> fix: changed .modal-backdrop to .offcanvas-backdrop

- src/DropdownMenu.tsx
- www/src/pages/components/input-group.js
> fix(Dropdown): fix menu positioning when renderOnMount=true

- src/AccordionCollapse.tsx
- test/AccordionSpec.js
Added As prop in AccordionCollapse Component as mentioned in 
https://github.com/react-bootstrap/react-bootstrap/issues/5659#issue-809664968
> Add As Prop in AccordionCollapse Component, Fix Issue: #5659

- src/Modal.tsx
> fix(Modal): fix children typing

- package.json
> Update @restart/ui dep to 0.2.3

- .github/workflows/ci.yml
> Add dependency caching to CI

- www/src/pages/components/badge.mdx
Pill pages haven't additional padding
> Remove inforamtion about padding in pill bages

- src/ListGroupItem.tsx
- test/ListGroupSpec.js
> fix(ListGroupItem): fix .active not being set with activeKey

- src/InputGroup.tsx
> fix(InputGroup): fix export

- src/ListGroup.tsx
- test/ListGroupSpec.js
- www/src/examples/ListGroup/Numbered.js
- www/src/examples/ListGroup/NumberedCustom.js
- www/src/pages/components/list-group.mdx
Ref: https://getbootstrap.com/docs/5.1/components/list-group/#numbered
> feat(ListGroup): add `numbered` prop

- src/NavDropdown.tsx
> fix(NavDropdown): fix `onSelect` type

- src/Modal.tsx
> fix(Modal): fix typescript intellisense with base props

- src/Accordion.tsx
- src/AccordionButton.tsx
- src/AccordionCollapse.tsx
- src/AccordionContext.ts
- test/AccordionButtonSpec.js
- test/AccordionSpec.js
- www/src/examples/Accordion/AlwaysOpen.js
- www/src/pages/components/accordion.mdx
Ref: https://getbootstrap.com/docs/5.1/components/accordion/#always-open
Closes #6063
> feat(Accordion): add `alwaysOpen` prop

- test/ToastHeaderSpec.tsx
- test/ToastSpec.tsx
While writing up some more tests, I've noticed that some of the previous tests were not wrapped in a `should`, making them a little bit spotty.
> test: fix toast tests

- src/ThemeProvider.tsx
- test/TabsSpec.tsx
- test/ThemeProviderSpec.tsx
Part of #6156 
Futher changes, but there's one big caveat here - I've had to remove one test, cause it seems like `chai`'s `expect` is unable to catch a error thrown by `<Tab />` when it's rendered by itself. I've tried wrapping it in error boundaries and trying to workaround this issue in different ways, but was unable to port the test.
To be sure that this is the problem with `chai` and not my approach I've implemented a simple `jest` setup under [a new branch](https://github.com/golota60/react-bootstrap/tree/jest-test), which shows that there are no issues when using `jest`. 
If you want to see it simply checkout the branch, install deps and run `yarn test:jest` which runs the said test.
There's always a possibity that I'm doing something wrong, feel free to point it out or have a stab …
> test: Move Tabs and ThemeProvider specs to rtl

- www/src/components/CarbonAds.js
- www/src/components/NavMain.js
- www/src/components/SideNav.js
- www/src/css/carbonads.scss
- www/src/css/global.scss
- www/src/layouts/ApiLayout.js
- www/src/layouts/index.js
- www/src/pages/index.js
Adds the ad into a couple places:
- Main page under the Get Started buttons
- Bottom of the sidenav where the components are listed
Preview:
https://deploy-preview-6195--react-bootstrap.netlify.app/
> docs: add Carbon ads

- test/AccordionSpec.tsx
> test(Accordion): migrate to rtl

- test/ModalSpec.tsx
Tests for Modal component
part of https://github.com/react-bootstrap/react-bootstrap/issues/6156
> test: move Modal to RTL

- src/TabPane.tsx
- test/TabsSpec.tsx
> fix(TabPane): use Fade for default transition

- www/src/examples/ListGroup/NumberedCustom.js
The `bg` prop seems to be the right one to set the badge style/variant as per docs.
> Replace Badge variant with bg

- test/AccordionButtonSpec.tsx
- test/AlertSpec.tsx
- test/BadgeSpec.tsx
- test/BreadcrumbItemSpec.tsx
- test/ButtonSpec.tsx
- test/FigureCaptionSpec.tsx
- test/FormCheckSpec.tsx
- test/ImageSpec.tsx
- test/ModalBodySpec.tsx
- test/ModalFooterSpec.tsx
- test/ModalHeaderSpec.tsx
- test/ModalSpec.tsx
- test/ModalTitleSpec.tsx
- test/TabsSpec.tsx
- test/ToastSpec.tsx
Fixes a number of ts lint warnings
> chore(tests): fix lint

- package.json
- src/Carousel.tsx
- www/src/components/NavMain.js
- www/src/examples/Overlays/Overlay.js
- Updates package keywords
- Fixes carousel interval props description
- Fixes custom overlay example not working in certain positions
- Revert header z-index change
> docs: various doc improvements

- package.json
- yarn.lock
> chore: bump @restart/hooks

- src/PageItem.tsx
- test/PaginationSpec.tsx
> feat(Pagination): Wrap Pagination sub-components in forward refs

- src/Dropdown.tsx
> Update Dropdown's docs on onToggle function

- package.json
- yarn.lock
> fix: update react-overlays and @restart/hooks packages

- src/Table.tsx
- test/TableSpec.tsx
- www/src/examples/Table/StripedColumns.js
- www/src/examples/Table/StripedRow.js
- www/src/pages/components/table.mdx
Added support for Striped Columns as per v5.2 
https://getbootstrap.com/docs/5.2/content/tables/#striped-columns
> feat(Table): added support for striped columns

- src/Offcanvas.tsx
- test/OffcanvasSpec.tsx
- www/src/examples/Offcanvas/StaticBackdrop.js
- www/src/pages/components/offcanvas.mdx
5.2 beta feature:
https://getbootstrap.com/docs/5.2/components/offcanvas/#static-backdrop
> feat(Offcanvas): added support for static backdrops

- www/.eslintrc.js
- www/src/components/BreakpointTable.js
- www/src/components/CarbonAds.js
- www/src/examples/AsProp.js
Fixes eslint errors as seen here:
https://github.com/react-bootstrap/react-bootstrap/pull/6368#discussion_r892912865
> chore: fix eslint for docs

- package.json
- yarn.lock
> fix: update @restart/ui to v1.3.0

- www/src/examples/AsProp.js
- www/src/pages/getting-started/introduction.mdx
> docs: fix as prop example

- www/package.json
- www/yarn.lock
Fails to build docs locally for me so had to revert.  Strangely it passed on the netlify build.  Will investigate later.
> chore: revert gatsby-plugin-mdx

- package.json
- www/src/examples/Tabs/LeftTabs.js
- yarn.lock
> fix: update @restart/ui to 1.3.1

- www/src/pages/getting-started/introduction.mdx
Add an extra space to ensure consistency across other comments' format.
> docs: add space for consistency in introduction.mdx.

- src/Modal.tsx
- test/ModalSpec.js
Fixes #6421
Backport of 2 fixes in the master branch but with modifications to test in enzyme
> Modal fixes for v1

- CONTRIBUTING.md
From:
To:
APIs should be be -->APIs should be
> '[Docs] Fixes typo in CONTRIBUTING.md'

- www/src/pages/components/forms.js
> fix(v4): Fix iconic link

- karma.conf.js
- package.json
- yarn.lock
Also needed a polyfill for process/browser otherwise karma wouldn't run.
> chore(deps): update sinon to v14

- www/package.json
- www/yarn.lock
Following [JavaScript Components > Update Files](https://fontawesome.com/docs/web/setup/upgrade/js-components#update-files)
> Update Font Awesome icons

- www/src/pages/components/navbar.mdx
> docs(Navbar): fix placement links

- src/Popover.tsx
- src/Tooltip.tsx
Fixes #6550
Fixes the out of sync animation for the arrow
> fix(Overlay): fix arrow animation

- www/src/examples/Toast/Placement.js
- www/src/examples/Toast/PlacementMulti.js
- www/src/examples/Toast/Stacking.js
these changes resolves the ( ToastContainer changes https://github.com/react-bootstrap/react-bootstrap/issues/6552 ) by precising the position to relative of the Toasts Stacking code example and also the ( Bug: Z-index problem in the components/toasts/ page https://github.com/react-bootstrap/react-bootstrap/issues/6564 ) by specifying the zIndex for each code example related to that problem
> Final_Version_Fixed_Toast_Layout

- package.json
- yarn.lock
https://github.com/react-restart/ui/pull/79
Fixes #6589
> fix: downgrade uncontrollable to 7.2.1

- src/Popover.tsx
> fix(Popover): fix `content` prop error

- src/Button.tsx
docs(Button): Added onClick event to button docs (#5405)
Added onClick event as specified in the issue #5405
> docs(Button): Added onClick event to button docs (#5405)

- www/package.json
- www/yarn.lock
Fixes #6660
Fall back to default cssnano preset to compile css.  https://docusaurus.io/docs/cli#docusaurus-build-sitedir
> docs: compile css with default cssnano preset

- www/docs/examples/Carousel/CarouselFade.js
- www/docs/examples/Carousel/Controlled.js
- www/docs/examples/Carousel/IndividualIntervals.js
- www/docs/examples/Carousel/NoTransition.js
- www/docs/examples/Carousel/Uncontrolled.js
- www/src/components/ExampleCarouselImage.tsx
- www/src/css/examples.scss
- www/src/theme/ReactLiveScope.ts
Fixes colors so it looks better in dark mode
> docs: fix carousel example colors

- www/docs/components/navbar.mdx
- www/docs/examples/Navbar/Form.js
> navbar form example added

- .github/workflows/ci.yml
> chore(ci): remove ubuntu firefox install step

- www/docs/examples/Navbar/Basic.js
- www/src/css/examples.scss
> fix: broken responsive navbar in docs page

- src/types.tsx
> fix(types): loosen color and gap types

- www/docs/examples/Modal/StaticBackdrop.js
Typo fix in "Static backdrop" modal example code.
> docs: Fix typo

- src/index.tsx
fix #6731
man, opening the issue takes longer than fixing it...
> Add AccordionBody to exports

- src/Modal.tsx
Close https://github.com/react-bootstrap/react-bootstrap/issues/6742
> fix(Modal): handle `data-bs-theme` attribute

- www/src/css/examples.scss
> docs: fix range track color

- src/FormCheck.tsx
Introduced in commit ab9e08094 but not yet documented.
> docs: Add feedbackType to FormCheck

- src/Carousel.tsx
Added missing close codeblocks for onSlide and onSlid callbacks
> Fix Carousel codeblocks

- www/package.json
- www/plugins/react-docgen-plugin/index.js
- www/plugins/react-docgen-plugin/resolveHocComponents.js
- www/yarn.lock
> docs: rollback react-docgen

- karma.conf.js
- package.json
- test/index.js
- test/useOverlayOffsetSpec.tsx
- yarn.lock
Remove last bits of enzyme.  Will try updating to react 18 after
> chore: remove enzyme

- www/package.json
- www/src/theme/MDXContent.tsx
- www/tsconfig.json
- www/yarn.lock
Fixes #6838
Latest release fixes an issue with the Algolia queries in the search page.
> docs: update docusaurus to v3.5.2

- src/AccordionHeader.tsx
- test/AccordionHeaderSpec.tsx
> fix(AccordionHeader): apply aria-controls to button

- package.json
- src/Collapse.tsx
- src/Fade.tsx
- src/OffcanvasToggling.tsx
- src/OverlayTrigger.tsx
- yarn.lock
> fix: fix ref access in React 19

- www/src/css/examples.scss
> Fix Progress bar and spinner spacing

- src/Navbar.tsx
Closes https://github.com/react-bootstrap/react-bootstrap/issues/6882
> fix(Navbar): fix react 19 type compatibility

- .eslintrc
- package.json
- yarn.lock
> fix: update @restart/ui to v1.9.4

- src/Navbar.tsx
> fix(Navbar): add defaultExpanded type

- package.json
- src/NavbarOffcanvas.tsx
- src/Offcanvas.tsx
- www/docs/migrating/migrating_v2.mdx
- yarn.lock
The existing rendering behavior didn't really work too well with responsive navbars due to the hardcoded breakpoint hook.  This PR aims to fix that deficiency and also bring the behavior closer to how upstream works where it renders the nodes inline in the DOM
BREAKING CHANGE: Offcanvas will always be rendered in the DOM and not at the body using a portal
Closes #6679
Closes #6627
Closes #6839
> feat(Offcanvas)!: change rendering behavior

- www/docs/components/navs.mdx
remove redundant word in comment
> chore: remove redundant word in comment

- package.json
Defaults to chrome so 4c/rollout won't complain
> chore: update test command

- package.json
- yarn.lock
> feat: update @restart/ui to v2.0.0-beta.10
